// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): FSM introspection pins for gears2fsm.
// The PINNED topology was derived from the artifact at build time; any
// unintended structural change to the machine fails this test.
import { describe, expect, it } from 'vitest';

import { findMachineConfig, pinIntrospection } from '@sublang/slc/verify';
import * as fsm from './gears2fsm.fsm.ts';

const PINNED = {
  initial: 'ready',
  captain: [
    {
      state: 'transform',
      sourceItem: 'G2F-1',
      player: 'Captain',
      resultKeys: ['needsBossReply', 'transformed'],
      onDone: [
        {
          index: 0,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 1,
          target: 'failed',
          guarded: true,
        },
        {
          index: 2,
          target: 'done',
          guarded: true,
        },
        {
          index: 3,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
  ],
  quiescent: [
    {
      state: 'ready',
      final: false,
      on: {
        START: [
          {
            index: 0,
            target: 'transform',
            guarded: false,
          },
        ],
      },
    },
    {
      state: 'awaitBossReply',
      final: false,
      on: {
        BOSS_REPLY: [
          {
            index: 0,
            target: 'failed',
            guarded: true,
          },
          {
            index: 1,
            target: 'transform',
            guarded: true,
          },
        ],
        BOSS_INTERRUPT: [
          {
            index: 0,
            target: 'ready',
            guarded: true,
          },
          {
            index: 1,
            target: 'transform',
            guarded: true,
          },
        ],
        START: [
          {
            index: 0,
            target: 'transform',
            guarded: false,
          },
        ],
      },
    },
    {
      state: 'failed',
      final: false,
      on: {
        START: [
          {
            index: 0,
            target: 'transform',
            guarded: false,
          },
        ],
      },
    },
    {
      state: 'done',
      final: true,
      on: {},
    },
  ],
  rootOn: {
    BOSS_INTERRUPT: [
      {
        index: 0,
        target: 'ready',
        guarded: true,
      },
      {
        index: 1,
        target: 'transform',
        guarded: true,
      },
    ],
  },
  interruptTargets: ['ready', 'transform'],
};

describe('gears2fsm: FSM introspection', () => {
  it('matches the machine topology pinned at build time', () => {
    expect(pinIntrospection(findMachineConfig(fsm))).toEqual(PINNED);
  });
});
