// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): prompt contract.
// The pinned rows were derived from the artifacts at build time; wiring,
// placeholder, or composition drift fails this test.
import { describe, expect, it } from 'vitest';

import {
  capturePromptContract,
  checkPromptComposition,
  deriveSubstitutions,
  findMachineConfig,
} from './.slc-verify/verify.js';
import * as fsm from './gears2fsm.fsm.js';
import * as playbook from './gears2fsm.playbook.js';

const CONTRACT = [
  {
    state: 'transform',
    sourceItem: 'GEARS2FSM-1',
    player: '',
    reads: ['bossReply', 'definition', 'pendingBossQuestion'],
    wires: {
      definition: ['definition'],
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: ['<definition>'],
  },
];
const SCHEMA_FINDINGS = [];

describe('gears2fsm: prompt contract', () => {
  it('uses consistent artifact-schema evidence', () => {
    expect(SCHEMA_FINDINGS).toEqual([]);
  });

  it('matches the prompt contract pinned at build time', () => {
    expect(capturePromptContract(findMachineConfig(fsm))).toEqual(CONTRACT);
  });

  const CAPTAIN_SUBSTITUTED = {
    transform: ['<definition>'],
  };

  const composeCaptain = (
    playbook as unknown as {
      _internal: { composeCaptainPrompt: (input: unknown) => string };
    }
  )._internal.composeCaptainPrompt;

  it('composes Captain prompts per the link contract', () => {
    expect(
      checkPromptComposition({
        config: findMachineConfig(fsm),
        compose: composeCaptain,
        actor: 'captain',
        artifactSchema: 3,
      }),
    ).toEqual([]);
  });

  it('substitutes the Captain placeholders pinned at build time', () => {
    expect(
      deriveSubstitutions(findMachineConfig(fsm), composeCaptain, 'captain'),
    ).toEqual(CAPTAIN_SUBSTITUTED);
  });
});
