// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by slc/link.md (FSM-to-Runtime linker).
// Source FSM:    ./gears2fsm.fsm.ts
// Role metadata: none — the machine declares no delegated `player` state, so
//                `roleStates` and `outcomeAuthority.governedPlayerStates` are
//                explicitly empty
// Boss event:    deterministic TRANSFORMATION_REQUEST entry; the exact Boss
//                text rides `request`, which the machine's
//                `copyTransformationRequest` action copies into the context
//                member of the same name (DR-034). BOSS_INTERRUPT and
//                BOSS_REPLY stay judge-classified; their contracts are derived
//                from the machine, so no `bossEvents` entry is emitted
// Adjudication:  LLM judge per state (the direct-Captain default). The visible
//                Captain call owns the `question` presentation field. This
//                phase is a transformation-performing Captain that writes a
//                declared target artifact, so its calls carry no `allowedTools`
//                restriction and preserve the host Captain's configured tools
// Compat:        artifact schema 3 / runtime ABI 1

import {
  createXStatePlaybookRuntime,
  defaultComposeCaptainPrompt,
  snapshotJsonValue,
  type XStatePlaybookRuntimeConstruction,
  type XStatePlaybookRuntimeFactory,
  type XStatePlaybookRuntimeSpecV3,
} from '@sublang/playbook/xstate-runtime';
import { machine, type MachineInput } from './gears2fsm.fsm.ts';
import type { PlaybookHostConstructionCapabilities } from '@sublang/playbook/playbook-captain';
import type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookControlReceipt,
  PlaybookControlView,
  PlaybookPendingCall,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlayerResult,
  PlayerSessionStore,
} from '@sublang/playbook/runtime';

export type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookControlReceipt,
  PlaybookControlView,
  PlaybookPendingCall,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlayerResult,
  PlayerSessionStore,
};

/**
 * Every required FSM input field not supplied by `PlaybookSession` or another
 * linker-owned source. `definition` is the host-owned phase definition the
 * GEARS blockquote relays through its `<definition>` placeholder; the machine
 * carries it as immutable input and context. The FSM declares no `script`
 * state, so no `cwd` option is declared.
 */
export type Gears2FsmPlaybookOptions = MachineInput;

/** The artifact's live schema-3 capability type: authority, repository, ledger. */
export type Gears2FsmPlaybookHostCapabilities =
  PlaybookHostConstructionCapabilities &
    XStatePlaybookRuntimeConstruction<
      Gears2FsmPlaybookOptions,
      object
    >['hostCapabilities'];

/**
 * The machine's `awaitBossReply` leaf also carries a malformed-reply fallback
 * arm targeting `failed`, which is not a resume destination. The suspended
 * working leaf is the sole `BOSS_REPLY` resume target, so the set is declared
 * rather than derived from that state's transition targets.
 */
const RESUMABLE_STATE_IDS: ReadonlySet<string> = new Set(['transform']);

/** No delegated-player state declares a verbatim-final-text payload field. */
const VERBATIM_PAYLOAD_FIELDS: ReadonlySet<string> = new Set();

/**
 * Neither `compiled` nor `rejected` is declared to leave the procedure
 * unfinished, and the set is never inferred from a state description or
 * procedure prose, so it is explicitly empty.
 */
const UNFINISHED_FINAL_STATE_IDS: ReadonlySet<string> = new Set();

function snapshotGears2FsmOptions(value: unknown): Gears2FsmPlaybookOptions {
  const captured = snapshotJsonValue(value, 'GEARS2FSM runtime options');
  if (
    captured === null ||
    typeof captured !== 'object' ||
    Array.isArray(captured)
  ) {
    throw new TypeError('GEARS2FSM runtime options must be an object');
  }
  const record = captured as Readonly<Record<string, JsonValue>>;
  for (const key of Object.keys(record)) {
    if (key !== 'definition') {
      throw new TypeError(`GEARS2FSM runtime options.${key} is not declared`);
    }
  }
  if (typeof record.definition !== 'string') {
    throw new TypeError(
      'GEARS2FSM runtime options.definition must be a string',
    );
  }
  return captured as unknown as Gears2FsmPlaybookOptions;
}

export const _internal = {
  // The spec overrides no composition, so the machine's direct-Captain calls
  // are composed by the shared default composer itself.
  composeCaptainPrompt: defaultComposeCaptainPrompt,
  RESUMABLE_STATE_IDS,
  VERBATIM_PAYLOAD_FIELDS,
  UNFINISHED_FINAL_STATE_IDS,
};

const runtimeSpec = {
  label: 'GEARS2FSM',
  // DR-022 / slc/link.md: the declaration carries the value current at link
  // time — a literal, never the loading engine's RUNTIME_ABI self-report,
  // which would follow whatever engine loads the module and make the
  // factory's skew check compare that engine with itself.
  compat: { artifactSchema: 3, runtimeAbi: 1 },
  snapshotOptions: snapshotGears2FsmOptions,
  entryEvent: {
    type: 'TRANSFORMATION_REQUEST',
    textField: 'request',
    // `copyTransformationRequest` copies the entry text here, so the
    // failure-state retry reads it back from the persisted machine snapshot
    // and survives a continued session (DR-034).
    contextField: 'request',
  },
  // The machine invokes only the direct `captain` actor.
  roleStates: {},
  outcomeAuthority: { governedPlayerStates: {} },
  verbatimPayloadFields: VERBATIM_PAYLOAD_FIELDS,
  resumableStateIds: RESUMABLE_STATE_IDS,
  controlContextFields: [],
  unfinishedFinalStateIds: UNFINISHED_FINAL_STATE_IDS,
  transitionEventFields: ['request', 'targetId', 'answer', 'questionId'],
} satisfies XStatePlaybookRuntimeSpecV3<Gears2FsmPlaybookOptions>;

const createPlaybookRuntime: XStatePlaybookRuntimeFactory<
  XStatePlaybookRuntimeConstruction<
    Gears2FsmPlaybookOptions,
    Gears2FsmPlaybookHostCapabilities
  >,
  3
> = createXStatePlaybookRuntime<
  Gears2FsmPlaybookOptions,
  Gears2FsmPlaybookHostCapabilities
>(machine, runtimeSpec);

export default createPlaybookRuntime;
