// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): FSM introspection pins.
// The PINNED topology was derived from the artifact at build time; any
// unintended structural change to the machine fails this test.
import { describe, expect, it } from 'vitest';

import { findMachineConfig, pinIntrospection } from './.slc-verify/verify.js';
import * as fsm from './gears2fsm.fsm.js';

const PINNED = {
  initial: 'ready',
  captain: [
    {
      state: 'transform',
      actor: 'captain',
      sourceItem: 'GEARS2FSM-1',
      player: '',
      resultKeys: ['compiled', 'needsBossReply', 'rejected'],
      onDone: [
        {
          index: 0,
          target: 'compiled',
          guarded: true,
        },
        {
          index: 1,
          target: 'rejected',
          guarded: true,
        },
        {
          index: 2,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 3,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
  ],
  quiescent: [
    {
      state: 'ready',
      final: false,
      on: {
        TRANSFORMATION_REQUEST: [
          {
            index: 0,
            target: 'transform',
            guarded: true,
          },
        ],
      },
    },
    {
      state: 'awaitBossReply',
      final: false,
      on: {
        BOSS_REPLY: [
          {
            index: 0,
            target: 'transform',
            guarded: true,
          },
          {
            index: 1,
            target: 'failed',
            guarded: false,
          },
        ],
      },
    },
    {
      state: 'failed',
      final: false,
      on: {
        TRANSFORMATION_REQUEST: [
          {
            index: 0,
            target: 'transform',
            guarded: true,
          },
        ],
      },
    },
    {
      state: 'compiled',
      final: true,
      on: {},
    },
    {
      state: 'rejected',
      final: true,
      on: {},
    },
  ],
  rootOn: {
    BOSS_INTERRUPT: [
      {
        index: 0,
        target: 'transform',
        guarded: true,
      },
    ],
  },
  interruptTargets: ['transform'],
};

describe('gears2fsm: FSM introspection', () => {
  it('matches the machine topology pinned at build time', () => {
    expect(pinIntrospection(findMachineConfig(fsm))).toEqual(PINNED);
  });
});
