// Linked playbook runtime — generated by slc link (slc/link.md).
//
// Linker inputs:
//   FSM artifact:           ./workflow.zh.fsm.ts
//   Adjudication strategy:  LLM-judge per state (default, every delegated-player state)
//   Boss-event mapping:     deterministic textual entry event `BOSS_TASK`,
//                           free-text judge classification otherwise (default)
//   Link options:           (none)
//
// Output profile: thin shared-factory module (§Output) — the FSM declares no
// `type: 'parallel'` state, so every interpreter concern (actor wiring, trace
// emission, Boss-event mapping, adjudication, script execution, session
// lifecycle, abort handling, snapshot/adoption/control surfaces) ships once in
// `createXStatePlaybookRuntime` rather than being regenerated here.
//
// The FSM is imported with a `.ts` runtime specifier: this artifact is
// source-only (no JavaScript sibling is built or shipped beside it) and its
// host loads TypeScript directly.

import {
  createXStatePlaybookRuntime,
  defaultComposePlayerPrompt,
} from '@sublang/playbook/xstate-runtime';
import type {
  XStateBossEventSpec,
  XStateOutcomeAuthoritySpec,
  XStatePlaybookRuntimeConstruction,
  XStatePlaybookRuntimeFactory,
  XStatePlaybookRuntimeSpecV3,
  XStateRepositoryCapability,
  XStateRoleStateStatus,
} from '@sublang/playbook/xstate-runtime';
import type { PlaybookEffectLedgerCapability } from '@sublang/playbook/runtime';
import type { RoleId } from './workflow.zh.fsm.ts';
import { workflowMachine } from './workflow.zh.fsm.ts';

export type {
  CaptainCallOptions,
  CaptainResult,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlayerCallOptions,
  PlayerResult,
  PlayerSessionStore,
} from '@sublang/playbook/runtime';

const LABEL = 'workflow.zh';

/**
 * Per-run options for this playbook. The FSM's only input field
 * (`bossIntent`) is optional and is supplied by the linker-owned entry event
 * carrying the exact Boss text, so it is not a caller option; `cwd` is
 * declared because the FSM contains a `script` state (WORKFLOW-1).
 */
export interface PlaybookRuntimeOptions {
  /** Working directory for the `script` actor. Default: the process cwd. */
  readonly cwd?: string;
}

/** Live schema-3 authority this artifact's Captain host binds. */
export interface WorkflowHostAuthority {
  readonly artifactId: string;
  readonly artifactSchema: 3;
  readonly roles: readonly RoleId[];
  readonly cohorts: readonly (readonly RoleId[])[];
  readonly cwd: string;
  readonly sessionId: string;
  readonly leaseOwnerId: string;
  readonly canonicalWorktree: {
    readonly worktree: string;
    readonly gitDir: string;
  };
}

/** This artifact's exact live schema-3 capability type. */
export interface HostCapabilities {
  readonly authority: WorkflowHostAuthority;
  readonly repository: XStateRepositoryCapability;
  readonly effectLedger: PlaybookEffectLedgerCapability;
}

const OPTION_KEYS: readonly string[] = ['cwd'];

/** Validate and JSON-snapshot the caller's options before any actor exists. */
const snapshotOptions = (value: unknown): PlaybookRuntimeOptions => {
  if (value === undefined) return {};
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new TypeError(`${LABEL} options must be a plain object`);
  }
  for (const key of Reflect.ownKeys(value)) {
    if (typeof key !== 'string' || !OPTION_KEYS.includes(key)) {
      throw new TypeError(
        `${LABEL} options contains undeclared key ${String(key)}`,
      );
    }
    const descriptor = Object.getOwnPropertyDescriptor(value, key);
    if (descriptor === undefined || !('value' in descriptor)) {
      throw new TypeError(
        `${LABEL} options.${key} must be an own data property`,
      );
    }
  }
  const cwd = (value as { cwd?: unknown }).cwd;
  if (cwd === undefined) return {};
  if (typeof cwd !== 'string' || cwd.trim() === '') {
    throw new TypeError(`${LABEL} options.cwd must be a non-empty string`);
  }
  return { cwd };
};

/**
 * Boss-facing identity for every FSM state that invokes the typed `player`
 * actor; each `role` and `label` is copied from that state's FSM metadata.
 */
const roleStates = {
  implementChange: {
    role: '编码者',
    label: '当 Git 仓库准备就绪时，由 `编码者` 按任务要求修改代码并提交 Git。',
  },
  reviewCommit: {
    role: '评审者',
    label:
      '当 `编码者` 完成一次提交时，由 `评审者` review 该 commit 并提出合理问题。',
  },
  judgeFindings: {
    role: '编码者',
    label:
      '当 `评审者` 提出的问题交回 `编码者` 做判断时，由 `编码者` 接受或拒绝并讲清楚原因。',
  },
  debateJudgment: {
    role: '评审者',
    label:
      '如果判断次数少于 3 次，当 `编码者` 拒绝问题时，由 `评审者` 与其争论直至达成一致。',
  },
  rejudgeRebuttal: {
    role: '编码者',
    label: '当 `评审者` 继续争论时，由 `编码者` 再次接受或拒绝并讲清楚原因。',
  },
  reviseByConclusion: {
    role: '编码者',
    label:
      '当双方达成一致，或 `编码者` 已做出总计第 3 次判断而不再争论时，由 `编码者` 按结论修改代码并再次提交。',
  },
} as const satisfies Readonly<Record<string, XStateRoleStateStatus>>;

/**
 * Schema-3 outcome authority: one entry per delegated-player state, naming
 * exactly that state's declared outcomes and exactly the payload fields each
 * outcome's result description requires. The two committing states
 * (WORKFLOW-2, WORKFLOW-7) declare `one-descendant-commit`, so their
 * mid-task Boss question is `deferred`; every reviewing or judging state
 * touches no repository state and declares `unchanged`.
 */
const outcomeAuthority = {
  governedPlayerStates: {
    implementChange: {
      done: { fields: {}, repositoryDisposition: 'one-descendant-commit' },
      needsBossReply: {
        fields: { question: 'presentation' },
        repositoryDisposition: 'deferred',
      },
    },
    reviewCommit: {
      issues: {
        fields: { reviewFindings: 'semantic' },
        repositoryDisposition: 'unchanged',
      },
      clean: { fields: {}, repositoryDisposition: 'unchanged' },
      needsBossReply: {
        fields: { question: 'presentation' },
        repositoryDisposition: 'unchanged',
      },
    },
    judgeFindings: {
      accept: { fields: {}, repositoryDisposition: 'unchanged' },
      reject: {
        fields: { coderJudgment: 'semantic' },
        repositoryDisposition: 'unchanged',
      },
      needsBossReply: {
        fields: { question: 'presentation' },
        repositoryDisposition: 'unchanged',
      },
    },
    debateJudgment: {
      dispute: {
        fields: { reviewerRebuttal: 'semantic' },
        repositoryDisposition: 'unchanged',
      },
      agreed: { fields: {}, repositoryDisposition: 'unchanged' },
      needsBossReply: {
        fields: { question: 'presentation' },
        repositoryDisposition: 'unchanged',
      },
    },
    rejudgeRebuttal: {
      accept: { fields: {}, repositoryDisposition: 'unchanged' },
      reject: {
        fields: { coderJudgment: 'semantic' },
        repositoryDisposition: 'unchanged',
      },
      needsBossReply: {
        fields: { question: 'presentation' },
        repositoryDisposition: 'unchanged',
      },
    },
    reviseByConclusion: {
      done: { fields: {}, repositoryDisposition: 'one-descendant-commit' },
      needsBossReply: {
        fields: { question: 'presentation' },
        repositoryDisposition: 'deferred',
      },
    },
  },
} as const satisfies XStateOutcomeAuthoritySpec;

/**
 * The one Boss-union arm whose payload cannot be recovered from the erased
 * machine types. `BOSS_TASK` is declared as the deterministic entry event and
 * `NO_ACTION` / `BOSS_REPLY` are runtime-owned, so none of them appears here.
 */
const bossEvents = [
  {
    type: 'BOSS_INTERRUPT',
    fields: {
      targetId: {
        source: 'judge',
        required: true,
        values: [
          'implementChange',
          'reviewCommit',
          'judgeFindings',
          'debateJudgment',
          'rejudgeRebuttal',
          'reviseByConclusion',
        ],
      },
    },
  },
] as const satisfies readonly XStateBossEventSpec[];

const spec: XStatePlaybookRuntimeSpecV3<PlaybookRuntimeOptions> = {
  label: LABEL,
  compat: { artifactSchema: 3, runtimeAbi: 1 },
  snapshotOptions,
  machineInput: () => ({}),
  entryEvent: {
    type: 'BOSS_TASK',
    textField: 'bossIntent',
    contextField: 'bossIntent',
  },
  bossEvents,
  roleStates,
  outcomeAuthority,
  verbatimPayloadFields: new Set<string>(),
  transitionEventFields: ['bossIntent', 'targetId', 'answer', 'questionId'],
  controlContextFields: ['loopCount', 'judgmentCount'],
  unfinishedFinalStateIds: new Set<string>(['cycleLimitReached']),
};

const createPlaybookRuntime: XStatePlaybookRuntimeFactory<
  XStatePlaybookRuntimeConstruction<PlaybookRuntimeOptions, HostCapabilities>,
  3
> = createXStatePlaybookRuntime<PlaybookRuntimeOptions, HostCapabilities>(
  workflowMachine,
  spec,
);

export default createPlaybookRuntime;

/** Not a public API: pure helpers compilation-correctness tests exercise. */
export const _internal = {
  composePlayerPrompt: defaultComposePlayerPrompt,
};
