// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): FSM introspection pins.
// The PINNED topology was derived from the artifact at build time; any
// unintended structural change to the machine fails this test.
import { describe, expect, it } from 'vitest';

import { findMachineConfig, pinIntrospection } from './.slc-verify/verify.js';
import * as fsm from './workflow.zh.fsm.js';

const PINNED = {
  initial: 'ready',
  captain: [
    {
      state: 'implementChange',
      actor: 'player',
      sourceItem: 'WORKFLOW-2',
      player: '',
      role: '编码者',
      resultKeys: ['done', 'needsBossReply'],
      onDone: [
        {
          index: 0,
          target: 'reviewCommit',
          guarded: true,
        },
        {
          index: 1,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 2,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
    {
      state: 'reviewCommit',
      actor: 'player',
      sourceItem: 'WORKFLOW-3',
      player: '',
      role: '评审者',
      resultKeys: ['clean', 'issues', 'needsBossReply'],
      onDone: [
        {
          index: 0,
          target: 'judgeFindings',
          guarded: true,
        },
        {
          index: 1,
          target: 'reviewClean',
          guarded: true,
        },
        {
          index: 2,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 3,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
    {
      state: 'judgeFindings',
      actor: 'player',
      sourceItem: 'WORKFLOW-4',
      player: '',
      role: '编码者',
      resultKeys: ['accept', 'needsBossReply', 'reject'],
      onDone: [
        {
          index: 0,
          target: 'reviseByConclusion',
          guarded: true,
        },
        {
          index: 1,
          target: 'debateJudgment',
          guarded: true,
        },
        {
          index: 2,
          target: 'reviseByConclusion',
          guarded: true,
        },
        {
          index: 3,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 4,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
    {
      state: 'debateJudgment',
      actor: 'player',
      sourceItem: 'WORKFLOW-5',
      player: '',
      role: '评审者',
      resultKeys: ['agreed', 'dispute', 'needsBossReply'],
      onDone: [
        {
          index: 0,
          target: 'rejudgeRebuttal',
          guarded: true,
        },
        {
          index: 1,
          target: 'reviseByConclusion',
          guarded: true,
        },
        {
          index: 2,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 3,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
    {
      state: 'rejudgeRebuttal',
      actor: 'player',
      sourceItem: 'WORKFLOW-6',
      player: '',
      role: '编码者',
      resultKeys: ['accept', 'needsBossReply', 'reject'],
      onDone: [
        {
          index: 0,
          target: 'reviseByConclusion',
          guarded: true,
        },
        {
          index: 1,
          target: 'debateJudgment',
          guarded: true,
        },
        {
          index: 2,
          target: 'reviseByConclusion',
          guarded: true,
        },
        {
          index: 3,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 4,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
    {
      state: 'reviseByConclusion',
      actor: 'player',
      sourceItem: 'WORKFLOW-7',
      player: '',
      role: '编码者',
      resultKeys: ['done', 'needsBossReply'],
      onDone: [
        {
          index: 0,
          target: 'reviewCommit',
          guarded: true,
        },
        {
          index: 1,
          target: 'cycleLimitReached',
          guarded: true,
        },
        {
          index: 2,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 3,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
  ],
  quiescent: [
    {
      state: 'ready',
      final: false,
      on: {
        BOSS_TASK: [
          {
            index: 0,
            target: 'ensureRepository',
            guarded: true,
          },
        ],
      },
    },
    {
      state: 'ensureRepository',
      final: false,
      on: {},
    },
    {
      state: 'awaitBossReply',
      final: false,
      on: {
        BOSS_REPLY: [
          {
            index: 0,
            target: 'implementChange',
            guarded: true,
          },
          {
            index: 1,
            target: 'reviewCommit',
            guarded: true,
          },
          {
            index: 2,
            target: 'judgeFindings',
            guarded: true,
          },
          {
            index: 3,
            target: 'debateJudgment',
            guarded: true,
          },
          {
            index: 4,
            target: 'rejudgeRebuttal',
            guarded: true,
          },
          {
            index: 5,
            target: 'reviseByConclusion',
            guarded: true,
          },
          {
            index: 6,
            target: 'failed',
            guarded: false,
          },
        ],
      },
    },
    {
      state: 'failed',
      final: false,
      on: {
        BOSS_TASK: [
          {
            index: 0,
            target: 'ensureRepository',
            guarded: true,
          },
        ],
      },
    },
    {
      state: 'reviewClean',
      final: true,
      on: {},
    },
    {
      state: 'cycleLimitReached',
      final: true,
      on: {},
    },
  ],
  rootOn: {
    BOSS_INTERRUPT: [
      {
        index: 0,
        target: 'implementChange',
        guarded: true,
      },
      {
        index: 1,
        target: 'reviewCommit',
        guarded: true,
      },
      {
        index: 2,
        target: 'judgeFindings',
        guarded: true,
      },
      {
        index: 3,
        target: 'debateJudgment',
        guarded: true,
      },
      {
        index: 4,
        target: 'rejudgeRebuttal',
        guarded: true,
      },
      {
        index: 5,
        target: 'reviseByConclusion',
        guarded: true,
      },
    ],
  },
  interruptTargets: [
    'implementChange',
    'reviewCommit',
    'judgeFindings',
    'debateJudgment',
    'rejudgeRebuttal',
    'reviseByConclusion',
  ],
};

describe('workflow.zh: FSM introspection', () => {
  it('matches the machine topology pinned at build time', () => {
    expect(pinIntrospection(findMachineConfig(fsm))).toEqual(PINNED);
  });
});
