// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): FSM introspection pins.
// The PINNED topology was derived from the artifact at build time; any
// unintended structural change to the machine fails this test.
import { describe, expect, it } from 'vitest';

import { findMachineConfig, pinIntrospection } from './.slc-verify/verify.js';
import * as fsm from './workflow.zh.fsm.js';

const PINNED = {
  initial: 'ready',
  captain: [
    {
      state: 'implement',
      actor: 'player',
      sourceItem: 'CODE-2',
      player: '编码者',
      resultKeys: ['done', 'needsBossReply'],
      onDone: [
        {
          index: 0,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 1,
          target: 'review',
          guarded: true,
        },
        {
          index: 2,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
    {
      state: 'review',
      actor: 'player',
      sourceItem: 'CODE-3',
      player: '审查者',
      resultKeys: ['clean', 'issues', 'needsBossReply'],
      onDone: [
        {
          index: 0,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 1,
          target: 'adjudicate',
          guarded: true,
        },
        {
          index: 2,
          target: 'done',
          guarded: true,
        },
        {
          index: 3,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
    {
      state: 'adjudicate',
      actor: 'player',
      sourceItem: 'CODE-4',
      player: '编码者',
      resultKeys: ['agreed', 'dispute', 'needsBossReply'],
      onDone: [
        {
          index: 0,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 1,
          target: 'applyConclusion',
          guarded: true,
        },
        {
          index: 2,
          target: 'rebut',
          guarded: true,
        },
        {
          index: 3,
          target: 'failed',
          guarded: true,
        },
        {
          index: 4,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
    {
      state: 'rebut',
      actor: 'player',
      sourceItem: 'CODE-5',
      player: '审查者',
      resultKeys: ['needsBossReply', 'responded'],
      onDone: [
        {
          index: 0,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 1,
          target: 'adjudicate',
          guarded: true,
        },
        {
          index: 2,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
    {
      state: 'applyConclusion',
      actor: 'player',
      sourceItem: 'CODE-6',
      player: '编码者',
      resultKeys: ['done', 'needsBossReply'],
      onDone: [
        {
          index: 0,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 1,
          target: 'review',
          guarded: true,
        },
        {
          index: 2,
          target: 'done',
          guarded: true,
        },
        {
          index: 3,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
  ],
  quiescent: [
    {
      state: 'ready',
      final: false,
      on: {
        START: [
          {
            index: 0,
            target: 'setup',
            guarded: false,
          },
        ],
      },
    },
    {
      state: 'setup',
      final: false,
      on: {},
    },
    {
      state: 'awaitBossReply',
      final: false,
      on: {
        BOSS_REPLY: [
          {
            index: 0,
            target: 'implement',
            guarded: true,
          },
          {
            index: 1,
            target: 'review',
            guarded: true,
          },
          {
            index: 2,
            target: 'adjudicate',
            guarded: true,
          },
          {
            index: 3,
            target: 'rebut',
            guarded: true,
          },
          {
            index: 4,
            target: 'applyConclusion',
            guarded: true,
          },
          {
            index: 5,
            target: 'failed',
            guarded: false,
          },
        ],
      },
    },
    {
      state: 'failed',
      final: false,
      on: {
        START: [
          {
            index: 0,
            target: 'setup',
            guarded: false,
          },
        ],
      },
    },
    {
      state: 'done',
      final: true,
      on: {},
    },
  ],
  rootOn: {},
  interruptTargets: [],
};

describe('workflow.zh: FSM introspection', () => {
  it('matches the machine topology pinned at build time', () => {
    expect(pinIntrospection(findMachineConfig(fsm))).toEqual(PINNED);
  });
});
