// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): prompt contract.
// The pinned rows were derived from the artifacts at build time; wiring,
// placeholder, or composition drift fails this test.
import { describe, expect, it } from 'vitest';

import {
  capturePromptContract,
  checkPromptComposition,
  deriveSubstitutions,
  findMachineConfig,
} from './.slc-verify/verify.js';
import * as fsm from './workflow.zh.fsm.js';
import * as playbook from './workflow.zh.playbook.js';

const CONTRACT = [
  {
    state: 'implementChange',
    sourceItem: 'WORKFLOW-2',
    player: '',
    role: '编码者',
    reads: ['bossIntent', 'pendingBossQuestion'],
    wires: {
      bossIntent: ['bossIntent'],
    },
    placeholders: [],
  },
  {
    state: 'reviewCommit',
    sourceItem: 'WORKFLOW-3',
    player: '',
    role: '评审者',
    reads: ['pendingBossQuestion'],
    wires: {},
    placeholders: [],
  },
  {
    state: 'judgeFindings',
    sourceItem: 'WORKFLOW-4',
    player: '',
    role: '编码者',
    reads: ['pendingBossQuestion', 'reviewFindings'],
    wires: {
      reviewFindings: ['reviewFindings'],
    },
    placeholders: ['<reviewFindings>'],
  },
  {
    state: 'debateJudgment',
    sourceItem: 'WORKFLOW-5',
    player: '',
    role: '评审者',
    reads: ['coderJudgment', 'pendingBossQuestion'],
    wires: {
      coderJudgment: ['coderJudgment'],
    },
    placeholders: ['<coderJudgment>'],
  },
  {
    state: 'rejudgeRebuttal',
    sourceItem: 'WORKFLOW-6',
    player: '',
    role: '编码者',
    reads: ['pendingBossQuestion', 'reviewerRebuttal'],
    wires: {
      reviewerRebuttal: ['reviewerRebuttal'],
    },
    placeholders: ['<reviewerRebuttal>'],
  },
  {
    state: 'reviseByConclusion',
    sourceItem: 'WORKFLOW-7',
    player: '',
    role: '编码者',
    reads: ['pendingBossQuestion'],
    wires: {},
    placeholders: [],
  },
];
const SCHEMA_FINDINGS = [];

describe('workflow.zh: prompt contract', () => {
  it('uses consistent artifact-schema evidence', () => {
    expect(SCHEMA_FINDINGS).toEqual([]);
  });

  it('matches the prompt contract pinned at build time', () => {
    expect(capturePromptContract(findMachineConfig(fsm))).toEqual(CONTRACT);
  });

  const PLAYER_SUBSTITUTED = {
    implementChange: [],
    reviewCommit: [],
    judgeFindings: ['<reviewFindings>'],
    debateJudgment: ['<coderJudgment>'],
    rejudgeRebuttal: ['<reviewerRebuttal>'],
    reviseByConclusion: [],
  };

  const composePlayer = (
    playbook as unknown as {
      _internal: { composePlayerPrompt: (input: unknown) => string };
    }
  )._internal.composePlayerPrompt;

  it('composes player prompts per the link contract', () => {
    expect(
      checkPromptComposition({
        config: findMachineConfig(fsm),
        compose: composePlayer,
        actor: 'player',
        artifactSchema: 3,
      }),
    ).toEqual([]);
  });

  it('substitutes the player placeholders pinned at build time', () => {
    expect(
      deriveSubstitutions(findMachineConfig(fsm), composePlayer, 'player'),
    ).toEqual(PLAYER_SUBSTITUTED);
  });
});
