// Linked playbook runtime — generated by slc link (slc/link.md).
//
// Linker inputs (§Linker inputs):
//   FSM artifact:          ./workflow.zh.fsm.ts  (gears2fsm output for
//                          workflow.zh.gears.md, WORKFLOW-1 .. WORKFLOW-7)
//   Adjudication strategy: LLM-judge per state (default; every delegated-player
//                          state, no marker-parse override)
//   Boss-event mapping:    deterministic textual entry event `BOSS_TASK`,
//                          free-text judge classification otherwise (default)
//   Link options:          (none)
//
// Output profile: thin shared-factory module (§Output). The FSM declares no
// `type: 'parallel'` state, so every interpreter concern — actor wiring,
// boundary tracing, Boss-event mapping, adjudication, script execution,
// nested-playbook bridging, session lifecycle, abort handling, and the optional
// parked-session snapshot, adoption, and control surfaces — ships once in
// `createXStatePlaybookRuntime` instead of being regenerated here. This module
// contributes only what the factory cannot read from the FSM's own data.
//
// The FSM is imported with a `.ts` runtime specifier: this bundle is
// source-only (no JavaScript sibling is built or shipped beside it) and its
// host loads TypeScript directly. Only erasable TypeScript syntax is used, so
// a host running under type stripping loads this file as written.

import {
  createXStatePlaybookRuntime,
  defaultComposePlayerPrompt,
} from '@sublang/playbook/xstate-runtime';
import type {
  XStateOutcomeAuthoritySpec,
  XStatePlaybookRuntimeConstruction,
  XStatePlaybookRuntimeFactory,
  XStatePlaybookRuntimeSpecV3,
  XStateRepositoryCapability,
  XStateRoleStateStatus,
} from '@sublang/playbook/xstate-runtime';
import type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookEffectLedgerCapability,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlayerCallOptions,
  PlayerResult,
  PlayerSessionStore,
} from '@sublang/playbook/runtime';
import type { RoleId } from './workflow.zh.fsm.ts';
import { workflowMachine } from './workflow.zh.fsm.ts';

// One shared contract definition: consumers import these names from here
// rather than redefining them (§Output). `RoleId` travels with them so a host
// can build this artifact's authority declaration without reaching into the
// object artifact.
export type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookEffectLedgerCapability,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlayerCallOptions,
  PlayerResult,
  PlayerSessionStore,
  RoleId,
};

const LABEL = 'workflow.zh';

/* -- Runtime options ------------------------------------------------------ */

/**
 * Per-run options for this playbook, derived from every required FSM input
 * field that is neither supplied by `PlaybookSession` nor owned by the linker.
 *
 * `WorkflowInput` declares exactly one member, the optional `inputTask`, and
 * that member is linker-owned: the deterministic `BOSS_TASK` entry event
 * carries the exact Boss turn text into it (§Boss-event mapping), so it is not
 * a caller option. The only option left is the working directory of the
 * WORKFLOW-1 `script` state (§Script execution); omitted, the shared script
 * actor uses the process working directory.
 *
 * Concrete player binding and prompt identity are host policy and deliberately
 * absent here, as is any live host seam — those enter only through
 * `hostCapabilities` in the schema-3 construction input.
 */
export interface PlaybookRuntimeOptions {
  /** Working directory for the `script` actor. Default: the process cwd. */
  readonly cwd?: string;
}

const DECLARED_OPTION_KEYS: ReadonlySet<string> = new Set(['cwd']);

/**
 * Validate and JSON-snapshot the caller's options before any actor exists, so
 * the factory binds an immutable options record and later caller mutation
 * cannot reach a prompt or a machine decision. Undeclared keys, accessors, and
 * non-conforming values reject construction rather than being repaired.
 */
const snapshotOptions = (value: unknown): PlaybookRuntimeOptions => {
  if (value === undefined || value === null) return Object.freeze({});
  if (typeof value !== 'object' || Array.isArray(value)) {
    throw new TypeError(`${LABEL} options must be a plain object`);
  }
  const source = value as Record<string, unknown>;
  for (const key of Reflect.ownKeys(source)) {
    if (typeof key !== 'string' || !DECLARED_OPTION_KEYS.has(key)) {
      throw new TypeError(`${LABEL} options declare no ${String(key)} member`);
    }
    const descriptor = Object.getOwnPropertyDescriptor(source, key);
    if (descriptor === undefined || !('value' in descriptor)) {
      throw new TypeError(`${LABEL} options.${key} must be a data property`);
    }
  }
  const cwd = source.cwd;
  if (cwd === undefined) return Object.freeze({});
  if (typeof cwd !== 'string' || cwd.trim().length === 0) {
    throw new TypeError(`${LABEL} options.cwd must be a non-empty string`);
  }
  return Object.freeze({ cwd });
};

/* -- Host capabilities ---------------------------------------------------- */

/**
 * This artifact's live schema-3 authority: its id and schema, its detached role
 * and cohort declarations, the current configured working directory, the
 * logical session and lease-owner identities, and the canonical worktree.
 *
 * `cohorts` is empty because the FSM declares no parallel region
 * (`concurrentRoleSets` is `[]`), so no physical cohort ever spans two roles.
 */
export interface WorkflowArtifactAuthority {
  readonly artifactId: string;
  readonly artifactSchema: 3;
  readonly roles: readonly RoleId[];
  readonly cohorts: readonly (readonly RoleId[])[];
  readonly cwd: string;
  readonly sessionId: string;
  readonly leaseOwnerId: string;
  readonly canonicalWorktree: {
    readonly worktree: string;
    readonly gitDir: string;
  };
}

/**
 * Exactly `authority`, `repository`, and `effectLedger` (§PlaybookRuntime
 * contract). This object, its callbacks, and its live handles are host seams:
 * they enter neither `PlaybookPorts`, machine input or context, runtime
 * snapshots, retained generations, nor continuation identity.
 */
export interface HostCapabilities {
  readonly authority: WorkflowArtifactAuthority;
  readonly repository: XStateRepositoryCapability;
  readonly effectLedger: PlaybookEffectLedgerCapability;
}

/* -- FSM-derived spec metadata -------------------------------------------- */

/**
 * Every FSM state that invokes the typed `player` actor. Each `role` is the
 * state's source-derived `meta.playbook.role` and each `label` is that state's
 * exact FSM description; the factory rejects any divergence from the machine.
 */
const ROLE_STATES: Readonly<Record<string, XStateRoleStateStatus>> = {
  implementChange: {
    role: '编码者',
    label:
      '当 Git 仓库准备就绪时，由 `编码者` 按 Boss 输入的任务要求修改代码并提交 Git。',
  },
  reviewCommit: {
    role: '审查者',
    label:
      '如果已进行的循环次数少于 2 次，当 `编码者` 完成一次提交时，由 `审查者` review 该 commit 并提出合理问题。',
  },
  judgeFindings: {
    role: '编码者',
    label:
      '当 `审查者` 把提出的问题交回 `编码者` 做判断时，由 `编码者` 接受或拒绝并讲清楚原因。',
  },
  debateJudgment: {
    role: '审查者',
    label:
      '如果 `编码者` 在本次循环中的判断次数少于 3 次，当其拒绝问题时，由 `审查者` 判断是否同意并与其争论。',
  },
  rejudgeRebuttal: {
    role: '编码者',
    label:
      '当 `审查者` 继续与 `编码者` 争论时，由 `编码者` 再次接受或拒绝并讲清楚原因。',
  },
  reviseByConclusion: {
    role: '编码者',
    label:
      '当双方达成一致，或 `编码者` 已做出本次循环中总计第 3 次判断而不再争论时，由 `编码者` 按结论修改代码并再次提交。',
  },
};

/**
 * The payload fields the FSM's result maps annotate exactly
 * `` `<field>: <verbatim final text>` ``: the hidden judge selects the guard
 * and the player's canonical non-empty final text fills the field, so no
 * judge-authored paraphrase can replace prose the player actually wrote.
 *
 * Each name is annotated consistently everywhere it appears — `coderJudgment`
 * in both `judgeFindings` outcomes and both `rejudgeRebuttal` outcomes,
 * `reviewFindings` in `reviewCommit.issues`, `reviewerRebuttal` in
 * `debateJudgment.dispute` — so no property carries two ownership policies.
 * Under artifact schema 3 the same annotation makes each field
 * presentation-owned in `OUTCOME_AUTHORITY` below.
 */
const VERBATIM_PAYLOAD_FIELDS: ReadonlySet<string> = new Set([
  'reviewFindings',
  'coderJudgment',
  'reviewerRebuttal',
]);

/**
 * Schema-3 authority and repository contract, one entry per delegated-player
 * state, naming exactly that state's declared `invoke.input.result` outcomes
 * and exactly the payload fields each outcome's result description requires.
 *
 * WORKFLOW-2 (`implementChange`) and WORKFLOW-7 (`reviseByConclusion`) are the
 * two behaviors the GEARS source has commit to Git, so their completing `done`
 * outcome declares `one-descendant-commit` and their mid-task Boss question may
 * defer that commit. Every other behavior reviews, judges, or argues and leaves
 * the repository `unchanged`, so its Boss question is `unchanged` too. No
 * outcome names `latestCommit`, so no field is effect-owned.
 */
const OUTCOME_AUTHORITY: XStateOutcomeAuthoritySpec = {
  governedPlayerStates: {
    implementChange: {
      done: { fields: {}, repositoryDisposition: 'one-descendant-commit' },
      needsBossReply: {
        fields: { question: 'presentation' },
        repositoryDisposition: 'deferred',
      },
    },
    reviewCommit: {
      issues: {
        fields: { reviewFindings: 'presentation' },
        repositoryDisposition: 'unchanged',
      },
      clean: { fields: {}, repositoryDisposition: 'unchanged' },
      needsBossReply: {
        fields: { question: 'presentation' },
        repositoryDisposition: 'unchanged',
      },
    },
    judgeFindings: {
      accept: {
        fields: { coderJudgment: 'presentation' },
        repositoryDisposition: 'unchanged',
      },
      reject: {
        fields: { coderJudgment: 'presentation' },
        repositoryDisposition: 'unchanged',
      },
      needsBossReply: {
        fields: { question: 'presentation' },
        repositoryDisposition: 'unchanged',
      },
    },
    debateJudgment: {
      dispute: {
        fields: { reviewerRebuttal: 'presentation' },
        repositoryDisposition: 'unchanged',
      },
      agreed: { fields: {}, repositoryDisposition: 'unchanged' },
      needsBossReply: {
        fields: { question: 'presentation' },
        repositoryDisposition: 'unchanged',
      },
    },
    rejudgeRebuttal: {
      accept: {
        fields: { coderJudgment: 'presentation' },
        repositoryDisposition: 'unchanged',
      },
      reject: {
        fields: { coderJudgment: 'presentation' },
        repositoryDisposition: 'unchanged',
      },
      needsBossReply: {
        fields: { question: 'presentation' },
        repositoryDisposition: 'unchanged',
      },
    },
    reviseByConclusion: {
      done: { fields: {}, repositoryDisposition: 'one-descendant-commit' },
      needsBossReply: {
        fields: { question: 'presentation' },
        repositoryDisposition: 'deferred',
      },
    },
  },
};

/**
 * Root `type: 'final'` states whose terminal outcome leaves the procedure
 * unfinished. `reviewClean` is the finished outcome — review found nothing.
 * `cycleLimitReached` stops at the source's limit of 2 review cycles with its
 * last commit never confirmed clean, which the FSM's own description states.
 */
const UNFINISHED_FINAL_STATE_IDS: ReadonlySet<string> = new Set([
  'cycleLimitReached',
]);

/* -- Spec ----------------------------------------------------------------- */

const spec: XStatePlaybookRuntimeSpecV3<PlaybookRuntimeOptions> = {
  label: LABEL,
  // Stamped at link time from the installed engine's self-report, which lists
  // schema 3 in SUPPORTED_ARTIFACT_SCHEMAS. The values are literals rather than
  // engine imports on purpose: they name the format of *this* module, so the
  // factory's check against the engine that actually loads it can catch skew.
  compat: { artifactSchema: 3, runtimeAbi: 1 },
  snapshotOptions,
  // `WorkflowInput`'s only member, `inputTask`, is carried by the entry event
  // below, and `cwd` is a script-actor option that must not reach the machine.
  machineInput: () => ({}),
  // `BOSS_TASK` is the FSM's only ordinary textual entry event: `ready`,
  // `failed`, and a reconstructed terminal each accept exactly it (the root
  // `BOSS_INTERRUPT` is an explicit-state-jump event, not a textual entry), so
  // a Boss turn enters deterministically carrying the exact original text and
  // spends no classifier judge call (§Boss-event mapping). `applyBossTask`
  // copies that text into the context member named below, so the control
  // surface's failure-state retry (DR-034) sources its payload from the
  // persisted machine snapshot and survives `restore`. `BOSS_INTERRUPT` with
  // its closed target set and `BOSS_REPLY` are derived by the factory from the
  // machine itself, and the factory supplies this entry contract too — hence no
  // `bossEvents` entry, and no `placeholderFields` entry either, since every
  // authored placeholder (`<inputTask>`, `<reviewFindings>`, `<coderJudgment>`,
  // `<reviewerRebuttal>`) already matches its typed `PlayerInput` field name.
  entryEvent: {
    type: 'BOSS_TASK',
    textField: 'inputTask',
    contextField: 'inputTask',
  },
  // The payload fields the FSM's `WorkflowEvent` union declares.
  transitionEventFields: ['inputTask', 'targetId', 'answer', 'questionId'],
  roleStates: ROLE_STATES,
  outcomeAuthority: OUTCOME_AUTHORITY,
  verbatimPayloadFields: VERBATIM_PAYLOAD_FIELDS,
  unfinishedFinalStateIds: UNFINISHED_FINAL_STATE_IDS,
  // The authored control-view projection: the Boss-authored task under way plus
  // the two progress counters the source's limits are stated in. Review
  // findings, judgments, and rebuttals are player-authored text and stay
  // private; `pendingBossQuestion` and `lastError` are surfaced first-class by
  // the view and must not be named here.
  controlContextFields: ['inputTask', 'loopCount', 'judgmentCount'],
};

const createPlaybookRuntime: XStatePlaybookRuntimeFactory<
  XStatePlaybookRuntimeConstruction<PlaybookRuntimeOptions, HostCapabilities>,
  3
> = createXStatePlaybookRuntime<PlaybookRuntimeOptions, HostCapabilities>(
  workflowMachine,
  spec,
);

export default createPlaybookRuntime;

/**
 * Not a public API — the leading underscore says so, and nothing here is
 * semver-stable. It exposes the pure composers compilation-correctness tests
 * exercise without a host. This playbook's states call delegated players only
 * and make no direct-Captain call, so it exposes the player composer alone.
 */
export const _internal = {
  composePlayerPrompt: defaultComposePlayerPrompt,
};
