// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by slc/link.md (FSM-to-Runtime linker).
// Source FSM:    ./text2gears.fsm.ts
// Role metadata: none — TEXT2GEARS-1 is direct Captain work, so this module
//                declares no local role and no delegated-player state
// Boss event:    deterministic BOSS_INTENT entry; the exact Boss text becomes
//                bossIntent; the pending Captain question retains BOSS_REPLY
// Adjudication:  LLM judge for the one direct-Captain state; `question` is
//                runtime-injected presentation from the visible call, never
//                authored by the hidden judge
// Captain tools: unrestricted — a transformation-performing Captain writes
//                the named Target through the host Captain's own tools, so
//                no `allowedTools` restriction is passed
// Compat:        artifact schema 3 / runtime ABI 1

import {
  createXStatePlaybookRuntime,
  defaultComposeCaptainPrompt,
  snapshotJsonValue,
  type XStatePlaybookRuntimeConstruction,
  type XStatePlaybookRuntimeFactory,
  type XStatePlaybookRuntimeSpecV3,
} from '@sublang/playbook/xstate-runtime';
import { text2gearsMachine, type Text2GearsInput } from './text2gears.fsm.ts';
import type { PlaybookHostConstructionCapabilities } from '@sublang/playbook/playbook-captain';
import type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookControlReceipt,
  PlaybookControlView,
  PlaybookPendingCall,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlayerResult,
  PlayerSessionStore,
} from '@sublang/playbook/runtime';

export type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookControlReceipt,
  PlaybookControlView,
  PlaybookPendingCall,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlayerResult,
  PlayerSessionStore,
};

/**
 * Every required FSM input field that no `PlaybookSession` member or other
 * linker-owned source supplies. `definition` is the host-owned configuration
 * TEXT2GEARS-1 relays: the exact bytes of the definition file the request
 * names, immutable for the session.
 */
export type Text2GearsPlaybookOptions = Text2GearsInput;

export type Text2GearsPlaybookHostCapabilities =
  PlaybookHostConstructionCapabilities &
    XStatePlaybookRuntimeConstruction<
      Text2GearsPlaybookOptions,
      object
    >['hostCapabilities'];

const OPTION_KEYS: ReadonlySet<string> = new Set(['definition']);

/**
 * No result description annotates a delegated player's whole final response:
 * the one acting state is direct Captain work, whose `question` is injected
 * by the runtime from the visible call rather than carried as a verbatim
 * payload field.
 */
const VERBATIM_PAYLOAD_FIELDS: ReadonlySet<string> = new Set();

/**
 * `rejected` is a root final state whose authored terminal outcome leaves the
 * Target unwritten, so the procedure it names is unfinished; `compiled` is
 * the finished outcome and is therefore not declared.
 */
const UNFINISHED_FINAL_STATE_IDS: ReadonlySet<string> = new Set(['rejected']);

/**
 * The working leaf a Boss reply resumes. Declared rather than derived: the
 * FSM's `awaitBossReply` BOSS_REPLY list ends in a malformed-reply arm to
 * `failed`, which is a recovery target and not a resume destination.
 */
const RESUMABLE_STATE_IDS: ReadonlySet<string> = new Set(['transform']);

function snapshotText2GearsOptions(value: unknown): Text2GearsPlaybookOptions {
  const captured = snapshotJsonValue(value, 'TEXT2GEARS runtime options');
  if (
    captured === null ||
    typeof captured !== 'object' ||
    Array.isArray(captured)
  ) {
    throw new TypeError('TEXT2GEARS runtime options must be an object');
  }
  const record = captured as Readonly<Record<string, JsonValue>>;
  for (const [key, option] of Object.entries(record)) {
    if (!OPTION_KEYS.has(key)) {
      throw new TypeError(`TEXT2GEARS runtime options.${key} is not declared`);
    }
    if (typeof option !== 'string') {
      throw new TypeError(`TEXT2GEARS runtime options.${key} must be a string`);
    }
  }
  for (const key of OPTION_KEYS) {
    if (!Object.prototype.hasOwnProperty.call(record, key)) {
      throw new TypeError(`TEXT2GEARS runtime options.${key} is required`);
    }
  }
  return captured as unknown as Text2GearsPlaybookOptions;
}

export const _internal = {
  // The spec overrides no composer, so the module exposes the shared default
  // its own direct-Captain state runs under.
  composeCaptainPrompt: defaultComposeCaptainPrompt,
  VERBATIM_PAYLOAD_FIELDS,
  UNFINISHED_FINAL_STATE_IDS,
  RESUMABLE_STATE_IDS,
};

const runtimeSpec = {
  label: 'TEXT2GEARS',
  // DR-022 / slc/link.md: the declaration carries the value current at link
  // time — a literal, never the loading engine's RUNTIME_ABI self-report,
  // which would follow whatever engine loads the module and make the
  // factory's skew check compare that engine with itself.
  compat: { artifactSchema: 3, runtimeAbi: 1 },
  snapshotOptions: snapshotText2GearsOptions,
  entryEvent: {
    type: 'BOSS_INTENT',
    textField: 'bossIntent',
    // `startFreshRequest` copies the entry text here, so the failure-state
    // retry reads it back from the persisted machine snapshot and survives a
    // continued session (DR-034).
    contextField: 'bossIntent',
  },
  // TEXT2GEARS delegates to no role, so the status profile names no player
  // state and schema 3 makes that absence explicit rather than inferred.
  roleStates: {},
  outcomeAuthority: { governedPlayerStates: {} },
  verbatimPayloadFields: VERBATIM_PAYLOAD_FIELDS,
  resumableStateIds: RESUMABLE_STATE_IDS,
  controlContextFields: [],
  unfinishedFinalStateIds: UNFINISHED_FINAL_STATE_IDS,
  transitionEventFields: ['bossIntent', 'targetId', 'answer', 'questionId'],
} satisfies XStatePlaybookRuntimeSpecV3<Text2GearsPlaybookOptions>;

const createPlaybookRuntime: XStatePlaybookRuntimeFactory<
  XStatePlaybookRuntimeConstruction<
    Text2GearsPlaybookOptions,
    Text2GearsPlaybookHostCapabilities
  >,
  3
> = createXStatePlaybookRuntime<
  Text2GearsPlaybookOptions,
  Text2GearsPlaybookHostCapabilities
>(text2gearsMachine, runtimeSpec);

export default createPlaybookRuntime;
