// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): prompt contract for text2gears.
// The pinned rows were derived from the artifacts at build time; wiring,
// placeholder, or composition drift fails this test.
import { describe, expect, it } from 'vitest';

import {
  capturePromptContract,
  checkPromptComposition,
  deriveSubstitutions,
  findMachineConfig,
} from '@sublang/slc/verify';
import * as fsm from './text2gears.fsm.ts';
import * as playbook from './text2gears.playbook.ts';

const CONTRACT = [
  {
    state: 'transformTextToGears',
    sourceItem: 'TEXT2GEARS-10',
    player: 'Captain',
    reads: ['bossReply', 'pendingBossQuestion', 'source', 'target'],
    wires: {
      source: ['source'],
      target: ['target'],
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: ['<source>', '<target>', '<placeholder>'],
  },
];

describe('text2gears: prompt contract', () => {
  it('matches the prompt contract pinned at build time', () => {
    expect(capturePromptContract(findMachineConfig(fsm))).toEqual(CONTRACT);
  });

  const SUBSTITUTED = {
    transformTextToGears: [],
  };

  const compose = (
    playbook as unknown as {
      _internal: { composePlayerPrompt: (input: unknown) => string };
    }
  )._internal.composePlayerPrompt;

  it('composes player prompts per the link contract', () => {
    expect(
      checkPromptComposition({ config: findMachineConfig(fsm), compose }),
    ).toEqual([]);
  });

  it('substitutes the placeholders pinned at build time', () => {
    expect(deriveSubstitutions(findMachineConfig(fsm), compose)).toEqual(
      SUBSTITUTED,
    );
  });
});
