// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (IR-007 Task 8): GEARS↔FSM conformance.
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import {
  checkGearsFsmConformance,
  findMachineConfig,
} from './.slc-verify/verify.js';
import * as fsm from './text2gears.fsm.js';

describe('text2gears: GEARS↔FSM conformance', () => {
  it('maps every GEARS item to a state with its player and verbatim prompt', () => {
    const gears = readFileSync(
      fileURLToPath(new URL('./text2gears.gears.md', import.meta.url)),
      'utf8',
    );
    expect(checkGearsFsmConformance(gears, findMachineConfig(fsm))).toEqual([]);
  });
});
