// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): prompt contract.
// The pinned rows were derived from the artifacts at build time; wiring,
// placeholder, or composition drift fails this test.
import { describe, expect, it } from 'vitest';

import {
  capturePromptContract,
  checkPromptComposition,
  deriveSubstitutions,
  findMachineConfig,
} from './.slc-verify/verify.js';
import * as fsm from './text2gears.fsm.js';
import * as playbook from './text2gears.playbook.js';

const CONTRACT = [
  {
    state: 'compile',
    sourceItem: 'T2G-1',
    player: '',
    reads: ['bossReply', 'pendingBossQuestion'],
    wires: {
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: [
      '<ITEM-ID>',
      '<behavior>',
      '<Player>',
      '<placeholder>',
      '<stable-kebab-case-id>',
      '<playbook-id>',
      '<playbook-id-context>',
      '<placeholder\\>',
    ],
  },
];

describe('text2gears: prompt contract', () => {
  it('matches the prompt contract pinned at build time', () => {
    expect(capturePromptContract(findMachineConfig(fsm))).toEqual(CONTRACT);
  });

  const CAPTAIN_SUBSTITUTED = {
    compile: [],
  };

  const composeCaptain = (
    playbook as unknown as {
      _internal: { composeCaptainPrompt: (input: unknown) => string };
    }
  )._internal.composeCaptainPrompt;

  it('composes Captain prompts per the link contract', () => {
    expect(
      checkPromptComposition({
        config: findMachineConfig(fsm),
        compose: composeCaptain,
        actor: 'captain',
      }),
    ).toEqual([]);
  });

  it('substitutes the Captain placeholders pinned at build time', () => {
    expect(
      deriveSubstitutions(findMachineConfig(fsm), composeCaptain, 'captain'),
    ).toEqual(CAPTAIN_SUBSTITUTED);
  });
});
