// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// slc link artifact — PlaybookRuntime for the `text2gears` playbook.
// Generated by slc/link.md (FSM-to-Runtime linker); reproducible from these
// inputs:
//   FSM artifact:       ./text2gears.fsm.ts
//   Player binding:     none — the GEARS source declares only Boss and Captain,
//                       and the sole actor is the direct Captain, which bypasses
//                       player binding and is served by PlaybookPorts.callCaptain.
//   Adjudication:       LLM-judge per Captain state (factory default).
//   Boss-event mapping: `COMPILE` carries no textual payload field, so the
//                       shared classifier selects it at ready, a reconstructed
//                       terminal machine, or while parked (`failed`/
//                       `awaitBossReply`) instead of inventing an event member.
//                       The FSM reads CaptainInput from context, not the event.
//                       The classifier also maps parked-state Boss text among
//                       COMPILE, BOSS_REPLY, and BOSS_INTERRUPT.
//                       `BOSS_INTERRUPT` is derived from the FSM root;
//                       `BOSS_REPLY`/`NO_ACTION` are runtime-owned (default).
//   Abort strategy:     natural rejection — the Captain actor rejects on abort
//                       or control failure and the FSM routes it through
//                       compile.onError to the quiescent `failed` state (factory
//                       default).
//
// This is a thin module: the FSM-interpreter machinery (actor wiring, boundary
// tracing, Boss-event classification, Captain adjudication, Boss-reply
// suspension, session lifecycle, abort handling, snapshot/restore) is NOT
// regenerated here — it ships once as the shared
// `createXStatePlaybookRuntime(machine, spec)` factory. This module hands that
// factory the FSM plus a small per-playbook `spec`. It imports no `xstate`,
// `p-queue`, or `node:child_process`, holds no host types, and never talks to
// LLMs directly; it speaks only `PlaybookPorts`. It does not modify the FSM or
// re-derive Captain prompts, result keys, or guard semantics.

import text2gearsMachine from './text2gears.fsm.ts';

import {
  createXStatePlaybookRuntime,
  defaultComposeCaptainPrompt,
  defaultComposePlayerPrompt,
} from '@sublang/playbook/xstate-runtime';
import type { XStatePlaybookRuntimeSpec } from '@sublang/playbook/xstate-runtime';

import type { PlaybookRuntimeFactory } from '@sublang/playbook/runtime';

// Single shared contract: re-export the names consumers import rather than
// redefining them, so every linked playbook shares one contract definition
// (slc/link.md §Output).
export type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlayerCallOptions,
  PlayerResult,
} from '@sublang/playbook/runtime';

// Per-run knobs. The FSM's machine input (Text2gearsInput) is empty — the
// single T2G-1 prompt establishes no runtime-value placeholders, the source
// declares no players, and the machine makes no dynamic playbook call (so there
// is no `selfPlaybookId`) — and the FSM has no `script` state (so there is no
// `cwd`). No per-run options remain.
export type PlaybookRuntimeOptions = Record<string, never>;

/**
 * Validate and JSON-snapshot the caller's per-run options (slc/link.md
 * §Output). `text2gears` declares no options, so the only conforming value is
 * an empty object (or an omitted value); any own key is rejected so the factory
 * binds an immutable, exact options record.
 */
function snapshotOptions(value: unknown): PlaybookRuntimeOptions {
  if (value === undefined || value === null) return {};
  if (typeof value !== 'object' || Array.isArray(value)) {
    throw new TypeError(
      'text2gears runtime options must be an object when provided',
    );
  }
  const keys = Reflect.ownKeys(value as object);
  if (keys.length > 0) {
    throw new TypeError(
      `text2gears runtime accepts no options; received: ${keys
        .map((key) => String(key))
        .join(', ')}`,
    );
  }
  return {};
}

// Everything the factory cannot read from the FSM artifact's own data
// (slc/link.md §Output):
// - `bossEvents`: `COMPILE` carries no textual payload field, so it cannot be a
//   deterministic textual entry event under slc/link.md §Boss-event mapping.
//   Its type-only contract is erased under TypeScript, so the runtime needs it
//   here to offer `COMPILE` to the classifier at ready, a reconstructed
//   terminal machine, and parked states (`failed`, `awaitBossReply`).
// - `transitionEventFields`: the exact string payload fields the FSM's Boss
//   union declares (BOSS_INTERRUPT.targetId, BOSS_REPLY.answer/questionId),
//   copied into transition telemetry/trace descriptors.
// The runtime-owned `BOSS_REPLY`/`NO_ACTION` arms and the root-derived
// `BOSS_INTERRUPT` contract need no `bossEvents` entry. Options validation,
// actor provisioning, prompt composition, classification, adjudication,
// statuses, and resumable-state derivation are the factory's generic defaults,
// which implement the behavioral sections of the link spec.
const spec: XStatePlaybookRuntimeSpec<PlaybookRuntimeOptions> = {
  label: 'text2gears',
  snapshotOptions,
  bossEvents: [{ type: 'COMPILE' }],
  transitionEventFields: ['targetId', 'answer', 'questionId'],
};

/**
 * The per-playbook runtime factory: `(options) => PlaybookRuntime`. The shared
 * engine interprets the `text2gears` FSM under the slc/link.md contract.
 */
const createPlaybookRuntime: PlaybookRuntimeFactory<PlaybookRuntimeOptions> =
  createXStatePlaybookRuntime<PlaybookRuntimeOptions>(text2gearsMachine, spec);

export default createPlaybookRuntime;

/**
 * Pure helpers verification exercises without a host (slc/link.md §Output).
 * `text2gears` overrides neither composer, so both re-export the shared
 * defaults: continuation preamble + presence-based placeholder substitution.
 */
export const _internal = {
  composePlayerPrompt: defaultComposePlayerPrompt,
  composeCaptainPrompt: defaultComposeCaptainPrompt,
};
