// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by slc/link.md (FSM-to-Runtime linker).
// Source FSM:     ./workflow.fsm.ts
// Player binding: 编码者→编码者, 审查者→审查者
//                 (default binding: each player → its lowercased name;
//                 these non-English names are unchanged by lowercasing)
// Boss event:     free-text judge classification
// Adjudication:   LLM-judge per state
// Script actor:   ensureRepo (CODE-1) runs `sh -c` locally, no agent
// Contract:       PlayerResult / PlaybookPorts / PlaybookSession /
//                 PlaybookRuntime imported and re-exported from
//                 @sublang/playbook/runtime (slc/link.md §Output)

import PQueue from 'p-queue';
import { spawn, type ChildProcess } from 'node:child_process';
import { createActor, fromPromise } from 'xstate';
import type { InspectionEvent, SnapshotFrom } from 'xstate';
import {
  assertPlaybookRuntimeSnapshot,
  combineAbortSignals,
  detachPersistedMachineSnapshot,
  normalizeError,
  normalizePlaybookSnapshot,
  snapshotJsonValue,
  snapshotPlaybookSession,
  validatePlayerResult,
  waitForPlaybookQuiescence,
} from '@sublang/playbook/xstate-runtime';
import {
  workflowMachine,
  type PlayerInput,
  type PlayerOutput,
  type ScriptInput,
  type ScriptOutput,
  type WorkflowInput,
  type WorkflowEvent,
} from './workflow.fsm.ts';
import type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookPendingCall,
  PlaybookRunResult,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlaybookPorts,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlayerResult,
} from '@sublang/playbook/runtime';

// Public contract. The shared runtime module is the single source for the
// PlaybookPorts / PlaybookRuntime contract; this playbook re-exports the
// names its consumers import rather than redefining them (slc/link.md §Output).
export type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookPendingCall,
  PlaybookRunResult,
  PlayerResult,
  PlaybookPorts,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookRuntimeSnapshot,
};

// Per-run knobs. The FSM's machine input (WorkflowInput) is empty, so the only
// runtime option is the optional script working directory required by
// slc/link.md §Script execution because this FSM declares a `script` actor.
export interface WorkflowPlaybookOptions {
  cwd?: string;
}

function snapshotWorkflowPlaybookOptions(
  value: unknown,
): WorkflowPlaybookOptions {
  const captured = snapshotJsonValue(value ?? {}, 'workflow runtime options');
  if (
    captured === null ||
    typeof captured !== 'object' ||
    Array.isArray(captured)
  ) {
    throw new TypeError('workflow runtime options must be an object');
  }
  const record = captured as Readonly<Record<string, JsonValue>>;
  const allowed = new Set(['cwd']);
  for (const [key, option] of Object.entries(record)) {
    if (!allowed.has(key)) {
      throw new TypeError(`workflow runtime options.${key} is not declared`);
    }
    if (typeof option !== 'string') {
      throw new TypeError(`workflow runtime options.${key} must be a string`);
    }
  }
  return captured as unknown as WorkflowPlaybookOptions;
}

const BOSS_REPLY_ERRORS = {
  missingQuestion: "needsBossReply outcome missing 'question' field",
  unregisteredState: (stateId: string) =>
    `state ${stateId} declared needsBossReply but is not registered as resumable`,
} as const;

// Default player binding (slc/link.md §Player binding): each GEARS player maps
// to its lowercased name. Both names are non-English, so lowercasing is
// identity. There are no composite/alias players in this FSM.
const PLAYER_BINDING: Readonly<Record<string, string>> = {
  编码者: '编码者',
  审查者: '审查者',
};

// Player-invoking working leaves: player + source item, for trace identity and
// human status. Derived from the FSM's delegated states.
const PLAYER_STATE_METADATA: ReadonlyMap<
  string,
  { player: string; sourceItem: string }
> = new Map([
  ['implement', { player: '编码者', sourceItem: 'CODE-2' }],
  ['review', { player: '审查者', sourceItem: 'CODE-3' }],
  ['judge', { player: '编码者', sourceItem: 'CODE-4' }],
  ['debate', { player: '审查者', sourceItem: 'CODE-5' }],
  ['revise', { player: '编码者', sourceItem: 'CODE-6' }],
]);

// Every player-invoking state supports Boss-reply suspension, so all are
// registered resume targets of the FSM's awaitBossReply state.
const registeredResumableStateIds: ReadonlySet<string> = new Set(
  PLAYER_STATE_METADATA.keys(),
);

// Human-readable labels for the Captain-facing status line, taken from the
// FSM state descriptions.
const STATE_LABELS: Readonly<Record<string, string>> = {
  ensureRepo: '确保当前目录是一个Git仓库',
  implement: '编码者按任务要求修改代码并提交',
  review: '审查者对提交的commit进行review并提出问题',
  judge: '编码者对审查者的问题做出判断',
  debate: '审查者与编码者争论直至达成一致',
  revise: '编码者按结论修改代码并再次提交',
  failed: '工作流失败',
};

// The runtime emits no human status on entry to the idle hub or terminal
// state; the host's next Boss prompt is the implicit "turn over" signal.
const SUPPRESSED_ENTRY_STATES: ReadonlySet<string> = new Set(['ready', 'done']);

// Classifier-facing event contract (slc/link.md §Boss-event mapping): each
// recovered object carries exactly `type` plus these non-text routing keys.
// The runtime owns the textual `answer` field, so it is excluded here.
const CLASSIFIER_ROUTING_KEYS: Readonly<Record<string, ReadonlySet<string>>> = {
  START: new Set<string>(),
  NO_ACTION: new Set<string>(),
  BOSS_REPLY: new Set<string>(['questionId']),
};

// ---------------------------------------------------------------------------
// Error / value normalization helpers.
// ---------------------------------------------------------------------------

function normalizeErrorCompact(
  err: unknown,
): { name: string; message: string } | undefined {
  if (err === undefined || err === null) return undefined;
  const normalized = normalizeError(err);
  return { name: normalized.name, message: normalized.message };
}

function normalizeErrorFull(
  err: unknown,
): { name: string; message: string; stack?: string } | undefined {
  if (err === undefined || err === null) return undefined;
  return normalizeError(err);
}

function isAbortFailure(error: unknown, signal: AbortSignal): boolean {
  return (
    signal.aborted &&
    (error === signal.reason || normalizeError(error).name === 'AbortError')
  );
}

function normalizeEventForTelemetry(event: unknown): unknown {
  if (event === undefined) return undefined;
  return normalizeEventValue(event, 'FSM event', new Set());
}

function normalizeEventValue(
  value: unknown,
  path: string,
  ancestors: ReadonlySet<object>,
): JsonValue {
  if (Array.isArray(value)) return snapshotJsonValue(value, path);
  if (value === null || typeof value !== 'object') {
    return snapshotJsonValue(value, path);
  }
  if (ancestors.has(value)) {
    throw new TypeError(`${path} must not contain a JSON cycle`);
  }
  const prototype = Object.getPrototypeOf(value) as unknown;
  if (prototype !== Object.prototype && prototype !== null) {
    return snapshotJsonValue(value, path);
  }
  if (Object.getOwnPropertySymbols(value).length > 0) {
    return snapshotJsonValue(value, path);
  }
  const nextAncestors = new Set(ancestors).add(value);
  const normalized: Record<string, JsonValue> = {};
  for (const [key, descriptor] of Object.entries(
    Object.getOwnPropertyDescriptors(value),
  )) {
    if (!descriptor.enumerable) {
      throw new TypeError(`${path}.${key} must be an enumerable JSON property`);
    }
    if (!Object.prototype.hasOwnProperty.call(descriptor, 'value')) {
      throw new TypeError(`${path}.${key} must be a JSON data property`);
    }
    if (descriptor.value === undefined) continue;
    normalized[key] =
      key === 'error'
        ? snapshotJsonValue(normalizeError(descriptor.value), `${path}.error`)
        : normalizeEventValue(
            descriptor.value,
            `${path}.${key}`,
            nextAncestors,
          );
  }
  return snapshotJsonValue(normalized, path);
}

// ---------------------------------------------------------------------------
// Player prompt composition (slc/link.md §Player prompt composition).
// ---------------------------------------------------------------------------

// Single callback-based pass. Replacement values are inserted literally, so
// placeholder-looking text or `$&`/`$$` tokens inside a value are never
// re-interpreted (slc/link.md §Output).
function substitutePlaceholders(
  template: string,
  values: Readonly<Record<string, string>>,
): string {
  return template.replace(
    /<([A-Za-z_$][A-Za-z0-9_$]*)>/g,
    (match, name: string) =>
      Object.prototype.hasOwnProperty.call(values, name) ? values[name] : match,
  );
}

function composePlayerPrompt(input: PlayerInput): string {
  const blocks: string[] = [];
  if (
    input.pendingBossQuestion !== undefined &&
    input.bossReply !== undefined
  ) {
    blocks.push(
      'You previously paused this task to ask Boss a question; Boss has now replied. Continue the same task using the reply below.',
    );
    blocks.push(`Boss question:\n${input.pendingBossQuestion.question}`);
    blocks.push(`Boss reply:\n${input.bossReply}`);
  }

  const values: Record<string, string> = {};
  if (input.reviewComments !== undefined) {
    values.reviewComments = input.reviewComments;
  }
  if (input.coderResponse !== undefined) {
    values.coderResponse = input.coderResponse;
  }
  if (input.agreedConclusion !== undefined) {
    values.agreedConclusion = input.agreedConclusion;
  }
  blocks.push(substitutePlaceholders(input.prompt, values));

  return blocks.join('\n\n');
}

function resolvePlayerId(input: PlayerInput): string {
  const bound = PLAYER_BINDING[input.player];
  if (bound === undefined) {
    throw new Error(`resolvePlayerId: unknown player ${String(input.player)}`);
  }
  return bound;
}

// ---------------------------------------------------------------------------
// Adjudication (slc/link.md §Captain adjudication).
// ---------------------------------------------------------------------------

type JudgePurpose = 'boss-input-classification' | 'player-output-adjudication';

interface RuntimeBoundaryCalls {
  callPlayer(
    input: PlayerInput,
    playerId: string,
    prompt: string,
    signal: AbortSignal,
  ): Promise<PlayerResult>;
  callJudge(
    purpose: JudgePurpose,
    stateId: string | undefined,
    prompt: string,
    signal: AbortSignal,
  ): Promise<string>;
}

async function adjudicate(
  input: PlayerInput,
  finalText: string,
  ports: PlaybookPorts,
  signal: AbortSignal,
  boundary?: RuntimeBoundaryCalls,
): Promise<PlayerOutput> {
  const prompt = buildJudgePrompt(input, finalText);
  const raw = boundary
    ? await boundary.callJudge(
        'player-output-adjudication',
        input.stateId,
        prompt,
        signal,
      )
    : await ports.callJudge(prompt, signal);
  const parsed = parseJudgeJson(raw);
  if (!isPlainObject(parsed)) {
    throw new Error('adjudicate: judge response is not a JSON object');
  }
  const obj = parsed as Record<string, unknown>;
  const guard = obj.guard;
  if (typeof guard !== 'string') {
    throw new Error('adjudicate: judge response missing string "guard" field');
  }
  if (!Object.prototype.hasOwnProperty.call(input.result, guard)) {
    throw new Error(
      `adjudicate: unknown guard "${guard}" — declared guards: ${Object.keys(
        input.result,
      ).join(', ')}`,
    );
  }
  for (const field of extractRequiredFields(input.result[guard])) {
    if (typeof obj[field] !== 'string') {
      if (guard === 'needsBossReply' && field === 'question') {
        throw new Error(BOSS_REPLY_ERRORS.missingQuestion);
      }
      throw new Error(
        `adjudicate: judge response missing required field "${field}" for guard "${guard}"`,
      );
    }
  }
  return obj as PlayerOutput;
}

// Extract the output property names a guard's description requires. Limited to
// the description's "Output shall include" / "输出应包含" clause; a backticked
// token names the property before any inner colon (slc/link.md
// §Captain adjudication).
function extractRequiredFields(description: string): string[] {
  const clause = description.match(
    /(?:Output shall include|输出应包含)([\s\S]*)$/,
  );
  if (!clause) return [];
  const fields: string[] = [];
  const re = /`\s*([A-Za-z_$][A-Za-z0-9_$]*)\s*(?::[^`]*)?`/g;
  for (const m of clause[1].matchAll(re)) {
    fields.push(m[1]);
  }
  return fields;
}

function buildJudgePrompt(input: PlayerInput, finalText: string): string {
  const lines: string[] = [];
  lines.push(`The ${input.player} just produced this output:`);
  lines.push('');
  lines.push('```');
  lines.push(finalText);
  lines.push('```');
  lines.push('');
  lines.push(
    'Pick exactly one outcome by `guard` and return JSON ' +
      '`{ guard, …payloadFields }`. Required payload fields are named in ' +
      'the outcome description.',
  );
  lines.push('');
  for (const [key, description] of Object.entries(input.result)) {
    lines.push(`- \`${key}\` — ${description}`);
  }
  return lines.join('\n');
}

// Tolerant JSON recovery shared by the classifier and adjudicator
// (slc/link.md §Boss-event mapping / §Captain adjudication): try a strict
// parse, then scan every `{`/`[` in document order and return the first
// recoverable object, preferring a strict balanced span over a repaired one
// at each start.
function parseJudgeJson(raw: string): unknown {
  const fenced = stripCodeFence(raw.trim());
  try {
    return JSON.parse(fenced);
  } catch {
    // Fall through to lenient extraction + repair.
  }
  const starts: number[] = [];
  for (let i = 0; i < fenced.length; i++) {
    const ch = fenced[i];
    if (ch === '{' || ch === '[') starts.push(i);
  }
  let firstValue: { value: unknown } | undefined;
  for (const start of starts) {
    let parsedHere: { value: unknown } | undefined;
    for (const repair of [false, true]) {
      const candidate = extractJsonValue(fenced, start, repair);
      if (candidate === undefined) continue;
      try {
        parsedHere = { value: JSON.parse(candidate) };
      } catch {
        continue;
      }
      break;
    }
    if (parsedHere === undefined) continue;
    if (isPlainObject(parsedHere.value)) return parsedHere.value;
    if (firstValue === undefined) firstValue = parsedHere;
  }
  if (firstValue !== undefined) return firstValue.value;
  throw new Error('adjudicate: judge response is not valid JSON');
}

function isPlainObject(value: unknown): boolean {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function stripCodeFence(text: string): string {
  const fence = text.match(/^```(?:json)?\s*\n?([\s\S]*?)\n?```$/);
  return fence ? fence[1].trim() : text;
}

function extractJsonValue(
  text: string,
  start: number,
  repair: boolean,
): string | undefined {
  const stack: string[] = [];
  let out = '';
  let inString = false;
  let escaped = false;
  for (let i = start; i < text.length; i++) {
    const ch = text[i];
    if (inString) {
      out += ch;
      if (escaped) escaped = false;
      else if (ch === '\\') escaped = true;
      else if (ch === '"') inString = false;
      continue;
    }
    if (ch === '"') {
      inString = true;
      out += ch;
      continue;
    }
    if (ch === '{' || ch === '[') {
      stack.push(ch === '{' ? '}' : ']');
      out += ch;
      continue;
    }
    if (ch === '}' || ch === ']') {
      if (repair) out = dropTrailingComma(out);
      out += ch;
      stack.pop();
      if (stack.length === 0) return out;
      continue;
    }
    out += ch;
  }
  if (!repair) return undefined;
  if (inString) out += '"';
  out = dropTrailingComma(out);
  while (stack.length > 0) out += stack.pop();
  return out;
}

function dropTrailingComma(out: string): string {
  return out.replace(/,(\s*)$/, '$1');
}

// ---------------------------------------------------------------------------
// Boss-event classification (slc/link.md §Boss-event mapping).
// ---------------------------------------------------------------------------

interface PendingBossQuestionForStatus {
  questionId: string;
  resumeStateId: string;
  sourceItem: string;
  player: string;
  question: string;
}

function pendingBossQuestionFromContext(
  context: Record<string, unknown>,
): PendingBossQuestionForStatus | undefined {
  const pending = context.pendingBossQuestion;
  if (
    pending === undefined ||
    typeof pending !== 'object' ||
    pending === null
  ) {
    return undefined;
  }
  const candidate = pending as Partial<
    Record<keyof PendingBossQuestionForStatus, unknown>
  >;
  if (
    typeof candidate.resumeStateId !== 'string' ||
    typeof candidate.questionId !== 'string' ||
    typeof candidate.sourceItem !== 'string' ||
    typeof candidate.player !== 'string' ||
    typeof candidate.question !== 'string'
  ) {
    return undefined;
  }
  return {
    questionId: candidate.questionId,
    resumeStateId: candidate.resumeStateId,
    sourceItem: candidate.sourceItem,
    player: candidate.player,
    question: candidate.question,
  };
}

interface ClassifierState {
  value: unknown;
  context: Record<string, unknown>;
}

function classifierState(snapshotOrState: unknown): ClassifierState {
  if (
    snapshotOrState !== null &&
    typeof snapshotOrState === 'object' &&
    'value' in snapshotOrState
  ) {
    const candidate = snapshotOrState as { value?: unknown; context?: unknown };
    return {
      value: candidate.value,
      context:
        candidate.context !== null &&
        typeof candidate.context === 'object' &&
        !Array.isArray(candidate.context)
          ? (candidate.context as Record<string, unknown>)
          : {},
    };
  }
  return { value: snapshotOrState, context: {} };
}

function buildClassifierPrompt(text: string, state: ClassifierState): string {
  const currentState =
    typeof state.value === 'string'
      ? state.value
      : JSON.stringify(state.value ?? null);
  const pending = pendingBossQuestionFromContext(state.context);
  const lines = [
    'Classify the following Boss message into exactly one of these events.',
    'Respond with JSON: { "type": "<EVENT>", ...routingFields }.',
    'Use { "type": "NO_ACTION" } when no FSM action should be taken.',
    'Do not include any textual answer/intent field — the runtime attaches the exact Boss text itself.',
    '',
    `Current state: ${currentState}`,
  ];
  if (pending !== undefined) {
    lines.push(
      `Pending question id: ${pending.questionId}`,
      `Pending asking player: ${pending.player}`,
      `Pending Boss question: ${pending.question}`,
    );
  }
  lines.push(
    '',
    'Events:',
    '- START: begin (or restart) the coding workflow. No routing fields.',
  );
  if (currentState === 'awaitBossReply') {
    lines.push(
      '- BOSS_REPLY: Boss is answering the pending question. Routing field questionId?: "<pending question id>".',
    );
  } else {
    lines.push('- BOSS_REPLY: valid only when Current state is awaitBossReply');
  }
  lines.push('', 'Boss message:', '```', text, '```');
  return lines.join('\n');
}

async function classifyBossText(
  text: string,
  ports: PlaybookPorts,
  signal: AbortSignal,
  snapshotOrState?: unknown,
  boundary?: RuntimeBoundaryCalls,
): Promise<WorkflowEvent | undefined> {
  if (text.trim() === '') return undefined;

  const state = classifierState(snapshotOrState);
  const prompt = buildClassifierPrompt(text, state);
  const stateId = typeof state.value === 'string' ? state.value : undefined;
  const raw = boundary
    ? await boundary.callJudge(
        'boss-input-classification',
        stateId,
        prompt,
        signal,
      )
    : await ports.callJudge(prompt, signal);

  let parsed: unknown;
  try {
    parsed = parseJudgeJson(raw);
  } catch {
    await ports.emitStatus('Classifier reply was not recoverable JSON');
    return undefined;
  }
  if (!isPlainObject(parsed)) {
    await ports.emitStatus('Classifier returned a non-object JSON response');
    return undefined;
  }
  const obj = parsed as Record<string, unknown>;
  const type = obj.type;
  if (typeof type !== 'string') {
    await ports.emitStatus('Classifier did not name an event type');
    return undefined;
  }
  const allowed = CLASSIFIER_ROUTING_KEYS[type];
  if (allowed === undefined) {
    await ports.emitStatus(`Classifier returned unknown event type: ${type}`);
    return undefined;
  }
  for (const key of Object.keys(obj)) {
    if (key === 'type') continue;
    if (!allowed.has(key)) {
      await ports.emitStatus(
        `Classifier supplied an undeclared field for ${type}: ${key}`,
      );
      return undefined;
    }
  }

  switch (type) {
    case 'NO_ACTION':
      return undefined;
    case 'START':
      return { type: 'START' };
    case 'BOSS_REPLY': {
      if (state.value !== 'awaitBossReply') {
        await ports.emitStatus(
          'Classifier returned BOSS_REPLY outside awaitBossReply',
        );
        return undefined;
      }
      const pending = pendingBossQuestionFromContext(state.context);
      if (!pending) {
        await ports.emitStatus(
          'Classifier returned BOSS_REPLY without a pending question',
        );
        return undefined;
      }
      if (obj.questionId !== undefined && typeof obj.questionId !== 'string') {
        await ports.emitStatus(
          'Classifier supplied a non-string questionId for BOSS_REPLY',
        );
        return undefined;
      }
      if (
        typeof obj.questionId === 'string' &&
        obj.questionId !== pending.questionId
      ) {
        await ports.emitStatus(
          `Classifier supplied unknown questionId for BOSS_REPLY: ${obj.questionId}`,
        );
        return undefined;
      }
      // Attach the exact original Boss text as `answer` (slc/link.md
      // §Boss-event mapping); the classifier never supplies it.
      return {
        type: 'BOSS_REPLY',
        answer: text,
        questionId: pending.questionId,
      };
    }
    default:
      await ports.emitStatus(`Classifier returned unknown event type: ${type}`);
      return undefined;
  }
}

function formatClassification(eventType: string): string {
  return eventType;
}

// ---------------------------------------------------------------------------
// Provided actors.
// ---------------------------------------------------------------------------

function validateBossReplyOutput(
  input: PlayerInput,
  output: PlayerOutput,
): void {
  if (output.guard !== 'needsBossReply') return;
  if (typeof output.question !== 'string') {
    throw new Error(BOSS_REPLY_ERRORS.missingQuestion);
  }
  if (!registeredResumableStateIds.has(input.stateId)) {
    throw new Error(BOSS_REPLY_ERRORS.unregisteredState(input.stateId));
  }
}

// Delegated-player actor: resolve the player id, compose the prompt, call the
// host player, adjudicate the reply into a PlayerOutput. A non-`ok` result or a
// missing finalText rejects so XState routes onError → #failed.
function playerActor(
  ports: PlaybookPorts,
  getActiveSignal: () => AbortSignal | undefined,
  drain: () => Promise<void>,
  boundary?: RuntimeBoundaryCalls,
  onControlPlaneError?: (error: unknown) => void,
) {
  return fromPromise<PlayerOutput, PlayerInput>(async ({ input, signal }) => {
    // State-entry transition/status must reach the host before this call.
    await drain();
    const activeSignal = combineAbortSignals(signal, getActiveSignal());
    const playerId = resolvePlayerId(input);
    const prompt = composePlayerPrompt(input);
    const result = boundary
      ? await boundary.callPlayer(input, playerId, prompt, activeSignal)
      : await ports.callPlayer(playerId, prompt, activeSignal, {
          resume: false,
        });
    if (result.status !== 'ok') {
      throw new Error(
        result.error ?? `playerActor: callPlayer status "${result.status}"`,
      );
    }
    if (result.finalText === undefined) {
      throw new Error(
        'playerActor: callPlayer returned status=ok with no finalText',
      );
    }
    try {
      const output = await adjudicate(
        input,
        result.finalText,
        ports,
        activeSignal,
        boundary,
      );
      validateBossReplyOutput(input, output);
      return output;
    } catch (error) {
      onControlPlaneError?.(error);
      throw error;
    }
  });
}

// Deterministic script actor (slc/link.md §Script execution): run the command
// through `sh -c`, resolve the FSM's two guards by exit status, and emit one
// status line plus one `playbook.script` telemetry event. No agent, no
// adjudication, and no `*.call.*` trace pair.
function scriptActor(
  ports: PlaybookPorts,
  getActiveSignal: () => AbortSignal | undefined,
  getCwd: () => string | undefined,
  drain: () => Promise<void>,
) {
  return fromPromise<ScriptOutput, ScriptInput>(async ({ input, signal }) => {
    await drain();
    const activeSignal = combineAbortSignals(signal, getActiveSignal());
    const guards = Object.keys(input.result);
    const exitStatus = await runShellCommand(
      input.command,
      getCwd(),
      activeSignal,
    );
    await ports.emitStatus(
      `Executed script for ${input.stateId} (exit ${exitStatus}).`,
    );
    await ports.emitTelemetry({
      topic: 'playbook.script',
      payload: {
        stateId: input.stateId,
        sourceItem: input.sourceItem,
        exitStatus,
      },
    });
    const guard = exitStatus === 0 ? guards[0] : guards[1];
    return { guard, exitStatus } as ScriptOutput;
  });
}

function runShellCommand(
  command: string,
  cwd: string | undefined,
  signal: AbortSignal,
): Promise<number> {
  return new Promise<number>((resolve, reject) => {
    if (signal.aborted) {
      reject(signal.reason ?? new Error('script aborted'));
      return;
    }
    let child: ChildProcess;
    try {
      child = spawn('sh', ['-c', command], {
        cwd: cwd ?? process.cwd(),
        stdio: 'ignore',
      });
    } catch (error) {
      reject(error);
      return;
    }
    let settled = false;
    const onAbort = (): void => {
      if (settled) return;
      child.kill('SIGTERM');
    };
    signal.addEventListener('abort', onAbort, { once: true });
    child.once('error', (error) => {
      if (settled) return;
      settled = true;
      signal.removeEventListener('abort', onAbort);
      reject(error);
    });
    child.once('close', (code) => {
      if (settled) return;
      settled = true;
      signal.removeEventListener('abort', onAbort);
      if (signal.aborted) {
        reject(signal.reason ?? new Error('script aborted'));
        return;
      }
      resolve(typeof code === 'number' ? code : 1);
    });
  });
}

// ---------------------------------------------------------------------------
// Telemetry / status descriptors.
// ---------------------------------------------------------------------------

interface ScheduledStatus {
  message: string;
  data?: JsonValue;
}

function structuredStateTelemetryPayload(
  previousState: PlaybookState | undefined,
  state: PlaybookState,
  event: unknown,
  context: Record<string, unknown>,
): JsonValue {
  const payload: Record<string, unknown> = {
    from: previousState?.value ?? null,
    to: state.value,
    event: normalizeEventForTelemetry(event) ?? null,
    previousState: previousState ?? null,
    state,
  };
  if (state.stateId === 'awaitBossReply') {
    const pending = pendingBossQuestionFromContext(context);
    if (pending !== undefined) payload.pendingBossQuestion = pending;
  }
  if (state.stateId === 'failed') {
    const lastError = normalizeErrorFull(context.lastError);
    if (lastError !== undefined) payload.lastError = lastError;
  }
  return snapshotJsonValue(payload, 'FSM telemetry payload');
}

function formatStateEntry(
  stateId: string,
  context: Record<string, unknown>,
): ScheduledStatus | undefined {
  if (SUPPRESSED_ENTRY_STATES.has(stateId)) return undefined;
  if (stateId === 'awaitBossReply') {
    const pending = pendingBossQuestionFromContext(context);
    const player = pending?.player ?? 'unknown';
    const question = pending?.question ?? '';
    return { message: `${player} 向 Boss 提问：${question}` };
  }
  if (stateId === 'failed') {
    const lastError = normalizeErrorCompact(context.lastError);
    return {
      message: STATE_LABELS.failed,
      ...(lastError === undefined
        ? {}
        : { data: snapshotJsonValue({ lastError }, 'failed status data') }),
    };
  }
  return { message: STATE_LABELS[stateId] ?? stateId };
}

// Internal export surface for compilation-correctness tests (slc/link.md
// §Output). Not part of the stable public API.
export const _internal = {
  composePlayerPrompt,
  substitutePlaceholders,
  resolvePlayerId,
  adjudicate,
  extractRequiredFields,
  buildJudgePrompt,
  parseJudgeJson,
  classifyBossText,
  buildClassifierPrompt,
  pendingBossQuestionFromContext,
  formatStateEntry,
  formatClassification,
  normalizeErrorCompact,
  normalizeErrorFull,
  normalizeEventForTelemetry,
  STATE_LABELS,
};

type BossSettlementOutcome =
  | 'no-action'
  | 'quiescent'
  | 'failed'
  | 'terminal'
  | 'aborted';

interface TracePosition {
  turnId?: number;
  callId?: string;
}

// ---------------------------------------------------------------------------
// Runtime factory.
// ---------------------------------------------------------------------------

export default function createPlaybookRuntime(
  options: WorkflowPlaybookOptions,
): PlaybookRuntime {
  const boundOptions = snapshotWorkflowPlaybookOptions(options);
  const machineInput: WorkflowInput = {};

  let actor: ReturnType<typeof createActor> | undefined;
  let session: PlaybookSession | undefined;
  let initialized = false;
  let initInFlight: Promise<void> | undefined;
  let disposalPromise: Promise<void> | undefined;
  let disposed = false;
  let savedPorts: PlaybookPorts | undefined;
  let runtimePorts: PlaybookPorts | undefined;
  let activeSignal: AbortSignal | undefined;
  let activeTurnId: number | undefined;
  let controlPlaneError: unknown;
  let priorState: PlaybookState | undefined;
  let suppressInspectionEmissions = false;

  let traceSequence = 0;
  let turnSequence = 0;
  let judgeCallSequence = 0;
  let playerCallSequence = 0;
  const playbookCallSequence = 0;
  const playerResumeTokens = new Map<string, string>();
  const activePlayerIds = new Set<string>();
  const judgeQueue = new PQueue({ concurrency: 1 });
  const emissionQueue = new PQueue({ concurrency: 1 });
  const activeEmissionCalls = new Set<Promise<void>>();
  let emissionFailure: unknown;

  function enqueueEmission(fn: () => Promise<void>): Promise<void> {
    const queued = emissionQueue.add(fn).then(() => undefined);
    activeEmissionCalls.add(queued);
    void queued.then(
      () => activeEmissionCalls.delete(queued),
      (error: unknown) => {
        activeEmissionCalls.delete(queued);
        emissionFailure ??= error;
      },
    );
    return queued;
  }

  async function drainEmissions(): Promise<void> {
    while (true) {
      const active = [...activeEmissionCalls];
      if (active.length > 0) await Promise.allSettled(active);
      await emissionQueue.onIdle();
      if (
        activeEmissionCalls.size === 0 &&
        emissionQueue.size === 0 &&
        emissionQueue.pending === 0
      ) {
        break;
      }
    }
    if (emissionFailure !== undefined) {
      const error = emissionFailure;
      emissionFailure = undefined;
      throw error;
    }
  }

  function requireSession(): PlaybookSession {
    if (!session) {
      throw new Error('createPlaybookRuntime: init must be called first');
    }
    return session;
  }

  function requireHostPorts(): PlaybookPorts {
    if (!savedPorts) {
      throw new Error('createPlaybookRuntime: init must be called first');
    }
    return savedPorts;
  }

  function stateIdentity(stateId: string | undefined): { stateId?: string } {
    return stateId === undefined ? {} : { stateId };
  }

  function currentState(): PlaybookState {
    if (!actor) {
      throw new Error('createPlaybookRuntime: actor is not initialized');
    }
    return normalizePlaybookSnapshot(actor.getSnapshot());
  }

  function stateTracePayload(state = currentState()): Record<string, unknown> {
    return { state, ...stateIdentity(state.stateId) };
  }

  function createTraceEvent(
    type: PlaybookTraceType,
    payload: unknown,
    position: TracePosition = {},
  ): PlaybookTraceEvent {
    const currentSession = requireSession();
    const safePayload = snapshotJsonValue(payload, `trace ${type} payload`);
    return {
      schemaVersion: 2,
      sessionId: currentSession.sessionId,
      playbookId: currentSession.playbookId,
      rootSessionId: currentSession.rootSessionId,
      ...(currentSession.parentSessionId !== undefined
        ? { parentSessionId: currentSession.parentSessionId }
        : {}),
      ...(currentSession.parentCallId !== undefined
        ? { parentCallId: currentSession.parentCallId }
        : {}),
      depth: currentSession.depth,
      sequence: ++traceSequence,
      timestamp: Date.now(),
      type,
      ...(position.turnId !== undefined ? { turnId: position.turnId } : {}),
      ...(position.callId !== undefined ? { callId: position.callId } : {}),
      payload: safePayload,
    };
  }

  function emitTrace(
    type: PlaybookTraceType,
    payload: unknown,
    position: TracePosition = {},
  ): Promise<void> {
    const currentSession = requireSession();
    const event = createTraceEvent(type, payload, position);
    return enqueueEmission(() =>
      currentSession.ports.emitTelemetry({
        topic: 'playbook.trace',
        payload: event,
      }),
    );
  }

  function tracePositionForActiveTurn(): TracePosition {
    return activeTurnId === undefined ? {} : { turnId: activeTurnId };
  }

  function createRuntimePorts(hostPorts: PlaybookPorts): PlaybookPorts {
    return {
      callPlayer: (playerId, prompt, signal, callOptions) =>
        hostPorts.callPlayer(playerId, prompt, signal, callOptions),
      callCaptain: (prompt, signal, callOptions) =>
        hostPorts.callCaptain(prompt, signal, callOptions),
      callJudge: (prompt, signal) => hostPorts.callJudge(prompt, signal),
      callPlaybook: (request, signal) =>
        hostPorts.callPlaybook(request, signal),
      emitStatus: (message, data) => {
        const descriptor = actor ? currentState() : undefined;
        const safeData =
          data === undefined
            ? undefined
            : snapshotJsonValue(data, 'status data');
        const trace = createTraceEvent(
          'status.emitted',
          {
            message,
            ...(safeData !== undefined ? { data: safeData } : {}),
            ...(descriptor !== undefined
              ? { state: descriptor, ...stateIdentity(descriptor.stateId) }
              : {}),
          },
          activeTurnId !== undefined ? { turnId: activeTurnId } : {},
        );
        return enqueueEmission(async () => {
          await hostPorts.emitTelemetry({
            topic: 'playbook.trace',
            payload: trace,
          });
          await hostPorts.emitStatus(message, safeData);
        });
      },
      emitTelemetry: (event) => {
        if (typeof event.topic !== 'string' || event.topic.length === 0) {
          throw new TypeError('telemetry topic must be a non-empty string');
        }
        const payload = snapshotJsonValue(event.payload, 'telemetry payload');
        return enqueueEmission(() =>
          hostPorts.emitTelemetry({ topic: event.topic, payload }),
        );
      },
    };
  }

  async function emitCallStarted(
    startedType: 'player.call.started' | 'judge.call.started',
    finishedType: 'player.call.finished' | 'judge.call.finished',
    identity: Record<string, unknown>,
    position: TracePosition,
  ): Promise<void> {
    try {
      await emitTrace(startedType, identity, position);
    } catch (error) {
      controlPlaneError ??= error;
      try {
        await emitTrace(
          finishedType,
          { ...identity, status: 'error', error: normalizeError(error) },
          position,
        );
      } catch {
        // Preserve the start failure after one best-effort finish attempt.
      }
      throw error;
    }
  }

  const boundary: RuntimeBoundaryCalls = {
    async callPlayer(input, playerId, prompt, signal): Promise<PlayerResult> {
      await drainEmissions();
      const turnId = activeTurnId;
      const callId = `player-${++playerCallSequence}`;
      const resume = playerResumeTokens.get(playerId) ?? false;
      const identity = {
        ...stateIdentity(input.stateId),
        sourceItem: input.sourceItem,
        playerId,
        resume,
      };
      const position: TracePosition = {
        ...(turnId !== undefined ? { turnId } : {}),
        callId,
      };

      if (activePlayerIds.has(playerId)) {
        const error = new Error(
          `simultaneous calls to resolved player ${playerId} are not allowed`,
        );
        await emitCallStarted(
          'player.call.started',
          'player.call.finished',
          { ...identity, prompt },
          position,
        );
        await emitTrace(
          'player.call.finished',
          { ...identity, status: 'error', error: normalizeError(error) },
          position,
        );
        throw error;
      }
      activePlayerIds.add(playerId);

      try {
        await emitTrace(
          'player.call.started',
          { ...identity, prompt },
          position,
        );

        let rawResult: unknown;
        try {
          rawResult = await requireHostPorts().callPlayer(
            playerId,
            prompt,
            signal,
            {
              resume,
            },
          );
          signal.throwIfAborted();
        } catch (error) {
          if (!signal.aborted) controlPlaneError ??= error;
          try {
            await emitTrace(
              'player.call.finished',
              {
                ...identity,
                status: signal.aborted ? 'aborted' : 'error',
                error: normalizeError(error),
              },
              position,
            );
          } catch {
            // The original port rejection remains authoritative.
          }
          throw error;
        }

        let result: PlayerResult;
        try {
          result = validatePlayerResult(rawResult);
        } catch (error) {
          if (!signal.aborted) controlPlaneError ??= error;
          try {
            await emitTrace(
              'player.call.finished',
              { ...identity, status: 'error', error: normalizeError(error) },
              position,
            );
          } catch {
            // The malformed host result remains authoritative.
          }
          throw error;
        }

        if (
          typeof result.resumeToken === 'string' &&
          result.resumeToken.trim().length > 0
        ) {
          playerResumeTokens.set(playerId, result.resumeToken);
        } else {
          playerResumeTokens.delete(playerId);
        }

        await emitTrace(
          'player.call.finished',
          {
            ...identity,
            status: result.status,
            ...(result.finalText !== undefined
              ? { finalText: result.finalText }
              : {}),
            ...(result.error !== undefined
              ? { error: normalizeError(result.error) }
              : {}),
            ...(result.resumeToken !== undefined
              ? { resumeToken: result.resumeToken }
              : {}),
          },
          position,
        );
        return result;
      } finally {
        activePlayerIds.delete(playerId);
      }
    },

    async callJudge(purpose, stateId, prompt, signal): Promise<string> {
      return judgeQueue.add(async () => {
        signal.throwIfAborted();
        await drainEmissions();
        signal.throwIfAborted();
        const turnId = activeTurnId;
        const callId = `judge-${++judgeCallSequence}`;
        const identity = { purpose, ...stateIdentity(stateId) };
        const position: TracePosition = {
          ...(turnId !== undefined ? { turnId } : {}),
          callId,
        };

        await emitCallStarted(
          'judge.call.started',
          'judge.call.finished',
          { ...identity, prompt },
          position,
        );
        let reply: unknown;
        try {
          reply = await requireHostPorts().callJudge(prompt, signal);
          signal.throwIfAborted();
        } catch (error) {
          if (!isAbortFailure(error, signal)) controlPlaneError ??= error;
          await emitTrace(
            'judge.call.finished',
            {
              ...identity,
              status: signal.aborted ? 'aborted' : 'error',
              error: normalizeError(error),
            },
            position,
          );
          throw error;
        }
        if (typeof reply !== 'string') {
          const error = new TypeError('judge reply must be a string');
          controlPlaneError ??= error;
          await emitTrace(
            'judge.call.finished',
            { ...identity, status: 'error', error: normalizeError(error) },
            position,
          );
          throw error;
        }
        await emitTrace(
          'judge.call.finished',
          { ...identity, status: 'ok', reply },
          position,
        );
        return reply;
      }) as Promise<string>;
    },
  };

  function enqueueTransitionEmission(
    payload: JsonValue,
    state: PlaybookState,
    statuses: readonly ScheduledStatus[],
    position: TracePosition,
  ): void {
    const currentSession = requireSession();
    const transitionTrace = createTraceEvent(
      'fsm.transition',
      payload,
      position,
    );
    const statusEmissions = statuses.map(({ message, data }) => ({
      message,
      data,
      trace: createTraceEvent(
        'status.emitted',
        {
          message,
          ...(data === undefined ? {} : { data }),
          state,
          ...stateIdentity(state.stateId),
        },
        position,
      ),
    }));
    void enqueueEmission(async () => {
      await currentSession.ports.emitTelemetry({
        topic: 'playbook.trace',
        payload: transitionTrace,
      });
      await currentSession.ports.emitTelemetry({
        topic: 'playbook.fsm.state',
        payload,
      });
      for (const status of statusEmissions) {
        await currentSession.ports.emitTelemetry({
          topic: 'playbook.trace',
          payload: status.trace,
        });
        await currentSession.ports.emitStatus(status.message, status.data);
      }
    }).catch(() => undefined);
  }

  function latchInspectionError(error: unknown): void {
    if (activeSignal !== undefined) controlPlaneError ??= error;
    else emissionFailure ??= error;
  }

  function buildActor(
    ports: PlaybookPorts,
    machineSnapshot?: JsonValue,
  ): ReturnType<typeof createActor> {
    priorState = undefined;
    const builtActor: ReturnType<typeof createActor> = createActor(
      workflowMachine.provide({
        actors: {
          player: playerActor(
            ports,
            () => activeSignal,
            drainEmissions,
            boundary,
            (error) => {
              if (!activeSignal?.aborted) controlPlaneError ??= error;
            },
          ),
          script: scriptActor(
            ports,
            () => activeSignal,
            () => boundOptions.cwd,
            drainEmissions,
          ),
        },
      }),
      {
        input: machineInput,
        ...(machineSnapshot === undefined
          ? {}
          : {
              snapshot: machineSnapshot as unknown as SnapshotFrom<
                typeof workflowMachine
              >,
            }),
        inspect: (inspectionEvent: InspectionEvent) => {
          if (inspectionEvent.type !== '@xstate.snapshot') return;
          if (inspectionEvent.actorRef !== builtActor) return;
          if (suppressInspectionEmissions) return;
          try {
            const snap = inspectionEvent.snapshot as SnapshotFrom<
              typeof workflowMachine
            >;
            const state = normalizePlaybookSnapshot(snap);
            const to = state.stateId;
            if (to === undefined) {
              throw new Error(
                'workflow root snapshot must expose exactly one playbook state id',
              );
            }
            const previousState = priorState;
            const context = snap.context as unknown as Record<string, unknown>;
            const payload = structuredStateTelemetryPayload(
              previousState,
              state,
              inspectionEvent.event,
              context,
            );
            const statuses: ScheduledStatus[] = [];
            const entry = formatStateEntry(to, context);
            if (entry !== undefined) statuses.push(entry);
            enqueueTransitionEmission(
              payload,
              state,
              statuses,
              tracePositionForActiveTurn(),
            );
            priorState = state;
          } catch (error) {
            latchInspectionError(error);
          }
        },
      },
    );
    return builtActor;
  }

  function runResultFor(
    outcome: BossSettlementOutcome,
    error?: unknown,
  ): PlaybookRunResult {
    const state = currentState();
    if (outcome === 'quiescent' || outcome === 'no-action') {
      return { outcome, state };
    }
    if (outcome === 'terminal') {
      const output = (actor?.getSnapshot() as { output?: unknown } | undefined)
        ?.output;
      if (output !== undefined) {
        return {
          outcome,
          state,
          output: snapshotJsonValue(output, 'terminal playbook output'),
        };
      }
      return { outcome, state };
    }
    const failure =
      error ??
      (outcome === 'failed'
        ? (actor?.getSnapshot() as { context?: { lastError?: unknown } })
            ?.context?.lastError
        : outcome === 'aborted'
          ? activeSignal?.reason
          : undefined);
    return {
      outcome,
      state,
      ...(failure !== undefined ? { error: normalizeError(failure) } : {}),
    };
  }

  function settledOutcome(signal: AbortSignal): BossSettlementOutcome {
    if (signal.aborted) return 'aborted';
    const state = currentState();
    if (state.status === 'error') {
      const actorError = (
        actor?.getSnapshot() as { error?: unknown } | undefined
      )?.error;
      throw actorError ?? new Error('workflow actor entered error status');
    }
    if (state.status === 'done') return 'terminal';
    if (state.stateId === 'failed') return 'failed';
    return 'quiescent';
  }

  function settlementTracePayload(
    result: PlaybookRunResult,
  ): Record<string, unknown> {
    return { ...result, ...stateIdentity(result.state.stateId) };
  }

  async function cleanupFailedStart(
    cause: unknown,
    options: { emitDisposal: boolean },
  ): Promise<void> {
    let finalState: PlaybookState | undefined;
    if (options.emitDisposal && actor) {
      try {
        finalState = currentState();
      } catch {
        // A state that cannot normalize has no disposal descriptor.
      }
    }
    suppressInspectionEmissions = true;
    try {
      actor?.stop();
    } catch {
      // Preserve the original startup failure.
    }
    try {
      await judgeQueue.onIdle();
      await drainEmissions();
    } catch {
      // Preserve the original startup failure.
    }
    if (options.emitDisposal) {
      try {
        await emitTrace(
          'session.disposed',
          finalState === undefined
            ? {}
            : { state: finalState, ...stateIdentity(finalState.stateId) },
        );
        await drainEmissions();
      } catch {
        // The session-start error remains authoritative.
      }
    }
    void cause;
    playerResumeTokens.clear();
    activePlayerIds.clear();
    activeEmissionCalls.clear();
    emissionQueue.clear();
    judgeQueue.clear();
    actor = undefined;
    session = undefined;
    savedPorts = undefined;
    runtimePorts = undefined;
    activeSignal = undefined;
    activeTurnId = undefined;
    controlPlaneError = undefined;
    emissionFailure = undefined;
    priorState = undefined;
    suppressInspectionEmissions = false;
    initialized = false;
    traceSequence = 0;
    turnSequence = 0;
    judgeCallSequence = 0;
    playerCallSequence = 0;
  }

  const runtime = {
    async init(nextSession: PlaybookSession): Promise<void> {
      if (initialized || disposed || disposalPromise !== undefined) {
        throw new Error('createPlaybookRuntime.init: already initialized');
      }
      const boundSession = snapshotPlaybookSession(nextSession);
      initialized = true;
      let finishInitialization!: () => void;
      const initialization = new Promise<void>((resolve) => {
        finishInitialization = resolve;
      });
      initInFlight = initialization;
      const initTask = (async () => {
        session = boundSession;
        savedPorts = boundSession.ports;
        runtimePorts = createRuntimePorts(boundSession.ports);
        suppressInspectionEmissions = false;
        actor = buildActor(runtimePorts);
        await emitTrace('session.started', stateTracePayload());
        actor.start();
        await drainEmissions();
      })();
      try {
        await initTask;
      } catch (error) {
        await cleanupFailedStart(error, { emitDisposal: true });
        throw error;
      } finally {
        finishInitialization();
        if (initInFlight === initialization) initInFlight = undefined;
      }
    },

    exportSnapshot(): PlaybookRuntimeSnapshot | undefined {
      if (!actor || !session || disposed || disposalPromise !== undefined) {
        return undefined;
      }
      if (activeSignal !== undefined) return undefined;
      const state = currentState();
      if (state.status !== 'active' || !state.quiescent) return undefined;
      const machine = detachPersistedMachineSnapshot(
        actor.getPersistedSnapshot(),
      );
      const context = (actor.getSnapshot() as { context?: unknown })
        .context as Record<string, unknown>;
      const pending = pendingBossQuestionFromContext(context ?? {});
      return {
        schemaVersion: 1,
        playbookId: session.playbookId,
        machine,
        playerResumeTokens: Object.fromEntries(playerResumeTokens),
        sequences: {
          trace: traceSequence,
          turn: turnSequence,
          judgeCall: judgeCallSequence,
          playerCall: playerCallSequence,
          playbookCall: playbookCallSequence,
        },
        state,
        pendingBossQuestions:
          pending === undefined
            ? []
            : [
                {
                  questionId: pending.questionId,
                  player: pending.player,
                  question: pending.question,
                  sourceItem: pending.sourceItem,
                },
              ],
      };
    },

    async restore(
      nextSession: PlaybookSession,
      snapshot: PlaybookRuntimeSnapshot,
    ): Promise<void> {
      if (initialized || disposed || disposalPromise !== undefined) {
        throw new Error('createPlaybookRuntime.restore: already initialized');
      }
      const boundSession = snapshotPlaybookSession(nextSession);
      const boundSnapshot = assertPlaybookRuntimeSnapshot(
        snapshot,
        boundSession.playbookId,
      );
      initialized = true;
      let finishInitialization!: () => void;
      const initialization = new Promise<void>((resolve) => {
        finishInitialization = resolve;
      });
      initInFlight = initialization;
      const initTask = (async () => {
        session = boundSession;
        savedPorts = boundSession.ports;
        runtimePorts = createRuntimePorts(boundSession.ports);
        traceSequence = boundSnapshot.sequences.trace;
        turnSequence = boundSnapshot.sequences.turn;
        judgeCallSequence = boundSnapshot.sequences.judgeCall;
        playerCallSequence = boundSnapshot.sequences.playerCall;
        playerResumeTokens.clear();
        for (const [playerId, token] of Object.entries(
          boundSnapshot.playerResumeTokens,
        )) {
          playerResumeTokens.set(playerId, token);
        }
        suppressInspectionEmissions = true;
        actor = buildActor(runtimePorts, boundSnapshot.machine);
        actor.start();
        const restoredState = currentState();
        if (restoredState.status !== 'active') {
          throw new Error(
            `createPlaybookRuntime.restore: restored actor status is ${restoredState.status}, expected active`,
          );
        }
        suppressInspectionEmissions = false;
        priorState = restoredState;
        await drainEmissions();
      })();
      try {
        await initTask;
      } catch (error) {
        await cleanupFailedStart(error, { emitDisposal: false });
        throw error;
      } finally {
        finishInitialization();
        if (initInFlight === initialization) initInFlight = undefined;
      }
    },

    async handleBossInput({
      text,
      signal,
    }: {
      text: string;
      signal: AbortSignal;
    }): Promise<PlaybookRunResult> {
      if (!actor || !savedPorts || !runtimePorts) {
        throw new Error(
          'createPlaybookRuntime.handleBossInput: init must be called first',
        );
      }
      if (disposed || disposalPromise !== undefined) {
        throw new Error(
          'createPlaybookRuntime.handleBossInput: runtime is disposing or disposed',
        );
      }
      if (activeSignal !== undefined) {
        throw new Error(
          'createPlaybookRuntime.handleBossInput: another runtime turn is active',
        );
      }
      const turnId = ++turnSequence;
      activeTurnId = turnId;
      activeSignal = signal;
      controlPlaneError = undefined;
      let result: PlaybookRunResult | undefined;
      let operationError: unknown;
      try {
        await emitTrace('boss.input.received', { text }, { turnId });
        const event = await classifyBossText(
          text,
          runtimePorts,
          signal,
          actor.getSnapshot(),
          boundary,
        );
        if (event === undefined) {
          result = runResultFor('no-action');
        } else {
          await runtimePorts.emitStatus(formatClassification(event.type));
          if (actor.getSnapshot().status === 'done') {
            actor.stop();
            actor = buildActor(runtimePorts);
            actor.start();
          }
          actor.send(event);
          await waitForPlaybookQuiescence(actor);
          if (controlPlaneError !== undefined) throw controlPlaneError;
          result = runResultFor(settledOutcome(signal));
        }
      } catch (error) {
        operationError = error;
      }

      let drainError: unknown;
      try {
        await drainEmissions();
      } catch (error) {
        drainError = error;
      }
      const latchedControlError = controlPlaneError;
      const primaryError = latchedControlError ?? drainError ?? operationError;
      const abortError =
        latchedControlError === undefined &&
        drainError === undefined &&
        operationError !== undefined &&
        isAbortFailure(operationError, signal);
      const settlementResult =
        primaryError === undefined
          ? (result ?? runResultFor('no-action'))
          : runResultFor(abortError ? 'aborted' : 'failed', primaryError);

      let settlementEmissionError: unknown;
      try {
        await emitTrace(
          'boss.input.settled',
          settlementTracePayload(settlementResult),
          { turnId },
        );
      } catch (error) {
        settlementEmissionError = error;
      }
      try {
        await drainEmissions();
      } catch (error) {
        settlementEmissionError ??= error;
      }
      const failure =
        controlPlaneError ??
        latchedControlError ??
        drainError ??
        (abortError
          ? (settlementEmissionError ?? operationError)
          : (operationError ?? settlementEmissionError));
      activeSignal = undefined;
      activeTurnId = undefined;
      controlPlaneError = undefined;

      if (
        failure !== undefined &&
        !(abortError && settlementEmissionError === undefined)
      ) {
        throw failure;
      }
      return settlementResult;
    },

    async resumePlaybookCall(input: {
      callId: string;
      result: PlaybookCallResult;
      signal: AbortSignal;
    }): Promise<PlaybookRunResult> {
      if (!actor || !savedPorts) {
        throw new Error(
          'createPlaybookRuntime.resumePlaybookCall: init must be called first',
        );
      }
      if (disposed || disposalPromise !== undefined) {
        throw new Error(
          'createPlaybookRuntime.resumePlaybookCall: runtime is disposing or disposed',
        );
      }
      if (activeSignal !== undefined) {
        throw new Error(
          'createPlaybookRuntime.resumePlaybookCall: another runtime turn is active',
        );
      }
      // This playbook declares no nested `playbook` actor, so no child call is
      // ever pending; every resume id is unknown and rejects without changing
      // actor state (slc/link.md §Nested playbook bridge).
      throw new Error(
        `createPlaybookRuntime.resumePlaybookCall: no pending playbook call for id "${input.callId}"`,
      );
    },

    dispose(): Promise<void> {
      if (disposalPromise !== undefined) return disposalPromise;
      if (disposed) return Promise.resolve();
      if (activeSignal !== undefined) {
        return Promise.reject(
          new Error(
            'createPlaybookRuntime.dispose: cannot dispose during an active runtime boundary',
          ),
        );
      }
      const task = (async (): Promise<void> => {
        const failures: unknown[] = [];
        try {
          if (initInFlight !== undefined) {
            try {
              await initInFlight;
            } catch {
              // Dispose still releases whatever an unsuccessful init bound.
            }
          }
          const finalState = actor ? currentState() : undefined;
          if (actor) actor.stop();
          try {
            await drainEmissions();
          } catch (error) {
            failures.push(error);
          }
          if (session !== undefined) {
            try {
              await emitTrace(
                'session.disposed',
                finalState === undefined
                  ? {}
                  : { state: finalState, ...stateIdentity(finalState.stateId) },
              );
              await drainEmissions();
            } catch (error) {
              failures.push(error);
            }
          }
        } finally {
          playerResumeTokens.clear();
          activePlayerIds.clear();
          activeEmissionCalls.clear();
          emissionQueue.clear();
          judgeQueue.clear();
          actor = undefined;
          activeSignal = undefined;
          activeTurnId = undefined;
          controlPlaneError = undefined;
          emissionFailure = undefined;
          savedPorts = undefined;
          runtimePorts = undefined;
          session = undefined;
          disposed = true;
        }
        if (failures.length === 1) throw failures[0];
        if (failures.length > 1) {
          throw new AggregateError(
            failures,
            'playbook runtime disposal failed',
          );
        }
      })();
      disposalPromise = task;
      return task;
    },
  };

  return runtime as PlaybookRuntime;
}
