// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): prompt contract.
// The pinned rows were derived from the artifacts at build time; wiring,
// placeholder, or composition drift fails this test.
import { describe, expect, it } from 'vitest';

import {
  capturePromptContract,
  checkPromptComposition,
  deriveSubstitutions,
  findMachineConfig,
} from './.slc-verify/verify.js';
import * as fsm from './workflow.fsm.js';
import * as playbook from './workflow.playbook.js';

const CONTRACT = [
  {
    state: 'implement',
    sourceItem: 'CODE-2',
    player: '编码者',
    reads: ['bossReply', 'pendingBossQuestion', 'task'],
    wires: {
      task: ['task'],
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: ['<task>'],
  },
  {
    state: 'review',
    sourceItem: 'CODE-3',
    player: '审查者',
    reads: ['bossReply', 'pendingBossQuestion'],
    wires: {
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: [],
  },
  {
    state: 'adjudicate',
    sourceItem: 'CODE-4',
    player: '编码者',
    reads: [
      'bossReply',
      'pendingBossQuestion',
      'reviewFindings',
      'reviewerRebuttal',
    ],
    wires: {
      reviewFindings: ['reviewFindings'],
      reviewerRebuttal: ['reviewerRebuttal'],
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: ['<reviewFindings>', '<reviewerRebuttal>'],
  },
  {
    state: 'rebut',
    sourceItem: 'CODE-5',
    player: '审查者',
    reads: ['bossReply', 'coderRuling', 'pendingBossQuestion'],
    wires: {
      coderRuling: ['coderRuling'],
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: ['<coderRuling>'],
  },
  {
    state: 'applyConclusion',
    sourceItem: 'CODE-6',
    player: '编码者',
    reads: ['bossReply', 'conclusion', 'pendingBossQuestion'],
    wires: {
      conclusion: ['conclusion'],
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: ['<conclusion>'],
  },
];

describe('workflow: prompt contract', () => {
  it('matches the prompt contract pinned at build time', () => {
    expect(capturePromptContract(findMachineConfig(fsm))).toEqual(CONTRACT);
  });

  const PLAYER_SUBSTITUTED = {
    implement: ['<task>'],
    review: [],
    adjudicate: ['<reviewFindings>', '<reviewerRebuttal>'],
    rebut: ['<coderRuling>'],
    applyConclusion: ['<conclusion>'],
  };

  const composePlayer = (
    playbook as unknown as {
      _internal: { composePlayerPrompt: (input: unknown) => string };
    }
  )._internal.composePlayerPrompt;

  it('composes player prompts per the link contract', () => {
    expect(
      checkPromptComposition({
        config: findMachineConfig(fsm),
        compose: composePlayer,
        actor: 'player',
      }),
    ).toEqual([]);
  });

  it('substitutes the player placeholders pinned at build time', () => {
    expect(
      deriveSubstitutions(findMachineConfig(fsm), composePlayer, 'player'),
    ).toEqual(PLAYER_SUBSTITUTED);
  });
});
