// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): prompt contract.
// The pinned rows were derived from the artifacts at build time; wiring,
// placeholder, or composition drift fails this test.
import { describe, expect, it } from 'vitest';

import {
  capturePromptContract,
  checkPromptComposition,
  deriveSubstitutions,
  findMachineConfig,
} from './.slc-verify/verify.js';
import * as fsm from './workflow.fsm.js';
import * as playbook from './workflow.playbook.js';

const CONTRACT = [
  {
    state: 'implement',
    sourceItem: 'CODE-2',
    player: '编码者',
    reads: ['bossReply', 'pendingBossQuestion'],
    wires: {
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: [],
  },
  {
    state: 'review',
    sourceItem: 'CODE-3',
    player: '审查者',
    reads: ['bossReply', 'pendingBossQuestion'],
    wires: {
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: [],
  },
  {
    state: 'judge',
    sourceItem: 'CODE-4',
    player: '编码者',
    reads: ['bossReply', 'pendingBossQuestion', 'reviewComments'],
    wires: {
      reviewComments: ['reviewComments'],
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: ['<reviewComments>'],
  },
  {
    state: 'debate',
    sourceItem: 'CODE-5',
    player: '审查者',
    reads: ['bossReply', 'coderResponse', 'pendingBossQuestion'],
    wires: {
      coderResponse: ['coderResponse'],
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: ['<coderResponse>'],
  },
  {
    state: 'revise',
    sourceItem: 'CODE-6',
    player: '编码者',
    reads: ['agreedConclusion', 'bossReply', 'pendingBossQuestion'],
    wires: {
      agreedConclusion: ['agreedConclusion'],
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: ['<agreedConclusion>'],
  },
];

describe('workflow: prompt contract', () => {
  it('matches the prompt contract pinned at build time', () => {
    expect(capturePromptContract(findMachineConfig(fsm))).toEqual(CONTRACT);
  });

  const PLAYER_SUBSTITUTED = {
    implement: [],
    review: [],
    judge: ['<reviewComments>'],
    debate: ['<coderResponse>'],
    revise: ['<agreedConclusion>'],
  };

  const composePlayer = (
    playbook as unknown as {
      _internal: { composePlayerPrompt: (input: unknown) => string };
    }
  )._internal.composePlayerPrompt;

  it('composes player prompts per the link contract', () => {
    expect(
      checkPromptComposition({
        config: findMachineConfig(fsm),
        compose: composePlayer,
        actor: 'player',
      }),
    ).toEqual([]);
  });

  it('substitutes the player placeholders pinned at build time', () => {
    expect(
      deriveSubstitutions(findMachineConfig(fsm), composePlayer, 'player'),
    ).toEqual(PLAYER_SUBSTITUTED);
  });
});
