// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by slc/link.md (FSM-to-Runtime linker).
// Source FSM:    ./workflow.fsm.ts
// Player bind:   编码者→编码者, 审查者→审查者
//                (default binding: each player to its lowercased name;
//                Chinese names lowercase to themselves; no aliases in source)
// Boss event:    deterministic START at ready/reconstructed-terminal;
//                free-text judge classification at awaitBossReply and failed
// Adjudication:  LLM-judge per state
// Contract:      PlaybookPorts / PlaybookSession / PlaybookRuntime imported
//                and re-exported from @sublang/playbook/runtime
//                (slc/link.md §Output). The FSM declares only `player` and
//                `script` actors, so this runtime provides only those and
//                imports no captain/nested-playbook machinery.

import { spawn } from 'node:child_process';
import PQueue from 'p-queue';
import { createActor, fromPromise } from 'xstate';
import type { InspectionEvent, SnapshotFrom } from 'xstate';
import {
  combineAbortSignals,
  normalizeError,
  normalizePlaybookSnapshot,
  snapshotJsonValue,
  snapshotPlaybookSession,
  validatePlayerResult,
  waitForPlaybookQuiescence,
} from '@sublang/playbook/xstate-runtime';
import {
  workflowMachine,
  type PlayerInput,
  type PlayerOutput,
  type ScriptInput,
  type ScriptOutput,
  type WorkflowEvent,
  type WorkflowInput,
} from './workflow.fsm.js';
import type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookPendingCall,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlaybookPorts,
  PlayerResult,
} from '@sublang/playbook/runtime';

// Public contract re-export (slc/link.md §Output): one shared definition,
// never redefined here.
export type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookPendingCall,
  PlaybookRunResult,
  PlayerResult,
  PlaybookPorts,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
};

// Per-run options for this playbook. `task` seeds the FSM machine input
// (WorkflowInput); `cwd` is the working directory the deterministic `script`
// actor (CODE-1) runs in (slc/link.md §Script execution). Both optional.
export interface WorkflowPlaybookOptions extends WorkflowInput {
  cwd?: string;
}

function snapshotWorkflowOptions(value: unknown): WorkflowPlaybookOptions {
  const captured = snapshotJsonValue(value ?? {}, 'workflow runtime options');
  if (
    captured === null ||
    typeof captured !== 'object' ||
    Array.isArray(captured)
  ) {
    throw new TypeError('workflow runtime options must be an object');
  }
  const record = captured as Readonly<Record<string, JsonValue>>;
  const allowed = new Set(['task', 'cwd']);
  for (const [key, option] of Object.entries(record)) {
    if (!allowed.has(key)) {
      throw new TypeError(`workflow runtime options.${key} is not declared`);
    }
    if (typeof option !== 'string') {
      throw new TypeError(`workflow runtime options.${key} must be a string`);
    }
  }
  return captured as unknown as WorkflowPlaybookOptions;
}

const BOSS_REPLY_ERRORS = {
  missingQuestion: "needsBossReply outcome missing 'question' field",
  unregisteredState: (stateId: string) =>
    `state ${stateId} declared needsBossReply but is not registered as resumable`,
} as const;

// States that suspend a task pending a Boss reply (FSM RESUMABLE_STATE_IDS).
const RESUMABLE_STATE_IDS: ReadonlySet<string> = new Set([
  'implement',
  'review',
  'adjudicate',
  'rebut',
  'applyConclusion',
]);

// Working leaves that surface a human status on entry. `ready` and `done`
// stay silent (slc/link.md §Session lifecycle).
const SUPPRESSED_ENTRY_STATES: ReadonlySet<string> = new Set(['ready', 'done']);

// ---------------------------------------------------------------------------
// Pure helpers (exposed under `_internal` for verification).
// ---------------------------------------------------------------------------

// Every runtime-value placeholder Source established, backed by a typed
// PlayerInput field (slc/gears2fsm.md §Setup). Substitution is one
// callback-based pass over the original template; replacement text is
// literal (no `$&`/`$$` interpretation), and placeholder-looking text inside
// a value is never re-substituted (slc/link.md §Output).
const PLACEHOLDER_FIELDS: ReadonlyArray<
  [placeholder: string, field: keyof PlayerInput]
> = [
  ['<task>', 'task'],
  ['<reviewFindings>', 'reviewFindings'],
  ['<reviewerRebuttal>', 'reviewerRebuttal'],
  ['<coderRuling>', 'coderRuling'],
  ['<conclusion>', 'conclusion'],
];

const PLACEHOLDER_PATTERN =
  /<task>|<reviewFindings>|<reviewerRebuttal>|<coderRuling>|<conclusion>/g;

// Player-prompt composer (slc/link.md §Player prompt composition).
// When the task resumes from its own Boss question, the continuation
// preamble and labelled Q/A blocks precede the domain body. The GEARS
// blockquote body is never re-flowed; only its placeholders are filled.
function composePlayerPrompt(input: PlayerInput): string {
  const blocks: string[] = [];
  if (
    input.pendingBossQuestion !== undefined &&
    input.bossReply !== undefined
  ) {
    blocks.push(
      'You previously paused this task to ask Boss a question; Boss has now replied. Continue the same task using the reply below.',
    );
    blocks.push(`Boss question:\n${input.pendingBossQuestion.question}`);
    blocks.push(`Boss reply:\n${input.bossReply}`);
  }

  const substitutions = new Map<string, string>();
  for (const [placeholder, field] of PLACEHOLDER_FIELDS) {
    const value = input[field];
    if (typeof value === 'string') substitutions.set(placeholder, value);
  }
  const body = input.prompt.replace(
    PLACEHOLDER_PATTERN,
    (match) => substitutions.get(match) ?? '',
  );
  blocks.push(body);

  return blocks.join('\n\n');
}

// Player-id resolver (slc/link.md §Player binding). Default binding: each
// player to its lowercased name; the Chinese names lowercase to themselves.
// The source declares no composite (aliased) players.
function resolvePlayerId(input: PlayerInput): string {
  return input.player.toLowerCase();
}

interface PendingBossQuestionShape {
  questionId: string;
  resumeStateId: string;
  sourceItem: string;
  player: string;
  question: string;
}

function pendingBossQuestionFromContext(
  context: Record<string, unknown>,
): PendingBossQuestionShape | undefined {
  const pending = context.pendingBossQuestion;
  if (
    pending === undefined ||
    typeof pending !== 'object' ||
    pending === null
  ) {
    return undefined;
  }
  const candidate = pending as Partial<
    Record<keyof PendingBossQuestionShape, unknown>
  >;
  if (
    typeof candidate.questionId !== 'string' ||
    typeof candidate.resumeStateId !== 'string' ||
    typeof candidate.sourceItem !== 'string' ||
    typeof candidate.player !== 'string' ||
    typeof candidate.question !== 'string'
  ) {
    return undefined;
  }
  return {
    questionId: candidate.questionId,
    resumeStateId: candidate.resumeStateId,
    sourceItem: candidate.sourceItem,
    player: candidate.player,
    question: candidate.question,
  };
}

// Required-field extraction (slc/link.md §Captain adjudication). Limited to
// the description's `Output shall include` / `输出应包含` clause; recognizes
// both the bare backticked name and the annotated `name: <...>` form.
function extractRequiredFields(description: string): string[] {
  const markers = ['Output shall include', '输出应包含'];
  let clauseStart = -1;
  for (const marker of markers) {
    const idx = description.indexOf(marker);
    if (idx !== -1) {
      clauseStart = idx + marker.length;
      break;
    }
  }
  if (clauseStart === -1) return [];
  const clause = description.slice(clauseStart);
  const fields: string[] = [];
  const re = /`([A-Za-z_$][A-Za-z0-9_$]*)(?::[^`]*)?`/g;
  for (const m of clause.matchAll(re)) fields.push(m[1]);
  return fields;
}

function buildJudgePrompt(input: PlayerInput, finalText: string): string {
  const lines: string[] = [];
  lines.push(`The ${input.player} just produced this output:`);
  lines.push('');
  lines.push('```');
  lines.push(finalText);
  lines.push('```');
  lines.push('');
  lines.push(
    'Pick exactly one outcome by `guard` and return JSON ' +
      '`{ guard, …payloadFields }`. Required payload fields are named in the ' +
      'outcome description after "Output shall include" / "输出应包含".',
  );
  lines.push('');
  for (const [key, description] of Object.entries(input.result)) {
    lines.push(`- \`${key}\` — ${description}`);
  }
  return lines.join('\n');
}

function isPlainObject(value: unknown): boolean {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function stripCodeFence(text: string): string {
  const fence = text.match(/^```(?:json)?\s*\n?([\s\S]*?)\n?```$/);
  return fence ? fence[1].trim() : text;
}

function dropTrailingComma(out: string): string {
  return out.replace(/,(\s*)$/, '$1');
}

// Scan the balanced JSON value rooted at `start`. Strict pass returns only a
// closed span; repair pass fixes a trailing comma, an unterminated string,
// and unclosed brackets (slc/link.md §Boss-event mapping).
function extractJsonValue(
  text: string,
  start: number,
  repair: boolean,
): string | undefined {
  const stack: string[] = [];
  let out = '';
  let inString = false;
  let escaped = false;
  for (let i = start; i < text.length; i++) {
    const ch = text[i];
    if (inString) {
      out += ch;
      if (escaped) escaped = false;
      else if (ch === '\\') escaped = true;
      else if (ch === '"') inString = false;
      continue;
    }
    if (ch === '"') {
      inString = true;
      out += ch;
      continue;
    }
    if (ch === '{' || ch === '[') {
      stack.push(ch === '{' ? '}' : ']');
      out += ch;
      continue;
    }
    if (ch === '}' || ch === ']') {
      if (repair) out = dropTrailingComma(out);
      out += ch;
      stack.pop();
      if (stack.length === 0) return out;
      continue;
    }
    out += ch;
  }
  if (!repair) return undefined;
  if (inString) out += '"';
  out = dropTrailingComma(out);
  while (stack.length > 0) out += stack.pop();
  return out;
}

// Tolerant JSON recovery shared by the classifier and adjudicator: prefer a
// strict balanced span at the earliest opening brace, then its repair, before
// advancing to a later candidate (slc/link.md §Boss-event mapping).
function parseJudgeJson(raw: string): unknown {
  const fenced = stripCodeFence(raw.trim());
  try {
    return JSON.parse(fenced);
  } catch {
    // Fall through to lenient extraction + repair.
  }
  const starts: number[] = [];
  for (let i = 0; i < fenced.length; i++) {
    const ch = fenced[i];
    if (ch === '{' || ch === '[') starts.push(i);
  }
  let firstValue: { value: unknown } | undefined;
  for (const start of starts) {
    let parsedHere: { value: unknown } | undefined;
    for (const repair of [false, true]) {
      const candidate = extractJsonValue(fenced, start, repair);
      if (candidate === undefined) continue;
      try {
        parsedHere = { value: JSON.parse(candidate) };
      } catch {
        continue;
      }
      break;
    }
    if (parsedHere === undefined) continue;
    if (isPlainObject(parsedHere.value)) return parsedHere.value;
    if (firstValue === undefined) firstValue = parsedHere;
  }
  if (firstValue !== undefined) return firstValue.value;
  throw new Error('adjudicate: judge response is not valid JSON');
}

type JudgePurpose = 'boss-input-classification' | 'player-output-adjudication';

interface RuntimeBoundaryCalls {
  callPlayer(
    input: PlayerInput,
    playerId: string,
    prompt: string,
    signal: AbortSignal,
  ): Promise<PlayerResult>;
  callJudge(
    purpose: JudgePurpose,
    stateId: string | undefined,
    prompt: string,
    signal: AbortSignal,
  ): Promise<string>;
}

// LLM-judge adjudicator (slc/link.md §Captain adjudication). Coerces the
// player's finalText into one of the state's declared guards, extracts every
// required payload field from the judge reply, and fails loudly (throws) on a
// missing JSON object, an undeclared guard, or a missing required field.
async function adjudicate(
  input: PlayerInput,
  finalText: string,
  ports: PlaybookPorts,
  signal: AbortSignal,
  boundary?: RuntimeBoundaryCalls,
): Promise<PlayerOutput> {
  const prompt = buildJudgePrompt(input, finalText);
  const raw = boundary
    ? await boundary.callJudge(
        'player-output-adjudication',
        input.stateId,
        prompt,
        signal,
      )
    : await ports.callJudge(prompt, signal);
  const parsed = parseJudgeJson(raw);
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    throw new Error('adjudicate: judge response is not a JSON object');
  }
  const obj = parsed as Record<string, unknown>;
  const guard = obj.guard;
  if (typeof guard !== 'string') {
    throw new Error('adjudicate: judge response missing string "guard" field');
  }
  if (!Object.prototype.hasOwnProperty.call(input.result, guard)) {
    throw new Error(
      `adjudicate: unknown guard "${guard}" — declared guards: ${Object.keys(
        input.result,
      ).join(', ')}`,
    );
  }
  for (const field of extractRequiredFields(input.result[guard])) {
    if (typeof obj[field] !== 'string') {
      if (guard === 'needsBossReply' && field === 'question') {
        throw new Error(BOSS_REPLY_ERRORS.missingQuestion);
      }
      throw new Error(
        `adjudicate: judge response missing required field "${field}" for guard "${guard}"`,
      );
    }
  }
  return obj as unknown as PlayerOutput;
}

function validateBossReplyOutput(
  input: PlayerInput,
  output: PlayerOutput,
): void {
  if (output.guard !== 'needsBossReply') return;
  if (typeof output.question !== 'string') {
    throw new Error(BOSS_REPLY_ERRORS.missingQuestion);
  }
  if (!RESUMABLE_STATE_IDS.has(input.stateId)) {
    throw new Error(BOSS_REPLY_ERRORS.unregisteredState(input.stateId));
  }
}

interface ClassifierState {
  value: unknown;
  context: Record<string, unknown>;
}

function classifierState(snapshotOrState: unknown): ClassifierState {
  if (
    snapshotOrState !== null &&
    typeof snapshotOrState === 'object' &&
    'value' in snapshotOrState
  ) {
    const candidate = snapshotOrState as { value?: unknown; context?: unknown };
    return {
      value: candidate.value,
      context:
        candidate.context !== null &&
        typeof candidate.context === 'object' &&
        !Array.isArray(candidate.context)
          ? (candidate.context as Record<string, unknown>)
          : {},
    };
  }
  return { value: snapshotOrState, context: {} };
}

// Boss-message classifier prompt (slc/link.md §Boss-event mapping). Lists the
// events the current parked state accepts and includes the exact Boss text.
// The runtime-owned textual fields (START.task, BOSS_REPLY.answer) are not
// requested from the judge.
function buildClassifierPrompt(text: string, state: ClassifierState): string {
  const currentState =
    typeof state.value === 'string'
      ? state.value
      : JSON.stringify(state.value ?? null);
  const lines = [
    'Classify the following Boss message into exactly one of these events.',
    'Respond with JSON: { "event": "<TYPE>", "payload": { ...fields } }.',
    'Use { "event": "NO_ACTION", "payload": {} } when no FSM action should be taken.',
    '',
    `Current state: ${currentState}`,
  ];
  const pending = pendingBossQuestionFromContext(state.context);
  if (currentState === 'awaitBossReply') {
    if (pending !== undefined) {
      lines.push(
        `Pending question id: ${pending.questionId}`,
        `Pending asking player: ${pending.player}`,
        `Pending Boss question: ${pending.question}`,
      );
    }
    lines.push(
      '',
      'Events:',
      '- BOSS_REPLY: payload { questionId?: "<pending question id>" } — the acting agent is waiting for Boss to answer its question.',
      '- NO_ACTION: payload {}',
    );
  } else if (currentState === 'failed') {
    lines.push(
      '',
      'Events:',
      '- START: payload {} — restart the workflow from the beginning with this message as the task.',
      '- NO_ACTION: payload {}',
    );
  } else {
    lines.push('', 'Events:', '- NO_ACTION: payload {}');
  }
  lines.push('', 'Boss message:', '```', text, '```');
  return lines.join('\n');
}

// Classify a non-empty Boss turn against the current parked state. Returns the
// FSM event to send, or undefined for no action / unrecoverable reply.
async function classifyBossText(
  text: string,
  ports: PlaybookPorts,
  signal: AbortSignal,
  snapshotOrState: unknown,
  boundary?: RuntimeBoundaryCalls,
): Promise<WorkflowEvent | undefined> {
  const trimmed = text.trim();
  if (trimmed === '') return undefined;
  const state = classifierState(snapshotOrState);
  const stateId = typeof state.value === 'string' ? state.value : undefined;
  const prompt = buildClassifierPrompt(text, state);
  const raw = boundary
    ? await boundary.callJudge(
        'boss-input-classification',
        stateId,
        prompt,
        signal,
      )
    : await ports.callJudge(prompt, signal);
  let parsed: unknown;
  try {
    parsed = parseJudgeJson(raw);
  } catch {
    await ports.emitStatus('Classifier reply was not recoverable JSON');
    return undefined;
  }
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    await ports.emitStatus('Classifier returned a non-object JSON response');
    return undefined;
  }
  const obj = parsed as Record<string, unknown>;
  const eventType = obj.event;
  if (typeof eventType !== 'string') {
    await ports.emitStatus('Classifier did not name an event type');
    return undefined;
  }
  const payload =
    typeof obj.payload === 'object' &&
    obj.payload !== null &&
    !Array.isArray(obj.payload)
      ? (obj.payload as Record<string, unknown>)
      : {};

  switch (eventType) {
    case 'NO_ACTION':
      return undefined;
    case 'START': {
      if (state.value !== 'failed') {
        await ports.emitStatus(
          'Classifier returned START outside a restartable state',
        );
        return undefined;
      }
      return { type: 'START', task: text };
    }
    case 'BOSS_REPLY': {
      if (state.value !== 'awaitBossReply') {
        await ports.emitStatus(
          'Classifier returned BOSS_REPLY outside awaitBossReply',
        );
        return undefined;
      }
      const pending = pendingBossQuestionFromContext(state.context);
      if (pending === undefined) {
        await ports.emitStatus(
          'Classifier returned BOSS_REPLY without a pending question',
        );
        return undefined;
      }
      if (
        payload.questionId !== undefined &&
        typeof payload.questionId !== 'string'
      ) {
        await ports.emitStatus(
          'Classifier supplied a non-string questionId for BOSS_REPLY',
        );
        return undefined;
      }
      if (
        typeof payload.questionId === 'string' &&
        payload.questionId !== pending.questionId
      ) {
        await ports.emitStatus(
          `Classifier supplied unknown questionId for BOSS_REPLY: ${payload.questionId}`,
        );
        return undefined;
      }
      return {
        type: 'BOSS_REPLY',
        answer: text,
        questionId: pending.questionId,
      };
    }
    default:
      await ports.emitStatus(
        `Classifier returned unknown event type: ${eventType}`,
      );
      return undefined;
  }
}

function isAbortFailure(error: unknown, signal: AbortSignal): boolean {
  return (
    signal.aborted &&
    (error === signal.reason || normalizeError(error).name === 'AbortError')
  );
}

function normalizeErrorFull(err: unknown): NormalizedError | undefined {
  if (err === undefined || err === null) return undefined;
  return normalizeError(err);
}

// Detached JSON-safe descriptor of an XState transition event: only the
// declared Boss-union payload fields, a validated actor output, and a
// normalized error member — never XState-internal fields (slc/link.md
// §Session lifecycle).
function normalizeTransitionEvent(event: unknown): JsonValue {
  if (event === null || typeof event !== 'object') {
    return snapshotJsonValue(event ?? null, 'FSM event');
  }
  const e = event as Record<string, unknown>;
  const out: Record<string, JsonValue> = {};
  if (typeof e.type === 'string') out.type = e.type;
  if (typeof e.task === 'string') out.task = e.task;
  if (typeof e.answer === 'string') out.answer = e.answer;
  if (typeof e.questionId === 'string') out.questionId = e.questionId;
  if (e.output !== undefined) {
    out.output = snapshotJsonValue(e.output, 'FSM event output');
  }
  if (e.error !== undefined) {
    out.error = snapshotJsonValue(normalizeError(e.error), 'FSM event error');
  }
  return snapshotJsonValue(out, 'FSM event');
}

export const _internal = {
  composePlayerPrompt,
  resolvePlayerId,
  adjudicate,
  classifyBossText,
  buildClassifierPrompt,
  buildJudgePrompt,
  parseJudgeJson,
  extractRequiredFields,
  pendingBossQuestionFromContext,
  normalizeErrorFull,
  normalizeTransitionEvent,
};

type BossSettlementOutcome =
  | 'no-action'
  | 'quiescent'
  | 'failed'
  | 'terminal'
  | 'aborted';

interface TracePosition {
  turnId?: number;
  callId?: string;
}

interface ScheduledStatus {
  message: string;
  data?: JsonValue;
}

export default function createPlaybookRuntime(
  options: WorkflowPlaybookOptions,
): PlaybookRuntime {
  const boundOptions = snapshotWorkflowOptions(options);
  const machineInput: WorkflowInput =
    boundOptions.task !== undefined ? { task: boundOptions.task } : {};
  const scriptCwd = boundOptions.cwd;

  let actor: ReturnType<typeof createActor> | undefined;
  let session: PlaybookSession | undefined;
  let initialized = false;
  let initInFlight: Promise<void> | undefined;
  let disposalPromise: Promise<void> | undefined;
  let disposed = false;
  let savedPorts: PlaybookPorts | undefined;
  let runtimePorts: PlaybookPorts | undefined;
  let activeSignal: AbortSignal | undefined;
  let activeTurnId: number | undefined;
  let controlPlaneError: unknown;
  let priorState: PlaybookState | undefined;
  let suppressInspectionEmissions = false;

  let traceSequence = 0;
  let turnSequence = 0;
  let judgeCallSequence = 0;
  let playerCallSequence = 0;
  const playerResumeTokens = new Map<string, string>();
  const activePlayerIds = new Set<string>();
  const judgeQueue = new PQueue({ concurrency: 1 });
  const emissionQueue = new PQueue({ concurrency: 1 });
  const activeEmissionCalls = new Set<Promise<void>>();
  let emissionFailure: unknown;

  function enqueueEmission(fn: () => Promise<void>): Promise<void> {
    const queued = emissionQueue.add(fn).then(() => undefined);
    activeEmissionCalls.add(queued);
    void queued.then(
      () => activeEmissionCalls.delete(queued),
      (error: unknown) => {
        activeEmissionCalls.delete(queued);
        emissionFailure ??= error;
      },
    );
    return queued;
  }

  async function drainEmissions(): Promise<void> {
    while (true) {
      const active = [...activeEmissionCalls];
      if (active.length > 0) await Promise.allSettled(active);
      await emissionQueue.onIdle();
      if (
        activeEmissionCalls.size === 0 &&
        emissionQueue.size === 0 &&
        emissionQueue.pending === 0
      ) {
        break;
      }
    }
    if (emissionFailure !== undefined) {
      const error = emissionFailure;
      emissionFailure = undefined;
      throw error;
    }
  }

  function requireSession(): PlaybookSession {
    if (!session) {
      throw new Error('createPlaybookRuntime: init must be called first');
    }
    return session;
  }

  function requireHostPorts(): PlaybookPorts {
    if (!savedPorts) {
      throw new Error('createPlaybookRuntime: init must be called first');
    }
    return savedPorts;
  }

  function stateIdentity(stateId: string | undefined): { stateId?: string } {
    return stateId === undefined ? {} : { stateId };
  }

  function createTraceEvent(
    type: PlaybookTraceType,
    payload: unknown,
    position: TracePosition = {},
  ): PlaybookTraceEvent {
    const currentSession = requireSession();
    const safePayload = snapshotJsonValue(payload, `trace ${type} payload`);
    return {
      schemaVersion: 2,
      sessionId: currentSession.sessionId,
      playbookId: currentSession.playbookId,
      rootSessionId: currentSession.rootSessionId,
      ...(currentSession.parentSessionId !== undefined
        ? { parentSessionId: currentSession.parentSessionId }
        : {}),
      ...(currentSession.parentCallId !== undefined
        ? { parentCallId: currentSession.parentCallId }
        : {}),
      depth: currentSession.depth,
      sequence: ++traceSequence,
      timestamp: Date.now(),
      type,
      ...(position.turnId !== undefined ? { turnId: position.turnId } : {}),
      ...(position.callId !== undefined ? { callId: position.callId } : {}),
      payload: safePayload,
    };
  }

  function emitTrace(
    type: PlaybookTraceType,
    payload: unknown,
    position: TracePosition = {},
  ): Promise<void> {
    const currentSession = requireSession();
    const event = createTraceEvent(type, payload, position);
    return enqueueEmission(() =>
      currentSession.ports.emitTelemetry({
        topic: 'playbook.trace',
        payload: event,
      }),
    );
  }

  function currentState(): PlaybookState {
    if (!actor) {
      throw new Error('createPlaybookRuntime: actor is not initialized');
    }
    return normalizePlaybookSnapshot(actor.getSnapshot());
  }

  function stateTracePayload(state = currentState()): Record<string, unknown> {
    return { state, ...stateIdentity(state.stateId) };
  }

  function createRuntimePorts(hostPorts: PlaybookPorts): PlaybookPorts {
    return {
      callPlayer: (playerId, prompt, signal, callOptions) =>
        hostPorts.callPlayer(playerId, prompt, signal, callOptions),
      callCaptain: (prompt, signal, callOptions) =>
        hostPorts.callCaptain(prompt, signal, callOptions),
      callJudge: (prompt, signal) => hostPorts.callJudge(prompt, signal),
      callPlaybook: (request, signal) =>
        hostPorts.callPlaybook(request, signal),
      emitStatus: (message, data) => {
        const descriptor = actor ? currentState() : undefined;
        const safeData =
          data === undefined
            ? undefined
            : snapshotJsonValue(data, 'status data');
        const trace = createTraceEvent(
          'status.emitted',
          {
            message,
            ...(safeData !== undefined ? { data: safeData } : {}),
            ...(descriptor !== undefined
              ? { state: descriptor, ...stateIdentity(descriptor.stateId) }
              : {}),
          },
          activeTurnId !== undefined ? { turnId: activeTurnId } : {},
        );
        return enqueueEmission(async () => {
          await hostPorts.emitTelemetry({
            topic: 'playbook.trace',
            payload: trace,
          });
          await hostPorts.emitStatus(message, safeData);
        });
      },
      emitTelemetry: (event) => {
        if (typeof event.topic !== 'string' || event.topic.length === 0) {
          throw new TypeError('telemetry topic must be a non-empty string');
        }
        const payload = snapshotJsonValue(event.payload, 'telemetry payload');
        return enqueueEmission(() =>
          hostPorts.emitTelemetry({ topic: event.topic, payload }),
        );
      },
    };
  }

  async function emitCallStarted(
    startedType: 'player.call.started' | 'judge.call.started',
    finishedType: 'player.call.finished' | 'judge.call.finished',
    identity: Record<string, unknown>,
    position: TracePosition,
  ): Promise<void> {
    try {
      await emitTrace(startedType, identity, position);
    } catch (error) {
      controlPlaneError ??= error;
      try {
        await emitTrace(
          finishedType,
          { ...identity, status: 'error', error: normalizeError(error) },
          position,
        );
      } catch {
        // Preserve the start failure after one best-effort finish attempt.
      }
      throw error;
    }
  }

  const boundary: RuntimeBoundaryCalls = {
    async callPlayer(input, playerId, prompt, signal): Promise<PlayerResult> {
      await drainEmissions();
      const turnId = activeTurnId;
      const callId = `player-${++playerCallSequence}`;
      const resume = playerResumeTokens.get(playerId) ?? false;
      const identity = {
        purpose: 'captain' as const,
        ...stateIdentity(input.stateId),
        sourceItem: input.sourceItem,
        playerId,
        resume,
      };
      const position: TracePosition = {
        ...(turnId !== undefined ? { turnId } : {}),
        callId,
      };

      if (activePlayerIds.has(playerId)) {
        const error = new Error(
          `simultaneous calls to resolved player ${playerId} are not allowed`,
        );
        await emitCallStarted(
          'player.call.started',
          'player.call.finished',
          { ...identity, prompt },
          position,
        );
        await emitTrace(
          'player.call.finished',
          { ...identity, status: 'error', error: normalizeError(error) },
          position,
        );
        throw error;
      }
      activePlayerIds.add(playerId);

      try {
        await emitTrace(
          'player.call.started',
          { ...identity, prompt },
          position,
        );

        let rawResult: unknown;
        try {
          rawResult = await requireHostPorts().callPlayer(
            playerId,
            prompt,
            signal,
            {
              resume,
            },
          );
          signal.throwIfAborted();
        } catch (error) {
          if (!signal.aborted) controlPlaneError ??= error;
          try {
            await emitTrace(
              'player.call.finished',
              {
                ...identity,
                status: signal.aborted ? 'aborted' : 'error',
                error: normalizeError(error),
              },
              position,
            );
          } catch {
            // The original port rejection remains authoritative.
          }
          throw error;
        }

        let result: PlayerResult;
        try {
          result = validatePlayerResult(rawResult);
        } catch (error) {
          if (!signal.aborted) controlPlaneError ??= error;
          try {
            await emitTrace(
              'player.call.finished',
              { ...identity, status: 'error', error: normalizeError(error) },
              position,
            );
          } catch {
            // The malformed host result remains authoritative.
          }
          throw error;
        }

        if (
          typeof result.resumeToken === 'string' &&
          result.resumeToken.trim().length > 0
        ) {
          playerResumeTokens.set(playerId, result.resumeToken);
        } else {
          playerResumeTokens.delete(playerId);
        }

        await emitTrace(
          'player.call.finished',
          {
            ...identity,
            status: result.status,
            ...(result.finalText !== undefined
              ? { finalText: result.finalText }
              : {}),
            ...(result.error !== undefined
              ? { error: normalizeError(result.error) }
              : {}),
            ...(result.resumeToken !== undefined
              ? { resumeToken: result.resumeToken }
              : {}),
          },
          position,
        );
        return result;
      } finally {
        activePlayerIds.delete(playerId);
      }
    },

    async callJudge(purpose, stateId, prompt, signal): Promise<string> {
      return judgeQueue.add(async () => {
        signal.throwIfAborted();
        await drainEmissions();
        signal.throwIfAborted();
        const turnId = activeTurnId;
        const callId = `judge-${++judgeCallSequence}`;
        const identity = { purpose, ...stateIdentity(stateId) };
        const position: TracePosition = {
          ...(turnId !== undefined ? { turnId } : {}),
          callId,
        };

        await emitCallStarted(
          'judge.call.started',
          'judge.call.finished',
          { ...identity, prompt },
          position,
        );
        let reply: unknown;
        try {
          reply = await requireHostPorts().callJudge(prompt, signal);
          signal.throwIfAborted();
        } catch (error) {
          if (!isAbortFailure(error, signal)) controlPlaneError ??= error;
          await emitTrace(
            'judge.call.finished',
            {
              ...identity,
              status: signal.aborted ? 'aborted' : 'error',
              error: normalizeError(error),
            },
            position,
          );
          throw error;
        }
        if (typeof reply !== 'string') {
          const error = new TypeError('judge reply must be a string');
          controlPlaneError ??= error;
          await emitTrace(
            'judge.call.finished',
            { ...identity, status: 'error', error: normalizeError(error) },
            position,
          );
          throw error;
        }
        await emitTrace(
          'judge.call.finished',
          { ...identity, status: 'ok', reply },
          position,
        );
        return reply;
      }) as Promise<string>;
    },
  };

  // Delegated-player actor. Resolve the player id, compose the prompt, call
  // the host player, then adjudicate the finalText into an FSM guard. A
  // non-`ok` result or missing finalText throws so XState routes via onError.
  function playerActor() {
    return fromPromise<PlayerOutput, PlayerInput>(async ({ input, signal }) => {
      await drainEmissions();
      const active = combineAbortSignals(signal, activeSignal);
      const playerId = resolvePlayerId(input);
      const prompt = composePlayerPrompt(input);
      const result = await boundary.callPlayer(input, playerId, prompt, active);
      if (result.status !== 'ok') {
        throw new Error(
          result.error ?? `playerActor: callPlayer status "${result.status}"`,
        );
      }
      if (result.finalText === undefined) {
        throw new Error(
          'playerActor: callPlayer returned status=ok with no finalText',
        );
      }
      try {
        const output = await adjudicate(
          input,
          result.finalText,
          runtimePorts ?? requireHostPorts(),
          active,
          boundary,
        );
        validateBossReplyOutput(input, output);
        return output;
      } catch (error) {
        if (!activeSignal?.aborted) controlPlaneError ??= error;
        throw error;
      }
    });
  }

  // Deterministic script actor (slc/link.md §Script execution). Runs
  // `input.command` through `sh -c`, resolves the declared guard mechanically
  // from the exit status, and emits one status + one `playbook.script`
  // telemetry event. No agent call, no adjudication, no `*.call.*` trace.
  function scriptActor() {
    return fromPromise<ScriptOutput, ScriptInput>(async ({ input, signal }) => {
      await drainEmissions();
      const active = combineAbortSignals(signal, activeSignal);
      const guards = Object.keys(input.result);
      const okGuard = guards[0];
      const failedGuard = guards[1];
      const cwd = scriptCwd ?? process.cwd();
      const ports = runtimePorts ?? requireHostPorts();

      const exitStatus = await new Promise<number>((resolve, reject) => {
        let child: ReturnType<typeof spawn>;
        try {
          child = spawn('sh', ['-c', input.command], { cwd, stdio: 'ignore' });
        } catch (error) {
          reject(error);
          return;
        }
        const onAbort = () => {
          child.kill('SIGTERM');
          reject(active.reason ?? new Error('script aborted'));
        };
        if (active.aborted) {
          onAbort();
          return;
        }
        active.addEventListener('abort', onAbort, { once: true });
        child.on('error', (error) => {
          active.removeEventListener('abort', onAbort);
          reject(error);
        });
        child.on('close', (code) => {
          active.removeEventListener('abort', onAbort);
          resolve(typeof code === 'number' ? code : 1);
        });
      });

      await ports.emitStatus(
        `Executed script for ${input.stateId} (exit ${exitStatus}).`,
      );
      await ports.emitTelemetry({
        topic: 'playbook.script',
        payload: {
          stateId: input.stateId,
          sourceItem: input.sourceItem,
          exitStatus,
        },
      });

      if (exitStatus === 0) {
        return { guard: okGuard, exitStatus: 0 } as ScriptOutput;
      }
      return { guard: failedGuard, exitStatus } as ScriptOutput;
    });
  }

  function structuredStateTelemetryPayload(
    previousState: PlaybookState | undefined,
    state: PlaybookState,
    event: unknown,
    context: Record<string, unknown>,
  ): JsonValue {
    const payload: Record<string, unknown> = {
      from: previousState?.value ?? null,
      to: state.value,
      event: normalizeTransitionEvent(event),
      previousState: previousState ?? null,
      state,
    };
    if (state.stateId === 'awaitBossReply') {
      const pending = pendingBossQuestionFromContext(context);
      if (pending !== undefined) payload.pendingBossQuestion = pending;
    }
    if (state.stateId === 'failed') {
      const lastError = normalizeErrorFull(context.lastError);
      if (lastError !== undefined) payload.lastError = lastError;
    }
    return snapshotJsonValue(payload, 'FSM telemetry payload');
  }

  function statusesForState(
    state: PlaybookState,
    context: Record<string, unknown>,
  ): ScheduledStatus[] {
    const stateId = state.stateId;
    if (stateId === undefined || SUPPRESSED_ENTRY_STATES.has(stateId))
      return [];
    if (stateId === 'awaitBossReply') {
      const pending = pendingBossQuestionFromContext(context);
      const message =
        pending === undefined
          ? 'Awaiting Boss reply.'
          : `${pending.player} asks: ${pending.question}`;
      return [{ message }];
    }
    if (stateId === 'failed') {
      const lastError = normalizeErrorFull(context.lastError);
      return [
        {
          message: 'Workflow failed; awaiting Boss recovery.',
          ...(lastError === undefined
            ? {}
            : { data: snapshotJsonValue({ lastError }, 'failed status data') }),
        },
      ];
    }
    return [{ message: `Entered ${stateId}.` }];
  }

  function enqueueTransitionEmission(
    payload: JsonValue,
    state: PlaybookState,
    statuses: readonly ScheduledStatus[],
    position: TracePosition,
  ): void {
    const currentSession = requireSession();
    const transitionTrace = createTraceEvent(
      'fsm.transition',
      payload,
      position,
    );
    const statusEmissions = statuses.map(({ message, data }) => ({
      message,
      data,
      trace: createTraceEvent(
        'status.emitted',
        {
          message,
          ...(data === undefined ? {} : { data }),
          state,
          ...stateIdentity(state.stateId),
        },
        position,
      ),
    }));
    void enqueueEmission(async () => {
      await currentSession.ports.emitTelemetry({
        topic: 'playbook.trace',
        payload: transitionTrace,
      });
      await currentSession.ports.emitTelemetry({
        topic: 'playbook.fsm.state',
        payload,
      });
      for (const status of statusEmissions) {
        await currentSession.ports.emitTelemetry({
          topic: 'playbook.trace',
          payload: status.trace,
        });
        await currentSession.ports.emitStatus(status.message, status.data);
      }
    }).catch(() => undefined);
  }

  function latchInspectionError(error: unknown): void {
    if (activeSignal !== undefined) controlPlaneError ??= error;
    else emissionFailure ??= error;
  }

  function buildActor(): ReturnType<typeof createActor> {
    priorState = undefined;
    let builtActor: ReturnType<typeof createActor>;
    builtActor = createActor(
      workflowMachine.provide({
        actors: {
          player: playerActor(),
          script: scriptActor(),
        },
      }),
      {
        input: machineInput,
        inspect: (inspectionEvent: InspectionEvent) => {
          if (inspectionEvent.type !== '@xstate.snapshot') return;
          if (inspectionEvent.actorRef !== builtActor) return;
          if (suppressInspectionEmissions) return;
          try {
            const snap = inspectionEvent.snapshot as SnapshotFrom<
              typeof workflowMachine
            >;
            const state = normalizePlaybookSnapshot(snap);
            const context = (snap.context ?? {}) as unknown as Record<
              string,
              unknown
            >;
            const payload = structuredStateTelemetryPayload(
              priorState,
              state,
              inspectionEvent.event,
              context,
            );
            const statuses = statusesForState(state, context);
            enqueueTransitionEmission(
              payload,
              state,
              statuses,
              activeTurnId === undefined ? {} : { turnId: activeTurnId },
            );
            priorState = state;
          } catch (error) {
            latchInspectionError(error);
          }
        },
      },
    );
    return builtActor;
  }

  function runResultFor(
    outcome: BossSettlementOutcome,
    error?: unknown,
  ): PlaybookRunResult {
    const state = currentState();
    if (outcome === 'quiescent' || outcome === 'no-action') {
      return { outcome, state };
    }
    if (outcome === 'terminal') {
      const output = (actor?.getSnapshot() as { output?: unknown } | undefined)
        ?.output;
      if (output !== undefined) {
        return {
          outcome,
          state,
          output: snapshotJsonValue(output, 'terminal playbook output'),
        };
      }
      return { outcome, state };
    }
    const failure =
      error ??
      (outcome === 'failed'
        ? (actor?.getSnapshot() as { context?: { lastError?: unknown } })
            ?.context?.lastError
        : outcome === 'aborted'
          ? activeSignal?.reason
          : undefined);
    return {
      outcome,
      state,
      ...(failure !== undefined ? { error: normalizeError(failure) } : {}),
    };
  }

  function settledOutcome(signal: AbortSignal): BossSettlementOutcome {
    if (signal.aborted) return 'aborted';
    const state = currentState();
    if (state.status === 'error') {
      const actorError = (
        actor?.getSnapshot() as { error?: unknown } | undefined
      )?.error;
      throw actorError ?? new Error('workflow actor entered error status');
    }
    if (state.status === 'done') return 'terminal';
    if (state.stateId === 'failed') return 'failed';
    return 'quiescent';
  }

  function settlementTracePayload(
    result: PlaybookRunResult,
  ): Record<string, unknown> {
    return { ...result, ...stateIdentity(result.state.stateId) };
  }

  async function cleanupFailedStart(cause: unknown): Promise<void> {
    let finalState: PlaybookState | undefined;
    if (actor) {
      try {
        finalState = currentState();
      } catch {
        // A state that cannot even normalize has no disposal descriptor.
      }
    }
    suppressInspectionEmissions = true;
    try {
      actor?.stop();
    } catch {
      // Preserve the original startup failure.
    }
    try {
      await judgeQueue.onIdle();
      await drainEmissions();
    } catch {
      // Preserve the original startup failure.
    }
    try {
      await emitTrace(
        'session.disposed',
        finalState === undefined
          ? {}
          : { state: finalState, ...stateIdentity(finalState.stateId) },
      );
      await drainEmissions();
    } catch {
      // The session-start error remains authoritative.
    }
    void cause;
    playerResumeTokens.clear();
    activePlayerIds.clear();
    activeEmissionCalls.clear();
    emissionQueue.clear();
    judgeQueue.clear();
    actor = undefined;
    session = undefined;
    savedPorts = undefined;
    runtimePorts = undefined;
    activeSignal = undefined;
    activeTurnId = undefined;
    controlPlaneError = undefined;
    emissionFailure = undefined;
    priorState = undefined;
    suppressInspectionEmissions = false;
    initialized = false;
    traceSequence = 0;
    turnSequence = 0;
    judgeCallSequence = 0;
    playerCallSequence = 0;
  }

  const runtime = {
    async init(nextSession: PlaybookSession): Promise<void> {
      if (initialized || disposed || disposalPromise !== undefined) {
        throw new Error('createPlaybookRuntime.init: already initialized');
      }
      const boundSession = snapshotPlaybookSession(nextSession);
      initialized = true;
      let finishInitialization!: () => void;
      const initialization = new Promise<void>((resolve) => {
        finishInitialization = resolve;
      });
      initInFlight = initialization;
      const initTask = (async () => {
        session = boundSession;
        savedPorts = boundSession.ports;
        runtimePorts = createRuntimePorts(boundSession.ports);
        suppressInspectionEmissions = false;
        actor = buildActor();
        await emitTrace('session.started', stateTracePayload());
        actor.start();
        await drainEmissions();
      })();
      try {
        await initTask;
      } catch (error) {
        await cleanupFailedStart(error);
        throw error;
      } finally {
        finishInitialization();
        if (initInFlight === initialization) initInFlight = undefined;
      }
    },

    async handleBossInput({
      text,
      signal,
    }: {
      text: string;
      signal: AbortSignal;
    }): Promise<PlaybookRunResult> {
      if (!actor || !savedPorts || !runtimePorts) {
        throw new Error(
          'createPlaybookRuntime.handleBossInput: init must be called first',
        );
      }
      if (disposed || disposalPromise !== undefined) {
        throw new Error(
          'createPlaybookRuntime.handleBossInput: runtime is disposing or disposed',
        );
      }
      if (activeSignal !== undefined) {
        throw new Error(
          'createPlaybookRuntime.handleBossInput: another runtime turn is active',
        );
      }
      const ports = runtimePorts;
      const turnId = ++turnSequence;
      activeTurnId = turnId;
      activeSignal = signal;
      controlPlaneError = undefined;
      let result: PlaybookRunResult | undefined;
      let operationError: unknown;
      try {
        await emitTrace('boss.input.received', { text }, { turnId });
        const trimmed = text.trim();
        let event: WorkflowEvent | undefined;
        if (trimmed !== '') {
          const snapshot = actor.getSnapshot();
          const stateId = normalizePlaybookSnapshot(snapshot).stateId;
          const terminal = snapshot.status === 'done';
          if (stateId === 'ready' || terminal) {
            event = { type: 'START', task: text };
          } else {
            event = await classifyBossText(
              text,
              ports,
              signal,
              snapshot,
              boundary,
            );
          }
        }
        if (event === undefined) {
          result = runResultFor('no-action');
        } else {
          if (actor.getSnapshot().status === 'done') {
            actor.stop();
            actor = buildActor();
            actor.start();
          }
          actor.send(event);
          await waitForPlaybookQuiescence(actor);
          if (controlPlaneError !== undefined) throw controlPlaneError;
          result = runResultFor(settledOutcome(signal));
        }
      } catch (error) {
        operationError = error;
      }

      let drainError: unknown;
      try {
        await drainEmissions();
      } catch (error) {
        drainError = error;
      }
      const latchedControlError = controlPlaneError;
      const primaryError = latchedControlError ?? drainError ?? operationError;
      const abortError =
        latchedControlError === undefined &&
        drainError === undefined &&
        operationError !== undefined &&
        isAbortFailure(operationError, signal);
      const settlementResult =
        primaryError === undefined
          ? (result ?? runResultFor('no-action'))
          : runResultFor(abortError ? 'aborted' : 'failed', primaryError);

      let settlementEmissionError: unknown;
      try {
        await emitTrace(
          'boss.input.settled',
          settlementTracePayload(settlementResult),
          { turnId },
        );
        await drainEmissions();
      } catch (error) {
        settlementEmissionError = error;
      }
      const failure =
        latchedControlError ??
        drainError ??
        (abortError
          ? (settlementEmissionError ?? operationError)
          : (operationError ?? settlementEmissionError));
      activeSignal = undefined;
      activeTurnId = undefined;
      controlPlaneError = undefined;

      if (
        failure !== undefined &&
        !(abortError && settlementEmissionError === undefined)
      ) {
        throw failure;
      }
      return settlementResult;
    },

    // The FSM declares no nested `playbook` actor, so no call is ever pending;
    // any resume names an unknown call id.
    resumePlaybookCall(input: {
      callId: string;
      result: PlaybookCallResult;
      signal: AbortSignal;
    }): Promise<PlaybookRunResult> {
      return Promise.reject(
        new Error(
          `createPlaybookRuntime.resumePlaybookCall: no pending playbook call ${input.callId}`,
        ),
      );
    },

    dispose(): Promise<void> {
      if (disposalPromise !== undefined) return disposalPromise;
      if (disposed) return Promise.resolve();
      if (activeSignal !== undefined) {
        return Promise.reject(
          new Error(
            'createPlaybookRuntime.dispose: cannot dispose during an active runtime boundary',
          ),
        );
      }
      const task = (async (): Promise<void> => {
        const failures: unknown[] = [];
        try {
          if (initInFlight !== undefined) {
            try {
              await initInFlight;
            } catch {
              // Dispose still releases whatever an unsuccessful init bound.
            }
          }
          const finalState = actor ? currentState() : undefined;
          if (actor) actor.stop();
          try {
            await drainEmissions();
          } catch (error) {
            failures.push(error);
          }
          if (session !== undefined) {
            try {
              await emitTrace(
                'session.disposed',
                finalState === undefined
                  ? {}
                  : { state: finalState, ...stateIdentity(finalState.stateId) },
              );
              await drainEmissions();
            } catch (error) {
              failures.push(error);
            }
          }
        } finally {
          playerResumeTokens.clear();
          activePlayerIds.clear();
          activeEmissionCalls.clear();
          emissionQueue.clear();
          judgeQueue.clear();
          actor = undefined;
          activeSignal = undefined;
          activeTurnId = undefined;
          controlPlaneError = undefined;
          emissionFailure = undefined;
          savedPorts = undefined;
          runtimePorts = undefined;
          session = undefined;
          disposed = true;
        }
        if (failures.length === 1) throw failures[0];
        if (failures.length > 1) {
          throw new AggregateError(
            failures,
            'playbook runtime disposal failed',
          );
        }
      })();
      disposalPromise = task;
      return task;
    },
  };

  return runtime as PlaybookRuntime;
}
