// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by slc (DR-014): the registry entry exposing the compiled
// playbook to `playbook run`. Derived deterministically from the compiled
// bundle; recompiling regenerates it. The role-binding boundary (DR-017)
// hands the host's `callPlayer` port only declared role ids.

import createPlaybookRuntime from './workflow.playbook/workflow.playbook.ts';

type RuntimeOptions = NonNullable<Parameters<typeof createPlaybookRuntime>[0]>;

const ALLOWED_OPTION_KEYS: readonly string[] = ['cwd'];

const REQUIRED_ROLE_IDS: readonly string[] = ['Coder', 'Reviewer'];

const ROLE_ID_BY_RESOLVED: ReadonlyMap<string, string> = new Map(
  REQUIRED_ROLE_IDS.map((id): [string, string] => [id.toLowerCase(), id]),
);

function bindRoleIds(session: unknown): unknown {
  if (typeof session !== 'object' || session === null) return session;
  const ports = (session as { ports?: unknown }).ports;
  if (typeof ports !== 'object' || ports === null) return session;
  const callPlayer = (ports as Record<string, unknown>).callPlayer;
  if (typeof callPlayer !== 'function') return session;
  return {
    ...session,
    ports: {
      ...(ports as Record<string, unknown>),
      callPlayer: (playerId: unknown, ...rest: unknown[]) =>
        (callPlayer as (...args: unknown[]) => unknown).call(
          ports,
          typeof playerId === 'string'
            ? (ROLE_ID_BY_RESOLVED.get(playerId) ?? playerId)
            : playerId,
          ...rest,
        ),
    },
  };
}

function withRoleBinding<T extends object>(runtime: T): T {
  return new Proxy(runtime, {
    get(target, property, receiver) {
      const value = Reflect.get(target, property, receiver);
      if (
        (property === 'init' || property === 'restore') &&
        typeof value === 'function'
      ) {
        return (session: unknown, ...rest: unknown[]) =>
          (value as (...args: unknown[]) => unknown).call(
            target,
            bindRoleIds(session),
            ...rest,
          );
      }
      return value;
    },
  });
}

function validateOptions(value: unknown): RuntimeOptions {
  if (value === undefined) return {};
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new Error('playbook options must be an object');
  }
  const options: Record<string, string> = {};
  for (const [key, option] of Object.entries(value)) {
    if (!ALLOWED_OPTION_KEYS.includes(key)) {
      throw new Error(
        `unknown option "${key}" (allowed: ${ALLOWED_OPTION_KEYS.join(', ') || 'none'})`,
      );
    }
    if (typeof option !== 'string' || option === '') {
      throw new Error(`option "${key}" must be a non-empty string`);
    }
    options[key] = option;
  }
  return options as RuntimeOptions;
}

const entry = {
  id: 'workflow',
  command: 'workflow',
  intent:
    'Two-Agent Task Workflow — Use two agents to carry out the input task.',
  requiredRoleIds: [...REQUIRED_ROLE_IDS],
  validateOptions,
  createRuntime(options: { captainOptions?: unknown }) {
    const validated = validateOptions(options.captainOptions);
    return withRoleBinding(
      createPlaybookRuntime({
        ...validated,
        cwd: validated.cwd ?? process.cwd(),
      }),
    );
  },
};

export default entry;
