// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by slc (DR-014): the registry entry exposing the compiled
// playbook to `playbook run`. Derived deterministically from the compiled
// bundle; recompiling regenerates it. `requiredRoleIds` are the canonical
// lowercase local role ids the compiled machine's delegated states name
// (DR-024).

import createPlaybookRuntime from './workflow.playbook/workflow.playbook.ts';

type FactoryInput = NonNullable<Parameters<typeof createPlaybookRuntime>[0]>;
type RuntimeOptions = FactoryInput['configuredOptions'];
type HostCapabilities = FactoryInput['hostCapabilities'];

const ALLOWED_OPTION_KEYS: readonly string[] = ['cwd'];

const REQUIRED_ROLE_IDS: readonly string[] = ['coder', 'reviewer'];

function validateOptions(value: unknown): RuntimeOptions {
  if (value === undefined) return {};
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new Error('playbook options must be an object');
  }
  const options: Record<string, string> = {};
  for (const [key, option] of Object.entries(value)) {
    if (!ALLOWED_OPTION_KEYS.includes(key)) {
      throw new Error(
        `unknown option "${key}" (allowed: ${ALLOWED_OPTION_KEYS.join(', ') || 'none'})`,
      );
    }
    if (typeof option !== 'string' || option === '') {
      throw new Error(`option "${key}" must be a non-empty string`);
    }
    options[key] = option;
  }
  return options as RuntimeOptions;
}

const entry = {
  id: 'workflow',
  command: 'workflow',
  intent: 'Two-Agent Change-and-Review Workflow — Roles:',
  artifactSchema: 3,
  runtimeProfile: 'composed-v3',
  concurrentRoleSets: [] as readonly (readonly string[])[],
  requiredRoleIds: [...REQUIRED_ROLE_IDS],
  validateOptions,
  createRuntime(
    options: { captainOptions?: unknown },
    hostCapabilities: HostCapabilities,
  ) {
    const validated = validateOptions(options.captainOptions);
    return createPlaybookRuntime({
      configuredOptions: {
        ...validated,
        cwd: validated.cwd ?? process.cwd(),
      },
      hostCapabilities,
    });
  },
};

export default entry;
