// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Linked playbook runtime for the FSM-to-Runtime Linking phase.
// Generated by the slc link phase; reproducible from these linker inputs:
//   FSM artifact:          ./link.fsm.ts
//   Adjudication strategy: LLM-judge per state (default)
//   Boss-event mapping:    free-text judge classification (default)
//   Link options:          (none)
//
// The FSM declares no `type: 'parallel'` state, so this is the thin
// shared-factory profile: every interpreter behavior ships once in
// `@sublang/playbook/xstate-runtime`.

import {
  createXStatePlaybookRuntime,
  defaultComposeCaptainPrompt,
  type XStatePlaybookRuntimeConstruction,
  type XStatePlaybookRuntimeFactory,
  type XStatePlaybookRuntimeSpecV3,
  type XStateRepositoryCapability,
} from '@sublang/playbook/xstate-runtime';
import type { PlaybookEffectLedgerCapability } from '@sublang/playbook/runtime';

import { linkMachine } from './link.fsm.ts';

/* -------------------------------------------------------------------------
 * Shared contract types, re-exported so consumers share one definition.
 * ---------------------------------------------------------------------- */

export type {
  CaptainCallOptions,
  CaptainResult,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlayerCallOptions,
  PlayerResult,
  PlayerSessionStore,
} from '@sublang/playbook/runtime';

/* -------------------------------------------------------------------------
 * Per-playbook options and live host capabilities
 * ---------------------------------------------------------------------- */

/**
 * Derived from every required FSM input field not supplied by
 * `PlaybookSession` or another linker-owned source. `LinkMachineInput`
 * declares exactly `definition`: the host-owned bytes backing the
 * `<definition>` prompt placeholder. The FSM declares no `script` state, so
 * no `cwd` option is emitted.
 */
export interface PlaybookRuntimeOptions {
  /** Exact bytes of the definition file the transformation request names. */
  readonly definition: string;
}

/** Live schema-3 capabilities this artifact requires from its current host. */
export interface HostCapabilities {
  readonly authority: {
    readonly playbookId: string;
    readonly artifactSchema: 3;
    readonly cwd: string;
    readonly sessionId: string;
    readonly leaseOwnerToken: string;
    readonly canonicalWorktree: {
      readonly worktree: string;
      readonly gitDir: string;
    };
    readonly requiredRoleIds: readonly string[];
    readonly concurrentRoleSets: readonly (readonly string[])[];
  };
  readonly repository: XStateRepositoryCapability;
  readonly effectLedger: PlaybookEffectLedgerCapability;
}

/**
 * Validate and JSON-snapshot the caller's configured options, rejecting
 * undeclared keys and non-conforming values, so the factory binds an
 * immutable options record before constructing any actor.
 */
const snapshotOptions = (value: unknown): PlaybookRuntimeOptions => {
  if (typeof value !== 'object' || value === null) {
    throw new TypeError('link options must be a plain object');
  }
  const prototype = Object.getPrototypeOf(value);
  if (prototype !== Object.prototype && prototype !== null) {
    throw new TypeError('link options must be a plain object');
  }
  for (const key of Reflect.ownKeys(value)) {
    if (key !== 'definition') {
      throw new TypeError(`link options carry undeclared key ${String(key)}`);
    }
  }
  const definition = (value as { definition?: unknown }).definition;
  if (typeof definition !== 'string' || definition.trim().length === 0) {
    throw new TypeError('link option `definition` must be a non-empty string');
  }
  return Object.freeze({ definition });
};

/* -------------------------------------------------------------------------
 * Per-playbook spec: only what the factory cannot read from the FSM itself
 * ---------------------------------------------------------------------- */

const spec: XStatePlaybookRuntimeSpecV3<PlaybookRuntimeOptions> = {
  label: 'link',

  // Compatibility values current at link time. These are literals, not the
  // installed engine's live self-report, so the factory can detect an
  // artifact linked against a different engine.
  compat: { artifactSchema: 3, runtimeAbi: 1 },

  snapshotOptions,

  // The FSM invokes only the `captain` actor, so there is no delegated-player
  // state to name: both maps are explicitly empty.
  outcomeAuthority: { governedPlayerStates: {} },
  roleStates: {},

  // `TRANSFORMATION_REQUEST` is a payload-free entry arm that disappears
  // entirely under TypeScript erasure, so the classifier needs it declared.
  // `BOSS_INTERRUPT`'s closed `targetId` set is derived from the machine's
  // root transition, and `NO_ACTION`/`BOSS_REPLY` are runtime-owned.
  bossEvents: [{ type: 'TRANSFORMATION_REQUEST' }],

  // String payload fields the FSM's Boss union declares.
  transitionEventFields: ['answer', 'questionId', 'targetId'],

  // No result field is annotated as a delegated player's verbatim final text;
  // the direct-Captain `question` field is runtime-injected presentation.
  verbatimPayloadFields: new Set<string>(),

  // Both root final states are authored terminal outcomes of LINK-1, so no
  // terminal outcome leaves the procedure unfinished.
  unfinishedFinalStateIds: new Set<string>(),
};

/* -------------------------------------------------------------------------
 * Factory
 * ---------------------------------------------------------------------- */

const createPlaybookRuntime: XStatePlaybookRuntimeFactory<
  XStatePlaybookRuntimeConstruction<PlaybookRuntimeOptions, HostCapabilities>,
  3
> = createXStatePlaybookRuntime<PlaybookRuntimeOptions, HostCapabilities>(
  linkMachine,
  spec,
);

export default createPlaybookRuntime;

/**
 * Pure helpers verification exercises without a host. Not a public API and
 * not semver-stable. The FSM makes direct-Captain calls and no player calls,
 * so only the Captain composer is exposed; the spec overrides no composer,
 * so this is the shared default the runtime itself uses.
 */
export const _internal = {
  composeCaptainPrompt: defaultComposeCaptainPrompt,
};
