// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by slc/link.md (FSM-to-Runtime linker). Reproducible from the
// linker inputs recorded below; the FSM artifact is not modified and its
// Captain prompts, result keys, and guard semantics are not re-derived.
//
// Source FSM:       ./link.fsm.ts  (extension-bearing sibling specifier so the
//                   module loads without a build step; link.md §Output).
// Player binding:   Captain -> captain
//                   No binding was supplied to the linker, so the default
//                   binding applies (each player to its lowercased name;
//                   link.md §Linker inputs). It is baked in and applied at
//                   every callPlayer site, and additionally exposed for
//                   per-run remapping via `LinkPlaybookOptions.captain`
//                   (link.md §Player binding).
// Alias resolution: none — the FSM declares no composite/alias players, so
//                   `resolvePlayerId` is a deterministic direct lookup in the
//                   recorded binding.
// Boss-event map:   free-text judge classification (default; link.md
//                   §Boss-event mapping).
// Adjudication:     LLM-judge for every state (default; link.md §Captain
//                   adjudication).
// Abort strategy:   natural rejection (link.md §Abort). The single
//                   captain-invoking state `linking` wires
//                   `onError -> failed` (a quiescent sink), so a cancelled
//                   callPlayer that rejects (or resolves with status
//                   'aborted' | 'error', which this runtime converts to a
//                   Captain-actor rejection) is routed through the FSM's own
//                   error wiring to quiescence.
// Contract:         `PlayerResult`, `PlaybookPorts`, `PlaybookRuntime`, and
//                   `PlaybookRuntimeFactory` are imported and re-exported from
//                   the shared type-only module `@sublang/playbook/runtime`,
//                   never redefined (link.md §Output). The dependency runs one
//                   way: this module depends on the contract, never the
//                   reverse.

import { createActor, fromPromise } from 'xstate';

import {
  linkMachine,
  type CaptainInput,
  type CaptainOutput,
  type LinkEvent,
  type LinkInput,
  type PendingBossQuestion,
} from './link.fsm.ts';
import type {
  PlaybookPorts,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlayerResult,
} from '@sublang/playbook/runtime';

// One shared contract definition (link.md §Output): re-export the names this
// module's consumers (host adapters, tests) import, sourced from the shared
// type-only module rather than redefined here.
export type {
  PlayerResult,
  PlaybookPorts,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
};

// ---------------------------------------------------------------------------
// Typed per-playbook options
// ---------------------------------------------------------------------------

// Host-agnostic per-run knobs for this playbook (link.md §PlaybookRuntime
// contract), emitted from the FSM's `LinkInput`. Carries only the optional
// per-run Captain player binding override; the runtime ships with a
// deterministic default binding it applies when this is unset.
export type LinkPlaybookOptions = LinkInput;

// ---------------------------------------------------------------------------
// FSM introspection (read-only; the FSM artifact is never modified)
// ---------------------------------------------------------------------------

// The Boss-originated event names this FSM's `LinkEvent` union declares. The
// classifier maps free-form Boss text onto exactly one of these (plus their
// payloads) or onto no FSM action.
const START_EVENT = 'START_LINK';
const BOSS_INTERRUPT_EVENT = 'BOSS_INTERRUPT';
const BOSS_REPLY_EVENT = 'BOSS_REPLY';

interface RawStateConfig {
  description?: string;
  type?: string;
  invoke?: {
    src?: string;
    input?: (arg: { context: Record<string, unknown> }) => CaptainInput;
  };
  on?: Record<string, unknown>;
}

interface RawMachineConfig {
  id?: string;
  initial?: string;
  states?: Record<string, RawStateConfig>;
  on?: Record<string, unknown>;
}

// The machine's own configuration, read (never mutated) to derive the small
// structural facts the runtime needs: which states invoke Captain, which are
// quiescent, which accept a Boss reply, and which are jumpable targets. Reading
// it keeps this module in lock-step with the FSM instead of hard-coding
// topology the linker would have to re-derive.
const MACHINE_CONFIG = linkMachine.config as unknown as RawMachineConfig;

interface CaptainStateMeta {
  stateId: string;
  player: string;
  sourceItem: string;
  resultKeys: string[];
}

function enumerateCaptainStates(): CaptainStateMeta[] {
  const out: CaptainStateMeta[] = [];
  for (const [stateId, state] of Object.entries(MACHINE_CONFIG.states ?? {})) {
    const inputFn = state.invoke?.input;
    if (state.invoke?.src !== 'captain' || typeof inputFn !== 'function') {
      continue;
    }
    let input: CaptainInput;
    try {
      input = inputFn({ context: {} });
    } catch {
      continue;
    }
    out.push({
      stateId,
      player: input.player,
      sourceItem: input.sourceItem,
      resultKeys: Object.keys(input.result),
    });
  }
  return out;
}

interface InterruptTarget {
  stateId: string;
  description: string;
}

function enumerateInterruptTargets(): InterruptTarget[] {
  const raw = MACHINE_CONFIG.on?.[BOSS_INTERRUPT_EVENT];
  const arms = Array.isArray(raw) ? raw : [];
  const targets: InterruptTarget[] = [];
  const seen = new Set<string>();
  for (const arm of arms) {
    const target = (arm as { target?: unknown }).target;
    if (typeof target !== 'string') continue;
    const stateId = target.replace(/^#/, '');
    if (seen.has(stateId)) continue;
    seen.add(stateId);
    targets.push({
      stateId,
      description: MACHINE_CONFIG.states?.[stateId]?.description ?? '',
    });
  }
  return targets;
}

// A captain-invoking state is registered as resumable when `awaitBossReply`
// carries a BOSS_REPLY arm that targets it; the empty-answer arm targets a
// non-captain sink and is excluded.
function enumerateResumableStateIds(
  captainIds: ReadonlySet<string>,
): Set<string> {
  const ids = new Set<string>();
  for (const state of Object.values(MACHINE_CONFIG.states ?? {})) {
    const raw = state.on?.[BOSS_REPLY_EVENT];
    if (!Array.isArray(raw)) continue;
    for (const arm of raw) {
      const target = (arm as { target?: unknown }).target;
      if (typeof target !== 'string') continue;
      const stateId = target.replace(/^#/, '');
      if (captainIds.has(stateId)) ids.add(stateId);
    }
  }
  return ids;
}

// The quiescent states are those that do not invoke Captain: they take a Boss
// event (or are final) and so end a `handleBossInput` drive (link.md §Session
// lifecycle step 4). The lone captain-invoking state (`linking`) is the only
// non-quiescent one.
function enumerateQuiescentStateIds(
  captainIds: ReadonlySet<string>,
): Set<string> {
  const ids = new Set<string>();
  for (const stateId of Object.keys(MACHINE_CONFIG.states ?? {})) {
    if (!captainIds.has(stateId)) ids.add(stateId);
  }
  return ids;
}

const CAPTAIN_STATES = enumerateCaptainStates();
const CAPTAIN_STATE_IDS: ReadonlySet<string> = new Set(
  CAPTAIN_STATES.map((s) => s.stateId),
);
const STATE_ID_BY_SOURCE_ITEM: ReadonlyMap<string, string> = new Map(
  CAPTAIN_STATES.map((s) => [s.sourceItem, s.stateId] as const),
);
const INTERRUPT_TARGETS = enumerateInterruptTargets();
const INTERRUPT_TARGET_IDS: ReadonlySet<string> = new Set(
  INTERRUPT_TARGETS.map((t) => t.stateId),
);
const RESUMABLE_STATE_IDS = enumerateResumableStateIds(CAPTAIN_STATE_IDS);
const QUIESCENT_STATE_IDS = enumerateQuiescentStateIds(CAPTAIN_STATE_IDS);
const STATE_DESCRIPTIONS: ReadonlyMap<string, string> = new Map(
  Object.entries(MACHINE_CONFIG.states ?? {}).map(
    ([id, s]) => [id, s.description ?? ''] as const,
  ),
);

// ---------------------------------------------------------------------------
// Player binding (link.md §Player binding)
// ---------------------------------------------------------------------------

// The default, baked binding: each declared player to its lowercased name.
// This FSM names exactly one player, `Captain`, so the whole binding is
// `Captain -> captain`. No composite/alias players are declared, so no
// per-source-item alias resolution is required — the binding is a direct
// lookup. The linker invents no identifier beyond this recorded default.
const DEFAULT_PLAYER_BINDING: Readonly<Record<string, string>> = {
  Captain: 'captain',
};

type PlayerBinding = Readonly<Record<string, string>>;

// Build the effective binding: the baked default, with the Captain player id
// overridden when a per-run remapping is supplied via options.
function effectiveBinding(options: LinkPlaybookOptions): PlayerBinding {
  return options.captain !== undefined
    ? { ...DEFAULT_PLAYER_BINDING, Captain: options.captain }
    : DEFAULT_PLAYER_BINDING;
}

// Resolve the opaque `playerId` used at the `callPlayer` site. `input.player`
// keeps its FSM value; resolution decides only the invocation. Deterministic
// and total over the binding: an unmapped player is a linker/FSM mismatch and
// fails loudly rather than inventing an identifier.
function resolvePlayerId(input: CaptainInput, binding: PlayerBinding): string {
  const playerId = binding[input.player];
  if (playerId === undefined) {
    throw new Error(
      `resolvePlayerId: no binding for player "${input.player}" (bound players: ${Object.keys(
        binding,
      ).join(', ')})`,
    );
  }
  return playerId;
}

// ---------------------------------------------------------------------------
// Player-prompt composition (link.md §Player prompt composition)
// ---------------------------------------------------------------------------

// Framework text supplied by the runtime — not part of the GEARS blockquote and
// never present in `invoke.input.prompt`.
const CONTINUATION_PREAMBLE =
  'You previously paused this task to ask Boss a question; Boss has now replied. Continue the same task using the reply below.';
const BOSS_QUESTION_LABEL = 'Boss question:';
const BOSS_REPLY_LABEL = 'Boss reply:';
// The one structured labelled block this FSM exposes on `CaptainInput`.
const BOSS_REQUEST_LABEL = 'Boss request:';

// Compose the actual player prompt from the state's `CaptainInput`. The domain
// prompt body (`input.prompt`) is carried verbatim — never mutated, re-flowed,
// or used to store framework control instructions, and it holds no placeholder
// tokens this FSM populates, so nothing is substituted into it. Structured
// labelled blocks are prepended from typed fields the FSM exposes; the
// continuation preamble and labelled Q&A blocks precede every ordinary block
// and the body on a Boss-reply continuation turn. No player-visible
// Boss-question instruction is injected — Boss-question detection is
// adjudicator-facing (the state's `needsBossReply` result description), not
// prompt text.
function composePlayerPrompt(input: CaptainInput): string {
  const blocks: string[] = [];

  if (
    input.pendingBossQuestion !== undefined &&
    input.bossReply !== undefined
  ) {
    blocks.push(CONTINUATION_PREAMBLE);
    blocks.push(
      `${BOSS_QUESTION_LABEL}\n${input.pendingBossQuestion.question}`,
    );
    blocks.push(`${BOSS_REPLY_LABEL}\n${input.bossReply}`);
  }

  if (input.bossRequest !== undefined) {
    blocks.push(`${BOSS_REQUEST_LABEL}\n${input.bossRequest}`);
  }

  blocks.push(input.prompt);

  return blocks.join('\n\n');
}

// ---------------------------------------------------------------------------
// Judge-reply JSON parsing (shared by classifier and adjudicator)
// ---------------------------------------------------------------------------

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

// Strip a single Markdown code fence wrapping the whole string.
function stripCodeFence(text: string): string {
  const fenced = text.match(/^```(?:json)?\s*\n?([\s\S]*?)\n?```$/);
  return fenced ? fenced[1].trim() : text;
}

// Return the balanced JSON value rooted at `start` (a `{`/`[` index), tracking
// string state so brackets inside strings do not miscount. Returns undefined if
// the value never closes.
function extractBalanced(text: string, start: number): string | undefined {
  const stack: string[] = [];
  let out = '';
  let inString = false;
  let escaped = false;
  for (let i = start; i < text.length; i++) {
    const ch = text[i];
    out += ch;
    if (inString) {
      if (escaped) escaped = false;
      else if (ch === '\\') escaped = true;
      else if (ch === '"') inString = false;
      continue;
    }
    if (ch === '"') {
      inString = true;
      continue;
    }
    if (ch === '{' || ch === '[') {
      stack.push(ch === '{' ? '}' : ']');
      continue;
    }
    if (ch === '}' || ch === ']') {
      stack.pop();
      if (stack.length === 0) return out;
    }
  }
  return undefined;
}

// Parse a judge reply into a JSON value. LLM judges routinely wrap the object
// in prose or a code fence; try a strict parse of the (optionally fenced) body
// first, then scan every bracket start in document order and return the first
// recoverable value, preferring a plain object (both callers expect one). Only
// a reply from which no JSON value can be recovered throws — preserving the
// "empty / malformed response" control-plane failure the adjudicator owns.
function parseJudgeJson(raw: string): unknown {
  const text = stripCodeFence(raw.trim());
  try {
    return JSON.parse(text);
  } catch {
    // Fall through to lenient extraction.
  }
  let firstValue: { value: unknown } | undefined;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (ch !== '{' && ch !== '[') continue;
    const span = extractBalanced(text, i);
    if (span === undefined) continue;
    let value: unknown;
    try {
      value = JSON.parse(span);
    } catch {
      continue;
    }
    if (isPlainObject(value)) return value;
    if (firstValue === undefined) firstValue = { value };
  }
  if (firstValue !== undefined) return firstValue.value;
  throw new Error('adjudicate: judge response is not valid JSON');
}

// ---------------------------------------------------------------------------
// Captain adjudication (link.md §Captain adjudication) — default LLM-judge
// ---------------------------------------------------------------------------

// Payload fields a state's `result` description names as required, via the
// FSM's load-bearing phrase ``Output shall include `<field>:``. For this FSM
// that yields `question` on the `needsBossReply` outcome and nothing on
// `completed`. The description text is read, never altered.
function extractRequiredFields(description: string): string[] {
  const fields: string[] = [];
  const re = /Output shall include `([A-Za-z_][A-Za-z0-9_]*):/g;
  for (const match of description.matchAll(re)) {
    fields.push(match[1]);
  }
  return fields;
}

// Build the LLM-judge prompt: name the source item's player, include the
// player's verbatim output, and list the state's `result` keys with their
// descriptions carried verbatim (never interpreted, paraphrased, or altered),
// demanding a JSON `{ guard, ...payloadFields }` answer keyed to exactly one
// declared guard.
function buildJudgePrompt(input: CaptainInput, finalText: string): string {
  const lines: string[] = [];
  lines.push(
    `The ${input.player} produced the following output for ${input.sourceItem}:`,
  );
  lines.push('```');
  lines.push(finalText);
  lines.push('```');
  lines.push('');
  lines.push(
    'Choose exactly one outcome by its `guard` and reply with a single JSON ' +
      'object `{ "guard": "<one of the guards below>", ...payloadFields }`. ' +
      'Include every payload field the chosen outcome description names as ' +
      'required. Do not interpret, paraphrase, or restate the descriptions.',
  );
  lines.push('');
  lines.push('Outcomes:');
  for (const [guard, description] of Object.entries(input.result)) {
    lines.push(`- \`${guard}\`: ${description}`);
  }
  return lines.join('\n');
}

// Coerce `result.finalText` into one of the state's declared `result` keys and
// extract any required payload fields. Fails loudly (throws) on an undeclared
// guard, a missing required payload field, or an empty/malformed response —
// these are control-plane errors (see `captainBridge`). A `needsBossReply`
// guard requires only that `question` be a string; an empty question is left
// for the FSM's own malformed-needsBossReply arm to route to `failed`.
async function adjudicate(
  input: CaptainInput,
  finalText: string,
  ports: PlaybookPorts,
  signal: AbortSignal,
): Promise<CaptainOutput> {
  const raw = await ports.callJudge(buildJudgePrompt(input, finalText), signal);
  const parsed = parseJudgeJson(raw);
  if (!isPlainObject(parsed)) {
    throw new Error('adjudicate: judge response is not a JSON object');
  }
  const guard = parsed.guard;
  if (typeof guard !== 'string') {
    throw new Error('adjudicate: judge response missing string "guard" field');
  }
  if (!Object.prototype.hasOwnProperty.call(input.result, guard)) {
    throw new Error(
      `adjudicate: undeclared guard "${guard}" — declared guards: ${Object.keys(
        input.result,
      ).join(', ')}`,
    );
  }
  for (const field of extractRequiredFields(input.result[guard])) {
    if (typeof parsed[field] !== 'string') {
      throw new Error(
        `adjudicate: judge response missing required field "${field}" for guard "${guard}"`,
      );
    }
  }
  return parsed as CaptainOutput;
}

// A needsBossReply outcome may only come from a state registered as resumable
// (wired for BOSS_REPLY resumption from `awaitBossReply`). A control-plane
// error otherwise.
function validateBossReplyOutput(
  input: CaptainInput,
  output: CaptainOutput,
): void {
  if (output.guard !== 'needsBossReply') return;
  if (typeof output.question !== 'string') {
    throw new Error(
      "adjudicate: needsBossReply outcome missing 'question' field",
    );
  }
  const stateId = STATE_ID_BY_SOURCE_ITEM.get(input.sourceItem);
  if (stateId === undefined || !RESUMABLE_STATE_IDS.has(stateId)) {
    throw new Error(
      `adjudicate: ${stateId ?? input.sourceItem} produced needsBossReply but is not registered as resumable`,
    );
  }
}

// ---------------------------------------------------------------------------
// Boss-event classification (link.md §Boss-event mapping) — default judge
// ---------------------------------------------------------------------------

interface ClassifierState {
  value: unknown;
  context: Record<string, unknown>;
}

function classifierState(snapshot: unknown): ClassifierState {
  if (isPlainObject(snapshot) && 'value' in snapshot) {
    const candidate = snapshot as { value?: unknown; context?: unknown };
    return {
      value: candidate.value,
      context: isPlainObject(candidate.context) ? candidate.context : {},
    };
  }
  return { value: snapshot, context: {} };
}

function pendingBossQuestionFromContext(
  context: Record<string, unknown>,
): PendingBossQuestion | undefined {
  const pending = context.pendingBossQuestion;
  if (!isPlainObject(pending)) return undefined;
  const { resumeStateId, sourceItem, player, question } = pending;
  if (
    typeof resumeStateId !== 'string' ||
    typeof sourceItem !== 'string' ||
    typeof player !== 'string' ||
    typeof question !== 'string'
  ) {
    return undefined;
  }
  return { resumeStateId, sourceItem, player, question };
}

// Build the classifier prompt: demand JSON against the FSM's typed event union,
// including each event's required payload fields and the jumpable BOSS_INTERRUPT
// targets. It is state-aware so that, in the Boss-reply suspension state, the
// current state and pending question let the judge distinguish a reply from a
// fresh directive.
function buildClassifierPrompt(text: string, state: ClassifierState): string {
  const currentState =
    typeof state.value === 'string' ? state.value : 'unknown';
  const pending = pendingBossQuestionFromContext(state.context);
  const lines: string[] = [];
  lines.push(
    'Classify the following Boss message into exactly one of the events below.',
  );
  lines.push(
    'Respond with a single JSON object: { "event": "<TYPE>", "payload": { ...fields } }.',
  );
  lines.push(
    'Use { "event": "NO_ACTION", "payload": {} } when no FSM action applies.',
  );
  lines.push('');
  lines.push(`Current state: ${currentState}`);
  if (pending !== undefined) {
    lines.push(`Pending Boss question: ${pending.question}`);
    lines.push(`Pending resume state: ${pending.resumeStateId}`);
  }
  lines.push('');
  lines.push('Events:');
  lines.push(
    `- ${START_EVENT}: payload { request: "<free-form Boss transformation request>" }`,
  );
  lines.push(`- ${BOSS_INTERRUPT_EVENT}: payload { targetId: "<stateId>" }`);
  lines.push('  targetId must be one of these jumpable states:');
  for (const target of INTERRUPT_TARGETS) {
    lines.push(`  - ${target.stateId}: ${target.description}`);
  }
  if (currentState === 'awaitBossReply') {
    lines.push(
      `- ${BOSS_REPLY_EVENT}: payload { answer: "<verbatim Boss answer to the pending question>" }`,
    );
  } else {
    lines.push(
      `- ${BOSS_REPLY_EVENT}: valid only when Current state is awaitBossReply`,
    );
  }
  lines.push('');
  lines.push('Boss message:');
  lines.push('```');
  lines.push(text);
  lines.push('```');
  return lines.join('\n');
}

// Classify a Boss turn into one typed FSM event plus payload, or no event.
// Empty/whitespace-only text produces no event and no port call. A `/`-prefixed
// turn is ordinary Boss text here (slash namespaces are host-level, resolved
// before the turn reaches this runtime). Classification is non-fatal: an
// unusable judge reply surfaces one status and takes no FSM action (unlike
// adjudication, which throws). An abort during classification is re-raised so
// the turn exits cleanly.
async function classifyBossText(
  text: string,
  ports: PlaybookPorts,
  signal: AbortSignal,
  snapshot: unknown,
): Promise<LinkEvent | undefined> {
  if (text.trim() === '') return undefined;

  const state = classifierState(snapshot);
  const prompt = buildClassifierPrompt(text, state);

  let raw: string;
  try {
    signal.throwIfAborted();
    raw = await ports.callJudge(prompt, signal);
    signal.throwIfAborted();
  } catch (error) {
    if (signal.aborted) throw error;
    await ports.emitStatus('Classifier call failed');
    return undefined;
  }

  let parsed: unknown;
  try {
    parsed = parseJudgeJson(raw);
  } catch {
    await ports.emitStatus('Classifier reply was not recoverable JSON');
    return undefined;
  }
  if (!isPlainObject(parsed)) {
    await ports.emitStatus('Classifier returned a non-object JSON response');
    return undefined;
  }
  const eventType = parsed.event;
  if (typeof eventType !== 'string') {
    await ports.emitStatus('Classifier did not name an event type');
    return undefined;
  }
  const payload = isPlainObject(parsed.payload) ? parsed.payload : {};

  switch (eventType) {
    case 'NO_ACTION':
    case 'NO_FSM_ACTION':
    case 'NONE':
      return undefined;
    case START_EVENT: {
      if (typeof payload.request !== 'string') {
        await ports.emitStatus(`Classifier omitted request for ${START_EVENT}`);
        return undefined;
      }
      return { type: 'START_LINK', request: payload.request };
    }
    case BOSS_INTERRUPT_EVENT: {
      if (typeof payload.targetId !== 'string') {
        await ports.emitStatus(
          `Classifier omitted targetId for ${BOSS_INTERRUPT_EVENT}`,
        );
        return undefined;
      }
      if (!INTERRUPT_TARGET_IDS.has(payload.targetId)) {
        await ports.emitStatus(
          `Classifier supplied invalid targetId for ${BOSS_INTERRUPT_EVENT}: ${payload.targetId}`,
        );
        return undefined;
      }
      return { type: 'BOSS_INTERRUPT', targetId: payload.targetId };
    }
    case BOSS_REPLY_EVENT: {
      if (state.value !== 'awaitBossReply') {
        await ports.emitStatus(
          `Classifier returned ${BOSS_REPLY_EVENT} outside awaitBossReply`,
        );
        return undefined;
      }
      if (typeof payload.answer !== 'string') {
        await ports.emitStatus(
          `Classifier omitted answer for ${BOSS_REPLY_EVENT}`,
        );
        return undefined;
      }
      return { type: 'BOSS_REPLY', answer: payload.answer };
    }
    default:
      await ports.emitStatus(
        `Classifier returned unknown event type: ${eventType}`,
      );
      return undefined;
  }
}

// ---------------------------------------------------------------------------
// Captain-actor bridge (link.md §Session lifecycle, §Abort)
// ---------------------------------------------------------------------------

// The concrete `captain` actor the runtime provides to the machine. Per
// invocation: resolve the playerId from the baked binding, compose the player
// prompt, call the player through the port, then adjudicate.
//
//   - A callPlayer result with status !== 'ok' (including an aborted/errored
//     cancellation) is a player-produced failure: throw so XState routes it
//     through `onError -> failed` (the FSM's error path / the host's
//     player-result channel).
//   - Adjudication is control-plane: on abort the rejection is the natural
//     abort path (routed to the quiescent error sink, turn exits cleanly);
//     any other adjudicator fault is recorded via `onControlPlaneError` and
//     re-thrown, so the actor cleans up to `failed` and `handleBossInput` then
//     re-throws the fault out of the turn.
//
// `getActiveSignal` flows the Boss's per-turn `handleBossInput.signal` into the
// port calls. It is combined with XState's actor-scoped signal so either a turn
// cancellation or invocation stop/re-entry aborts the in-flight port work.
function captainBridge(
  ports: PlaybookPorts,
  binding: PlayerBinding,
  getActiveSignal: () => AbortSignal | undefined,
  onControlPlaneError: (error: unknown) => void,
) {
  return fromPromise<CaptainOutput, CaptainInput>(async ({ input, signal }) => {
    const turnSignal = getActiveSignal();
    const activeSignal =
      turnSignal === undefined ? signal : AbortSignal.any([signal, turnSignal]);
    const playerId = resolvePlayerId(input, binding);
    const prompt = composePlayerPrompt(input);

    activeSignal.throwIfAborted();
    const result = await ports.callPlayer(playerId, prompt, activeSignal);
    activeSignal.throwIfAborted();
    if (result.status !== 'ok') {
      throw new Error(
        result.error ?? `callPlayer resolved with status "${result.status}"`,
      );
    }
    if (result.finalText === undefined) {
      throw new Error('callPlayer resolved with status "ok" but no finalText');
    }

    try {
      const output = await adjudicate(
        input,
        result.finalText,
        ports,
        activeSignal,
      );
      activeSignal.throwIfAborted();
      validateBossReplyOutput(input, output);
      return output;
    } catch (error) {
      if (!activeSignal.aborted) onControlPlaneError(error);
      throw error;
    }
  });
}

// ---------------------------------------------------------------------------
// Status / telemetry formatting (link.md §Status and telemetry)
// ---------------------------------------------------------------------------

// Normalize an unknown error to a compact, structured shape so raw Error
// instances never leak through the emission channels.
function normalizeError(
  err: unknown,
): { name: string; message: string } | undefined {
  if (err === undefined || err === null) return undefined;
  if (err instanceof Error) return { name: err.name, message: err.message };
  if (isPlainObject(err) && typeof err.message === 'string') {
    return {
      name: typeof err.name === 'string' ? err.name : 'Error',
      message: err.message,
    };
  }
  return { name: 'Error', message: String(err) };
}

// Normalize any `error` field inside a telemetry event so a failed transition
// does not leak a raw Error through the structured channel.
function normalizeEventForTelemetry(event: unknown): unknown {
  if (!isPlainObject(event) || !('error' in event)) return event;
  return { ...event, error: normalizeError(event.error) };
}

// The human-readable status line for entering a state. Every transition emits
// one by default (the host may filter). `awaitBossReply` surfaces the pending
// player question so Boss can answer it.
function formatStateEntry(
  stateId: string,
  context: Record<string, unknown>,
): string {
  const description = STATE_DESCRIPTIONS.get(stateId);
  if (stateId === 'awaitBossReply') {
    const pending = pendingBossQuestionFromContext(context);
    if (pending !== undefined) {
      return `${stateId}: ${pending.player} asks: ${pending.question}`;
    }
  }
  return description ? `${stateId}: ${description}` : stateId;
}

// ---------------------------------------------------------------------------
// Quiescence (link.md §Session lifecycle step 4, §Abort)
// ---------------------------------------------------------------------------

function isQuiescent(snapshot: { value: unknown }): boolean {
  return (
    typeof snapshot.value === 'string' &&
    QUIESCENT_STATE_IDS.has(snapshot.value)
  );
}

// Resolve once the actor's snapshot value is a quiescent state (one that takes
// a Boss event, or a final state). Each Captain invoke is driven to completion
// by the provided `captain` actor, whose settling advances the machine; on
// abort the natural-rejection path lands the machine in `failed`, which is
// quiescent, so this resolves without a separate poll.
function driveToQuiescence(
  actor: ReturnType<typeof createActor>,
): Promise<void> {
  return new Promise<void>((resolve) => {
    if (isQuiescent(actor.getSnapshot())) {
      resolve();
      return;
    }
    const subscription = actor.subscribe((snapshot) => {
      if (isQuiescent(snapshot)) {
        subscription.unsubscribe();
        resolve();
      }
    });
  });
}

// ---------------------------------------------------------------------------
// Internal surface for compilation-correctness tests (link.md §Output)
// ---------------------------------------------------------------------------

// Not a stable public API; the leading underscore signals "subject to change".
// At minimum the player-prompt composer is exposed so verification can exercise
// composition without a host.
export const _internal = {
  composePlayerPrompt,
  resolvePlayerId,
  effectiveBinding,
  DEFAULT_PLAYER_BINDING,
  adjudicate,
  buildJudgePrompt,
  extractRequiredFields,
  validateBossReplyOutput,
  parseJudgeJson,
  classifyBossText,
  buildClassifierPrompt,
  captainBridge,
  pendingBossQuestionFromContext,
  formatStateEntry,
  normalizeError,
  normalizeEventForTelemetry,
  CAPTAIN_STATES,
  INTERRUPT_TARGETS,
  RESUMABLE_STATE_IDS,
  QUIESCENT_STATE_IDS,
};

// ---------------------------------------------------------------------------
// Runtime factory (default export) — link.md §PlaybookRuntime contract
// ---------------------------------------------------------------------------

export function createPlaybookRuntime(
  options: LinkPlaybookOptions,
): PlaybookRuntime {
  // The deterministic player binding this runtime applies at every callPlayer
  // site — the baked default, with any per-run Captain override from options.
  const binding = effectiveBinding(options);

  let actor: ReturnType<typeof createActor> | undefined;
  let savedPorts: PlaybookPorts | undefined;
  // The Boss's per-turn AbortSignal, surfaced to the captain bridge so the port
  // calls see the right cancellation source. Undefined between turns.
  let activeSignal: AbortSignal | undefined;
  // A control-plane (adjudicator) fault captured during a turn, re-thrown out
  // of `handleBossInput` after the actor cleans up. Undefined when the turn had
  // none.
  let controlPlaneError: unknown;
  let hasControlPlaneError = false;
  // Previous root-machine state value, for the inspect-driven emitter.
  let priorState: unknown;

  // Emissions "shall be ordered, awaited, and never-dropped" (link.md
  // §PlaybookPorts contract). The inspect/subscribe callbacks are synchronous
  // and cannot await, so each emission is enqueued and a single drainer runs
  // them sequentially.
  const emitQueue: Array<() => Promise<void>> = [];
  let drainer: Promise<void> | undefined;
  let emissionError: unknown;
  let hasEmissionError = false;

  function enqueueEmit(fn: () => Promise<void>): void {
    emitQueue.push(fn);
    if (drainer === undefined) {
      drainer = (async () => {
        while (emitQueue.length > 0) {
          const next = emitQueue.shift();
          if (next === undefined) break;
          try {
            await next();
          } catch (error) {
            // Keep draining in order so later emissions are not dropped, then
            // surface the first host-side emission failure at the turn boundary.
            if (!hasEmissionError) emissionError = error;
            hasEmissionError = true;
          }
        }
        drainer = undefined;
      })();
    }
  }

  async function drainEmissions(): Promise<void> {
    await (drainer ?? Promise.resolve());
    if (hasEmissionError) {
      const error = emissionError;
      emissionError = undefined;
      hasEmissionError = false;
      throw error;
    }
  }

  // Construct the session-scoped actor: provide the concrete `captain` bridge,
  // derive FSM `input` from options, and subscribe (via inspect) to each root
  // snapshot so every transition surfaces telemetry and status before the next
  // event fires.
  function buildActor(ports: PlaybookPorts): ReturnType<typeof createActor> {
    priorState = undefined;
    return createActor(
      linkMachine.provide({
        actors: {
          captain: captainBridge(
            ports,
            binding,
            () => activeSignal,
            (error) => {
              if (!hasControlPlaneError) controlPlaneError = error;
              hasControlPlaneError = true;
            },
          ),
        },
      }),
      {
        input: options,
        inspect: (inspectionEvent) => {
          if (inspectionEvent.type !== '@xstate.snapshot') return;
          const snapshot = inspectionEvent.snapshot as {
            value?: unknown;
            context?: Record<string, unknown>;
          };
          // Only the root machine snapshot has a string value; ignore the
          // captain sub-actor's (fromPromise) snapshots.
          if (typeof snapshot.value !== 'string') return;
          const to = snapshot.value;
          if (priorState === to) return;
          const from = priorState;
          priorState = to;
          const context = snapshot.context ?? {};

          // One telemetry event per transition, under the namespaced topic
          // with payload { from, to, event } (event normalized so no raw Error
          // leaks). The runtime never interprets the topic.
          enqueueEmit(() =>
            ports.emitTelemetry({
              topic: 'playbook.fsm.state',
              payload: {
                from,
                to,
                event: normalizeEventForTelemetry(inspectionEvent.event),
              },
            }),
          );

          // One status per transition (the host filters). On entry to `failed`,
          // surface the actor's `lastError`.
          const line = formatStateEntry(to, context);
          if (to === 'failed') {
            const data = { lastError: normalizeError(context.lastError) };
            enqueueEmit(() => ports.emitStatus(line, data));
          } else {
            enqueueEmit(() => ports.emitStatus(line));
          }
        },
      },
    );
  }

  const runtime: PlaybookRuntime & { _getActor(): typeof actor } = {
    async init(ports: PlaybookPorts): Promise<void> {
      savedPorts = ports;
      actor = buildActor(ports);
      actor.start();
      await drainEmissions();
    },

    async handleBossInput(turn: {
      text: string;
      signal: AbortSignal;
    }): Promise<void> {
      if (actor === undefined || savedPorts === undefined) {
        throw new Error('handleBossInput: init must be called first');
      }
      const ports = savedPorts;
      activeSignal = turn.signal;
      controlPlaneError = undefined;
      hasControlPlaneError = false;
      try {
        // 1. Classify the turn into an FSM event through the Boss-event mapping.
        let event: LinkEvent | undefined;
        try {
          event = await classifyBossText(
            turn.text,
            ports,
            turn.signal,
            actor.getSnapshot(),
          );
        } catch (error) {
          // An abort during classification: no event was sent and the actor is
          // already quiescent, so exit the turn cleanly. Surface anything else.
          if (turn.signal.aborted) {
            await drainEmissions();
            return;
          }
          throw error;
        }
        if (turn.signal.aborted) {
          await drainEmissions();
          return;
        }
        // No event (empty text, no-action, or an unusable classifier reply):
        // drain any emissions and return.
        if (event === undefined) {
          await drainEmissions();
          return;
        }

        // 2. A `final` state is terminal and cannot accept new events: dispose
        //    and reconstruct the actor before sending.
        if (actor.getSnapshot().status === 'done') {
          actor.stop();
          actor = buildActor(ports);
          actor.start();
        }

        // 3. Send the classified event.
        actor.send(event);

        // 4. Drive to quiescence. Each captain invoke is completed by the
        //    bridge; on abort the natural-rejection path lands the machine in
        //    `failed`.
        await driveToQuiescence(actor);

        // Drain transition emissions so Boss sees this turn's final status.
        await drainEmissions();

        // A control-plane (adjudicator) fault is propagated out of the turn
        // after the actor's cleanup and the emission drain.
        if (hasControlPlaneError) {
          const error = controlPlaneError;
          controlPlaneError = undefined;
          hasControlPlaneError = false;
          throw error;
        }
      } finally {
        activeSignal = undefined;
      }
    },

    async dispose(): Promise<void> {
      if (actor !== undefined) {
        actor.stop();
        actor = undefined;
      }
      await drainEmissions();
      savedPorts = undefined;
    },

    // Test-only escape hatch for inspecting the underlying actor's snapshot.
    _getActor() {
      return actor;
    },
  };

  return runtime;
}

// The default export conforms to the shared generic factory type
// (link.md §PlaybookRuntime contract, §Output).
const _factoryConformance: PlaybookRuntimeFactory<LinkPlaybookOptions> =
  createPlaybookRuntime;
void _factoryConformance;

export default createPlaybookRuntime;
