// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): FSM introspection pins.
// The PINNED topology was derived from the artifact at build time; any
// unintended structural change to the machine fails this test.
import { describe, expect, it } from 'vitest';

import { findMachineConfig, pinIntrospection } from './.slc-verify/verify.js';
import * as fsm from './link.fsm.js';

const PINNED = {
  initial: 'ready',
  captain: [
    {
      state: 'compile',
      actor: 'captain',
      sourceItem: 'LINK-1',
      player: '',
      resultKeys: ['linked', 'needsBossReply', 'unrepresentable'],
      onDone: [
        {
          index: 0,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 1,
          target: 'failed',
          guarded: true,
        },
        {
          index: 2,
          target: 'done',
          guarded: true,
        },
        {
          index: 3,
          target: 'done',
          guarded: true,
        },
        {
          index: 4,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
  ],
  quiescent: [
    {
      state: 'ready',
      final: false,
      on: {
        COMPILE: [
          {
            index: 0,
            target: 'compile',
            guarded: false,
          },
        ],
      },
    },
    {
      state: 'awaitBossReply',
      final: false,
      on: {
        BOSS_REPLY: [
          {
            index: 0,
            target: 'failed',
            guarded: true,
          },
          {
            index: 1,
            target: 'compile',
            guarded: true,
          },
        ],
        BOSS_INTERRUPT: [
          {
            index: 0,
            target: 'ready',
            guarded: true,
          },
          {
            index: 1,
            target: 'compile',
            guarded: true,
          },
          {
            index: 2,
            target: 'failed',
            guarded: true,
          },
        ],
        COMPILE: [
          {
            index: 0,
            target: 'compile',
            guarded: false,
          },
        ],
      },
    },
    {
      state: 'failed',
      final: false,
      on: {
        COMPILE: [
          {
            index: 0,
            target: 'compile',
            guarded: false,
          },
        ],
      },
    },
    {
      state: 'done',
      final: true,
      on: {},
    },
  ],
  rootOn: {
    BOSS_INTERRUPT: [
      {
        index: 0,
        target: 'ready',
        guarded: true,
      },
      {
        index: 1,
        target: 'compile',
        guarded: true,
      },
      {
        index: 2,
        target: 'failed',
        guarded: true,
      },
    ],
  },
  interruptTargets: ['ready', 'compile', 'failed'],
};

describe('link: FSM introspection', () => {
  it('matches the machine topology pinned at build time', () => {
    expect(pinIntrospection(findMachineConfig(fsm))).toEqual(PINNED);
  });
});
