// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): FSM introspection pins.
// The PINNED topology was derived from the artifact at build time; any
// unintended structural change to the machine fails this test.
import { describe, expect, it } from 'vitest';

import { findMachineConfig, pinIntrospection } from './.slc-verify/verify.js';
import * as fsm from './link.fsm.js';

const PINNED = {
  initial: 'ready',
  captain: [
    {
      state: 'linking',
      actor: 'captain',
      sourceItem: 'LINK-1',
      player: '',
      resultKeys: ['done', 'needsBossReply'],
      onDone: [
        {
          index: 0,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 1,
          target: 'failed',
          guarded: true,
        },
        {
          index: 2,
          target: 'done',
          guarded: true,
        },
        {
          index: 3,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
  ],
  quiescent: [
    {
      state: 'ready',
      final: false,
      on: {
        LINK_REQUEST: [
          {
            index: 0,
            target: 'linking',
            guarded: false,
          },
        ],
      },
    },
    {
      state: 'awaitBossReply',
      final: false,
      on: {
        BOSS_REPLY: [
          {
            index: 0,
            target: 'failed',
            guarded: true,
          },
          {
            index: 1,
            target: 'linking',
            guarded: true,
          },
        ],
        LINK_REQUEST: [
          {
            index: 0,
            target: 'linking',
            guarded: false,
          },
        ],
      },
    },
    {
      state: 'failed',
      final: false,
      on: {
        LINK_REQUEST: [
          {
            index: 0,
            target: 'linking',
            guarded: false,
          },
        ],
      },
    },
    {
      state: 'done',
      final: true,
      on: {},
    },
  ],
  rootOn: {},
  interruptTargets: [],
};

describe('link: FSM introspection', () => {
  it('matches the machine topology pinned at build time', () => {
    expect(pinIntrospection(findMachineConfig(fsm))).toEqual(PINNED);
  });
});
