// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): FSM transition coverage for "link".
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import {
  checkFsmCoverage,
  fsmCoverageTestTimeout,
} from './.slc-verify/verify.js';
import * as fsm from './link.fsm.js';

describe('link: FSM coverage', () => {
  it(
    'reaches every declared transition',
    async () => {
      const sourceText = readFileSync(
        fileURLToPath(new URL('./link.fsm.ts', import.meta.url)),
        'utf8',
      );
      expect(await checkFsmCoverage(fsm, { sourceText })).toEqual([]);
    },
    fsmCoverageTestTimeout(fsm),
  );
});
