// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): FSM introspection pins.
// The PINNED topology was derived from the artifact at build time; any
// unintended structural change to the machine fails this test.
import { describe, expect, it } from 'vitest';

import { findMachineConfig, pinIntrospection } from './.slc-verify/verify.js';
import * as fsm from './workflow.fsm.js';

const PINNED = {
  initial: 'ready',
  captain: [
    {
      state: 'implement',
      actor: 'player',
      sourceItem: 'IMPL-1',
      player: 'Coder',
      resultKeys: ['done', 'needsBossReply'],
      onDone: [
        {
          index: 0,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 1,
          target: 'failed',
          guarded: true,
        },
        {
          index: 2,
          target: 'review',
          guarded: true,
        },
        {
          index: 3,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
    {
      state: 'review',
      actor: 'player',
      sourceItem: 'REVIEW-1',
      player: 'Reviewer',
      resultKeys: ['clean', 'findings', 'needsBossReply'],
      onDone: [
        {
          index: 0,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 1,
          target: 'failed',
          guarded: true,
        },
        {
          index: 2,
          target: 'judge',
          guarded: true,
        },
        {
          index: 3,
          target: 'done',
          guarded: true,
        },
        {
          index: 4,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
    {
      state: 'judge',
      actor: 'player',
      sourceItem: 'JUDGE-1',
      player: 'Coder',
      resultKeys: ['agreed', 'disagreed', 'needsBossReply'],
      onDone: [
        {
          index: 0,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 1,
          target: 'failed',
          guarded: true,
        },
        {
          index: 2,
          target: 'reimplement',
          guarded: true,
        },
        {
          index: 3,
          target: 'done',
          guarded: true,
        },
        {
          index: 4,
          target: 'argue',
          guarded: true,
        },
        {
          index: 5,
          target: 'reimplement',
          guarded: true,
        },
        {
          index: 6,
          target: 'done',
          guarded: true,
        },
        {
          index: 7,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
    {
      state: 'argue',
      actor: 'player',
      sourceItem: 'ARGUE-1',
      player: 'Reviewer',
      resultKeys: ['agreed', 'findings', 'needsBossReply'],
      onDone: [
        {
          index: 0,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 1,
          target: 'failed',
          guarded: true,
        },
        {
          index: 2,
          target: 'judge',
          guarded: true,
        },
        {
          index: 3,
          target: 'reimplement',
          guarded: true,
        },
        {
          index: 4,
          target: 'done',
          guarded: true,
        },
        {
          index: 5,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
    {
      state: 'reimplement',
      actor: 'player',
      sourceItem: 'IMPL-2',
      player: 'Coder',
      resultKeys: ['done', 'needsBossReply'],
      onDone: [
        {
          index: 0,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 1,
          target: 'failed',
          guarded: true,
        },
        {
          index: 2,
          target: 'review',
          guarded: true,
        },
        {
          index: 3,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
  ],
  quiescent: [
    {
      state: 'ready',
      final: false,
      on: {
        START: [
          {
            index: 0,
            target: 'repoSetup',
            guarded: false,
          },
        ],
      },
    },
    {
      state: 'repoSetup',
      final: false,
      on: {},
    },
    {
      state: 'awaitBossReply',
      final: false,
      on: {
        BOSS_REPLY: [
          {
            index: 0,
            target: 'failed',
            guarded: true,
          },
          {
            index: 1,
            target: 'implement',
            guarded: true,
          },
          {
            index: 2,
            target: 'review',
            guarded: true,
          },
          {
            index: 3,
            target: 'judge',
            guarded: true,
          },
          {
            index: 4,
            target: 'argue',
            guarded: true,
          },
          {
            index: 5,
            target: 'reimplement',
            guarded: true,
          },
          {
            index: 6,
            target: 'failed',
            guarded: false,
          },
        ],
      },
    },
    {
      state: 'failed',
      final: false,
      on: {
        START: [
          {
            index: 0,
            target: 'repoSetup',
            guarded: false,
          },
        ],
      },
    },
    {
      state: 'done',
      final: true,
      on: {},
    },
  ],
  rootOn: {},
  interruptTargets: [],
};

describe('workflow: FSM introspection', () => {
  it('matches the machine topology pinned at build time', () => {
    expect(pinIntrospection(findMachineConfig(fsm))).toEqual(PINNED);
  });
});
