// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): prompt contract.
// The pinned rows were derived from the artifacts at build time; wiring,
// placeholder, or composition drift fails this test.
import { describe, expect, it } from 'vitest';

import {
  capturePromptContract,
  checkPromptComposition,
  deriveSubstitutions,
  findMachineConfig,
} from './.slc-verify/verify.js';
import * as fsm from './workflow.fsm.js';
import * as playbook from './workflow.playbook.js';

const CONTRACT = [
  {
    state: 'implement',
    sourceItem: 'IMPL-1',
    player: 'Coder',
    reads: ['bossReply', 'pendingBossQuestion', 'task'],
    wires: {
      task: ['task'],
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: ['<task>'],
  },
  {
    state: 'review',
    sourceItem: 'REVIEW-1',
    player: 'Reviewer',
    reads: ['bossReply', 'pendingBossQuestion'],
    wires: {
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: [],
  },
  {
    state: 'judge',
    sourceItem: 'JUDGE-1',
    player: 'Coder',
    reads: ['bossReply', 'findings', 'pendingBossQuestion'],
    wires: {
      findings: ['findings'],
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: ['<findings>'],
  },
  {
    state: 'argue',
    sourceItem: 'ARGUE-1',
    player: 'Reviewer',
    reads: ['bossReply', 'judgment', 'pendingBossQuestion'],
    wires: {
      judgment: ['judgment'],
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: ['<judgment>'],
  },
  {
    state: 'reimplement',
    sourceItem: 'IMPL-2',
    player: 'Coder',
    reads: ['bossReply', 'conclusion', 'pendingBossQuestion'],
    wires: {
      conclusion: ['conclusion'],
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: ['<conclusion>'],
  },
];

describe('workflow: prompt contract', () => {
  it('matches the prompt contract pinned at build time', () => {
    expect(capturePromptContract(findMachineConfig(fsm))).toEqual(CONTRACT);
  });

  const PLAYER_SUBSTITUTED = {
    implement: ['<task>'],
    review: [],
    judge: ['<findings>'],
    argue: ['<judgment>'],
    reimplement: ['<conclusion>'],
  };

  const composePlayer = (
    playbook as unknown as {
      _internal: { composePlayerPrompt: (input: unknown) => string };
    }
  )._internal.composePlayerPrompt;

  it('composes player prompts per the link contract', () => {
    expect(
      checkPromptComposition({
        config: findMachineConfig(fsm),
        compose: composePlayer,
        actor: 'player',
      }),
    ).toEqual([]);
  });

  it('substitutes the player placeholders pinned at build time', () => {
    expect(
      deriveSubstitutions(findMachineConfig(fsm), composePlayer, 'player'),
    ).toEqual(PLAYER_SUBSTITUTED);
  });
});
