// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): FSM introspection pins.
// The PINNED topology was derived from the artifact at build time; any
// unintended structural change to the machine fails this test.
import { describe, expect, it } from 'vitest';

import { findMachineConfig, pinIntrospection } from './.slc-verify/verify.js';
import * as fsm from './workflow.fsm.js';

const PINNED = {
  initial: 'ready',
  captain: [
    {
      state: 'implement',
      actor: 'player',
      sourceItem: 'WORKFLOW-2',
      player: '',
      role: 'coder',
      resultKeys: ['done', 'needsBossReply'],
      onDone: [
        {
          index: 0,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 1,
          target: 'review',
          guarded: true,
        },
        {
          index: 2,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
    {
      state: 'review',
      actor: 'player',
      sourceItem: 'WORKFLOW-3',
      player: '',
      role: 'reviewer',
      resultKeys: ['clean', 'findings', 'needsBossReply'],
      onDone: [
        {
          index: 0,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 1,
          target: 'judgeFindings',
          guarded: true,
        },
        {
          index: 2,
          target: 'reviewedClean',
          guarded: true,
        },
        {
          index: 3,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
    {
      state: 'judgeFindings',
      actor: 'player',
      sourceItem: 'WORKFLOW-4',
      player: '',
      role: 'coder',
      resultKeys: ['judged', 'needsBossReply'],
      onDone: [
        {
          index: 0,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 1,
          target: 'argue',
          guarded: true,
        },
        {
          index: 2,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
    {
      state: 'argue',
      actor: 'player',
      sourceItem: 'WORKFLOW-5',
      player: '',
      role: 'reviewer',
      resultKeys: ['agreement', 'argument', 'needsBossReply'],
      onDone: [
        {
          index: 0,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 1,
          target: 'judgeArgument',
          guarded: true,
        },
        {
          index: 2,
          target: 'apply',
          guarded: true,
        },
        {
          index: 3,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
    {
      state: 'judgeArgument',
      actor: 'player',
      sourceItem: 'WORKFLOW-6',
      player: '',
      role: 'coder',
      resultKeys: ['judged', 'needsBossReply'],
      onDone: [
        {
          index: 0,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 1,
          target: 'argue',
          guarded: true,
        },
        {
          index: 2,
          target: 'apply',
          guarded: true,
        },
        {
          index: 3,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
    {
      state: 'apply',
      actor: 'player',
      sourceItem: 'WORKFLOW-7',
      player: '',
      role: 'coder',
      resultKeys: ['done', 'needsBossReply'],
      onDone: [
        {
          index: 0,
          target: 'awaitBossReply',
          guarded: true,
        },
        {
          index: 1,
          target: 'review',
          guarded: true,
        },
        {
          index: 2,
          target: 'loopLimitReached',
          guarded: true,
        },
        {
          index: 3,
          target: 'failed',
          guarded: false,
        },
      ],
      onError: [
        {
          index: 0,
          target: 'failed',
          guarded: false,
        },
      ],
      on: {},
    },
  ],
  quiescent: [
    {
      state: 'ready',
      final: false,
      on: {
        START: [
          {
            index: 0,
            target: 'setup',
            guarded: false,
          },
        ],
      },
    },
    {
      state: 'setup',
      final: false,
      on: {},
    },
    {
      state: 'awaitBossReply',
      final: false,
      on: {
        BOSS_REPLY: [
          {
            index: 0,
            target: 'implement',
            guarded: true,
          },
          {
            index: 1,
            target: 'review',
            guarded: true,
          },
          {
            index: 2,
            target: 'judgeFindings',
            guarded: true,
          },
          {
            index: 3,
            target: 'argue',
            guarded: true,
          },
          {
            index: 4,
            target: 'judgeArgument',
            guarded: true,
          },
          {
            index: 5,
            target: 'apply',
            guarded: true,
          },
          {
            index: 6,
            target: 'failed',
            guarded: false,
          },
        ],
      },
    },
    {
      state: 'failed',
      final: false,
      on: {
        START: [
          {
            index: 0,
            target: 'setup',
            guarded: false,
          },
        ],
      },
    },
    {
      state: 'reviewedClean',
      final: true,
      on: {},
    },
    {
      state: 'loopLimitReached',
      final: true,
      on: {},
    },
  ],
  rootOn: {
    BOSS_INTERRUPT: [
      {
        index: 0,
        target: 'implement',
        guarded: true,
      },
      {
        index: 1,
        target: 'review',
        guarded: true,
      },
      {
        index: 2,
        target: 'judgeFindings',
        guarded: true,
      },
      {
        index: 3,
        target: 'argue',
        guarded: true,
      },
      {
        index: 4,
        target: 'judgeArgument',
        guarded: true,
      },
      {
        index: 5,
        target: 'apply',
        guarded: true,
      },
    ],
  },
  interruptTargets: [
    'implement',
    'review',
    'judgeFindings',
    'argue',
    'judgeArgument',
    'apply',
  ],
};

describe('workflow: FSM introspection', () => {
  it('matches the machine topology pinned at build time', () => {
    expect(pinIntrospection(findMachineConfig(fsm))).toEqual(PINNED);
  });
});
