// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by slc/link.md (FSM-to-Runtime linker).
// Source FSM:    ./workflow.fsm.ts
// Link target:   @sublang/playbook/src/runtime.ts (contract types)
// Runtime:       the shared createXStatePlaybookRuntime factory from
//                @sublang/playbook/xstate-runtime interprets the FSM
//                (slc/link.md §Output); this module carries only the
//                workflow-specific spec.
// Player bind:   Coder -> coder, Reviewer -> reviewer
//                (default binding: lowercased player name; no binding was
//                supplied to the linker).
// Boss event:    deterministic START entry (turn.text -> START.task) for the
//                ready/failed entry; free-text judge classification otherwise
//                (default), used only for BOSS_REPLY at awaitBossReply.
// Adjudication:  LLM-judge per state (default).
// Abort:         natural rejection; every player-invoking state's onError
//                routes to the quiescent failed state, and the script state's
//                onError does too.
// Actors:        script (REPO-1) + player (IMPL-1/REVIEW-1/JUDGE-1/ARGUE-1/
//                IMPL-2); no captain or nested-playbook actor is declared.
// Contract:      PlaybookRuntime / PlaybookPorts / PlaybookSession and the
//                other contract types are imported and re-exported from
//                @sublang/playbook/runtime (slc/link.md §Output).

import {
  createXStatePlaybookRuntime,
  defaultComposeCaptainPrompt,
  defaultComposePlayerPrompt,
  snapshotJsonValue,
  type XStatePlaybookRuntimeSpec,
} from '@sublang/playbook/xstate-runtime';

import { workflowMachine, type WorkflowInput } from './workflow.fsm.ts';

import type {
  JsonValue,
  PlaybookRuntimeFactory,
} from '@sublang/playbook/runtime';

// Public contract. The runtime-boundary types are re-exported from the shared
// type-only module (slc/link.md §Output) so every linked playbook resolves one
// contract definition rather than redefining it.
export type {
  CaptainCallOptions,
  CaptainResult,
  JsonValue,
  NormalizedError,
  PlayerCallOptions,
  PlayerResult,
  PlaybookCallRequest,
  PlaybookCallResult,
  PlaybookCallStart,
  PlaybookPendingCall,
  PlaybookPorts,
  PlaybookRunResult,
  PlaybookRuntime,
  PlaybookRuntimeFactory,
  PlaybookRuntimeSnapshot,
  PlaybookSession,
  PlaybookState,
  PlaybookStateValue,
  PlaybookTraceEvent,
  PlaybookTraceType,
} from '@sublang/playbook/runtime';

// Per-run options for this playbook (slc/link.md §PlaybookRuntime contract).
// The FSM's only input field (WorkflowInput.task) is optional and is supplied
// by the Boss turn through the deterministic START entry, so it is not a
// runtime option. The FSM contains a script state (REPO-1), so the optional
// `cwd` script working directory is the sole declared option
// (slc/link.md §Script execution).
export interface PlaybookRuntimeOptions {
  cwd?: string;
}

function snapshotWorkflowOptions(value: unknown): PlaybookRuntimeOptions {
  const captured = snapshotJsonValue(value, 'workflow runtime options');
  if (
    captured === null ||
    typeof captured !== 'object' ||
    Array.isArray(captured)
  ) {
    throw new TypeError('workflow runtime options must be an object');
  }
  const record = captured as Readonly<Record<string, JsonValue>>;
  const allowed = new Set(['cwd']);
  for (const [key, option] of Object.entries(record)) {
    if (!allowed.has(key)) {
      throw new TypeError(`workflow runtime options.${key} is not declared`);
    }
    if (typeof option !== 'string') {
      throw new TypeError(`workflow runtime options.${key} must be a string`);
    }
  }
  return captured as unknown as PlaybookRuntimeOptions;
}

// Internal export surface for compilation-correctness tests. The composers are
// the shared defaults because this spec does not override composition; the
// default player composer performs the `<task>`/`<findings>`/`<judgment>`/
// `<conclusion>` placeholder substitution from the typed PlayerInput fields.
export const _internal = {
  composePlayerPrompt: defaultComposePlayerPrompt,
  composeCaptainPrompt: defaultComposeCaptainPrompt,
};

// The workflow-specific spec handed to the shared runtime factory
// (slc/link.md §Output). Every other strategy — player/script actor
// provisioning, prompt composition, classification, adjudication, statuses,
// and resumable-state derivation — comes from the factory's FSM-derived
// generic defaults:
//   - resumableStateIds: the awaitBossReply BOSS_REPLY targets
//     (implement, review, judge, argue, reimplement);
//   - player binding: lowercased player name (Coder->coder, Reviewer->reviewer);
//   - placeholder substitution: canonical single-word token -> same-name field;
//   - script cwd: the validated options.cwd, else the process cwd.
const runtimeSpec: XStatePlaybookRuntimeSpec<PlaybookRuntimeOptions> = {
  label: 'workflow',
  snapshotOptions: snapshotWorkflowOptions,
  // WorkflowInput.task is Boss-supplied via the START event, not an option, so
  // the machine starts with an empty input; `cwd` reaches the script actor
  // through the factory's default scriptCwd(options), not machine input.
  machineInput: (): WorkflowInput => ({}),
  // Deterministic textual entry (slc/link.md §Boss-event mapping): the ready
  // and failed states accept exactly one ordinary textual entry event, START,
  // whose declared textual payload field is `task`.
  entryEvent: { type: 'START', textField: 'task' },
};

const createPlaybookRuntime: PlaybookRuntimeFactory<PlaybookRuntimeOptions> =
  createXStatePlaybookRuntime(workflowMachine, runtimeSpec);

export default createPlaybookRuntime;
