// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): GEARS↔FSM conformance.
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import {
  checkGearsFsmConformance,
  findConcurrentRoleSets,
  findMachineConfig,
} from './.slc-verify/verify.js';
import * as fsm from './workflow.fsm.js';

const SCHEMA_FINDINGS = [];

describe('workflow: GEARS↔FSM conformance', () => {
  it('uses consistent artifact-schema evidence', () => {
    expect(SCHEMA_FINDINGS).toEqual([]);
  });

  it('maps every GEARS item to a state with its player and verbatim prompt', () => {
    const gears = readFileSync(
      fileURLToPath(new URL('./workflow.gears.md', import.meta.url)),
      'utf8',
    );
    expect(
      checkGearsFsmConformance(gears, findMachineConfig(fsm), {
        concurrentRoleSets: findConcurrentRoleSets(fsm),
        artifactSchema: 3,
      }),
    ).toEqual([]);
  });
});
