// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

// Generated by slc (DR-009): prompt contract.
// The pinned rows were derived from the artifacts at build time; wiring,
// placeholder, or composition drift fails this test.
import { describe, expect, it } from 'vitest';

import {
  capturePromptContract,
  checkPromptComposition,
  deriveSubstitutions,
  findMachineConfig,
} from './.slc-verify/verify.js';
import * as fsm from './workflow.fsm.js';
import * as playbook from './workflow.playbook.js';

const CONTRACT = [
  {
    state: 'implement',
    sourceItem: 'WORKFLOW-2',
    player: '',
    role: 'coder',
    reads: ['bossReply', 'pendingBossQuestion'],
    wires: {
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: [],
  },
  {
    state: 'review',
    sourceItem: 'WORKFLOW-3',
    player: '',
    role: 'reviewer',
    reads: ['bossReply', 'pendingBossQuestion'],
    wires: {
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: [],
  },
  {
    state: 'judgeFindings',
    sourceItem: 'WORKFLOW-4',
    player: '',
    role: 'coder',
    reads: ['bossReply', 'pendingBossQuestion', 'reviewFindings'],
    wires: {
      reviewFindings: ['reviewFindings'],
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: ['<reviewFindings>'],
  },
  {
    state: 'argue',
    sourceItem: 'WORKFLOW-5',
    player: '',
    role: 'reviewer',
    reads: ['bossReply', 'coderJudgment', 'pendingBossQuestion'],
    wires: {
      coderJudgment: ['coderJudgment'],
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: ['<coderJudgment>'],
  },
  {
    state: 'judgeArgument',
    sourceItem: 'WORKFLOW-6',
    player: '',
    role: 'coder',
    reads: ['bossReply', 'pendingBossQuestion', 'reviewerArgument'],
    wires: {
      reviewerArgument: ['reviewerArgument'],
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: ['<reviewerArgument>'],
  },
  {
    state: 'apply',
    sourceItem: 'WORKFLOW-7',
    player: '',
    role: 'coder',
    reads: ['bossReply', 'coderJudgment', 'pendingBossQuestion'],
    wires: {
      coderJudgment: ['coderJudgment'],
      pendingBossQuestion: ['pendingBossQuestion'],
      bossReply: ['bossReply'],
    },
    placeholders: ['<coderJudgment>'],
  },
];
const SCHEMA_FINDINGS = [];

describe('workflow: prompt contract', () => {
  it('uses consistent artifact-schema evidence', () => {
    expect(SCHEMA_FINDINGS).toEqual([]);
  });

  it('matches the prompt contract pinned at build time', () => {
    expect(capturePromptContract(findMachineConfig(fsm))).toEqual(CONTRACT);
  });

  const PLAYER_SUBSTITUTED = {
    implement: [],
    review: [],
    judgeFindings: ['<reviewFindings>'],
    argue: ['<coderJudgment>'],
    judgeArgument: ['<reviewerArgument>'],
    apply: ['<coderJudgment>'],
  };

  const composePlayer = (
    playbook as unknown as {
      _internal: { composePlayerPrompt: (input: unknown) => string };
    }
  )._internal.composePlayerPrompt;

  it('composes player prompts per the link contract', () => {
    expect(
      checkPromptComposition({
        config: findMachineConfig(fsm),
        compose: composePlayer,
        actor: 'player',
        artifactSchema: 3,
      }),
    ).toEqual([]);
  });

  it('substitutes the player placeholders pinned at build time', () => {
    expect(
      deriveSubstitutions(findMachineConfig(fsm), composePlayer, 'player'),
    ).toEqual(PLAYER_SUBSTITUTED);
  });
});
