// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by slc (DR-014): the registry entry exposing the compiled
// playbook to `playbook run`. Derived deterministically from the compiled
// bundle; recompiling regenerates it.

import createPlaybookRuntime from './workflow.zh.playbook/workflow.zh.playbook.ts';

type RuntimeOptions = NonNullable<Parameters<typeof createPlaybookRuntime>[0]>;

const ALLOWED_OPTION_KEYS: readonly string[] = ['cwd'];

function validateOptions(value: unknown): RuntimeOptions {
  if (value === undefined) return {};
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new Error('playbook options must be an object');
  }
  const options: Record<string, string> = {};
  for (const [key, option] of Object.entries(value)) {
    if (!ALLOWED_OPTION_KEYS.includes(key)) {
      throw new Error(
        `unknown option "${key}" (allowed: ${ALLOWED_OPTION_KEYS.join(', ') || 'none'})`,
      );
    }
    if (typeof option !== 'string' || option === '') {
      throw new Error(`option "${key}" must be a non-empty string`);
    }
    options[key] = option;
  }
  return options as RuntimeOptions;
}

const entry = {
  id: 'workflow.zh',
  command: 'workflow.zh',
  intent: '工作流 — 用两个agent来完成输入的任务。',
  requiredRoleIds: ['编码者', '审查者'],
  validateOptions,
  createRuntime(options: { captainOptions?: unknown }) {
    const validated = validateOptions(options.captainOptions);
    return createPlaybookRuntime({
      ...validated,
      cwd: validated.cwd ?? process.cwd(),
    });
  },
};

export default entry;
