// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>

/**
 * Deterministic entry-module emission (DR-014, SELFHOST-15).
 *
 * After a successful full-link of the `playbook` pipeline, {@link
 * emitEntryModule} writes `<cwd>/<basename>.ts`: an erasable-TypeScript module
 * default-exporting a Playbook registry entry derived entirely from the
 * compiled bundle — `id`/`command` from the basename, `requiredRoleIds` from
 * the gears `Players:` declaration, `intent` from the normalized source's
 * title and lead line, an option allowlist carrying `cwd` exactly when the
 * source compiled a script item, and `createRuntime` wiring the linked default
 * factory. `playbook run ./<basename>.ts "<task>"` consumes it unchanged
 * (SELFHOST-14). See specs/dev/self-hosting.md.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import { parseGearsItems } from './verify.js';

/** Options for {@link emitEntryModule}. */
export interface EmitEntryModuleOptions {
  /** Invocation working directory the module is written into (DR-014). */
  cwd: string;
  /** The DR-001 basename naming the entry module and the bundle. */
  basename: string;
  /** Pipeline reference forming the bundle directory leaf `<basename>.<pipeline>`. */
  pipeline: string;
  /** The optimized gears artifact: players and script items. */
  gearsPath: string;
  /** The normalized (or entry-form) text source: title and lead line. */
  textPath: string;
}

/** Emits the entry module and returns its path. */
export async function emitEntryModule(
  opts: EmitEntryModuleOptions,
): Promise<string> {
  const gears = await readFile(opts.gearsPath, 'utf8');
  const text = await readFile(opts.textPath, 'utf8');
  const players = declaredPlayers(gears);
  const hasScript = parseGearsItems(gears).some(
    (item) => item.actor === 'script',
  );
  const intent = deriveIntent(text) ?? opts.basename;
  const path = join(opts.cwd, `${opts.basename}.ts`);
  await writeFile(
    path,
    renderEntryModule({
      basename: opts.basename,
      bundleLeaf: `${opts.basename}.${opts.pipeline}`,
      players,
      hasScript,
      intent,
    }),
    'utf8',
  );
  return path;
}

/**
 * The gears `Players:` declaration, verbatim in source order (SELFHOST-15).
 * Alias declarations (`` `A` = `B` | `C` ``) are launcher options, not
 * required roles, and are excluded.
 */
export function declaredPlayers(gears: string): string[] {
  const players: string[] = [];
  let inBlock = false;
  for (const line of gears.split('\n')) {
    if (/^Players:\s*$/.test(line)) {
      inBlock = true;
      continue;
    }
    if (!inBlock) continue;
    const bullet = /^-\s+(.*)$/.exec(line.trim());
    if (bullet === null) {
      if (line.trim() === '') continue;
      break;
    }
    const declaration = bullet[1];
    if (declaration.includes('=')) continue;
    const name = /^[`"“]?([^`"”]+?)[`"”]?\s*$/.exec(declaration.trim());
    if (name !== null && name[1].length > 0) players.push(name[1]);
  }
  return players;
}

/** Title and lead line of the normalized source, joined as the intent. */
function deriveIntent(text: string): string | undefined {
  let title: string | undefined;
  let lead: string | undefined;
  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (trimmed === '' || trimmed.startsWith('<!--')) continue;
    if (title === undefined) {
      const heading = /^#\s+(.*)$/.exec(trimmed);
      if (heading !== null) {
        title = heading[1].trim();
        continue;
      }
    }
    if (
      trimmed.startsWith('#') ||
      trimmed.startsWith('-') ||
      /^Players:\s*$/.test(trimmed)
    ) {
      continue;
    }
    lead = trimmed;
    break;
  }
  if (title !== undefined && lead !== undefined) return `${title} — ${lead}`;
  return title ?? lead;
}

function renderEntryModule(spec: {
  basename: string;
  bundleLeaf: string;
  players: readonly string[];
  hasScript: boolean;
  intent: string;
}): string {
  const allowed = spec.hasScript ? `['cwd']` : `[]`;
  const cwdWiring = spec.hasScript
    ? `{\n      ...validated,\n      cwd: validated.cwd ?? process.cwd(),\n    }`
    : `validated`;
  return `// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 SubLang International <https://sublang.ai>
//
// Generated by slc (DR-014): the registry entry exposing the compiled
// playbook to \`playbook run\`. Derived deterministically from the compiled
// bundle; recompiling regenerates it.

import createPlaybookRuntime from './${spec.bundleLeaf}/${spec.basename}.playbook.ts';

type RuntimeOptions = NonNullable<Parameters<typeof createPlaybookRuntime>[0]>;

const ALLOWED_OPTION_KEYS: readonly string[] = ${allowed};

function validateOptions(value: unknown): RuntimeOptions {
  if (value === undefined) return {};
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new Error('playbook options must be an object');
  }
  const options: Record<string, string> = {};
  for (const [key, option] of Object.entries(value)) {
    if (!ALLOWED_OPTION_KEYS.includes(key)) {
      throw new Error(
        \`unknown option "\${key}" (allowed: \${ALLOWED_OPTION_KEYS.join(', ') || 'none'})\`,
      );
    }
    if (typeof option !== 'string' || option === '') {
      throw new Error(\`option "\${key}" must be a non-empty string\`);
    }
    options[key] = option;
  }
  return options as RuntimeOptions;
}

const entry = {
  id: ${sourceString(spec.basename)},
  command: ${sourceString(spec.basename)},
  intent: ${sourceString(spec.intent)},
  requiredRoleIds: [${spec.players.map(sourceString).join(', ')}],
  validateOptions,
  createRuntime(options: { captainOptions?: unknown }) {
    const validated = validateOptions(options.captainOptions);
    return createPlaybookRuntime(${cwdWiring});
  },
};

export default entry;
`;
}

function sourceString(value: string): string {
  // Single-quoted source form (the repo's prettier style), derived from the
  // JSON escape so control characters stay escaped.
  const json = JSON.stringify(value)
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
  const inner = json.slice(1, -1).replace(/\\"/g, '"').replace(/'/g, "\\'");
  return `'${inner}'`;
}
